import type { SupportData } from "@/types/support";

export const SUPPORT_SEED: SupportData = {
  clients: [
    {
      id: "client_fellas",
      name: "Fellas Loaded",
      slug: "fellas-loaded",
      status: "active",
      reportingRecipient: "Liam",
      reportDueDay: 1,
    },
    {
      id: "client_wedge",
      name: "Wedge",
      slug: "wedge",
      status: "active",
      supportDaysPerMonth: 10,
      supportDaysUsed: 5,
      reportingRecipient: "Luke",
      reportDueDay: 1,
    },
  ],

  users: [
    {
      id: "user_owner",
      name: "Daniel",
      email: "owner@gitwork.local",
      role: "owner",
      assignedClientIds: ["client_fellas", "client_wedge"],
    },
    {
      id: "user_staff",
      name: "Support Staff",
      email: "staff@gitwork.local",
      role: "staff",
      assignedClientIds: ["client_wedge"],
    },
  ],

  connections: [
    {
      id: "conn_fellas_gmail",
      clientId: "client_fellas",
      source: "gmail",
      label: "Support inbox",
      authMode: "oauth",
      health: "needs_setup",
      nextStep: "Create shared mailbox access and connect Gmail OAuth.",
    },
    {
      id: "conn_fellas_discord",
      clientId: "client_fellas",
      source: "discord",
      label: "Community channels",
      authMode: "bot_token",
      health: "needs_setup",
      nextStep: "Create a new Discord bot account and add channel scopes.",
    },
    {
      id: "conn_fellas_reddit",
      clientId: "client_fellas",
      source: "reddit",
      label: "Subreddit monitoring",
      authMode: "manual",
      health: "needs_setup",
      nextStep: "Add the subreddit name below and run the scraper worker to start monitoring.",
      scraperConfig: { intervalHours: 12 },
    },
    {
      id: "conn_fellas_stripe",
      clientId: "client_fellas",
      source: "stripe",
      label: "Subscription support",
      authMode: "oauth",
      health: "needs_setup",
      nextStep: "Invite a shared admin user and rotate handover access.",
    },
    {
      id: "conn_wedge_gmail",
      clientId: "client_wedge",
      source: "gmail",
      label: "Support inbox",
      authMode: "oauth",
      health: "needs_setup",
      nextStep: "Connect support mailbox with least-privilege OAuth.",
    },
    {
      id: "conn_wedge_instagram",
      clientId: "client_wedge",
      source: "instagram",
      label: "Instagram comments",
      authMode: "oauth",
      health: "needs_setup",
      nextStep: "Connect Meta account after API permission approval.",
    },
    {
      id: "conn_wedge_youtube",
      clientId: "client_wedge",
      source: "youtube",
      label: "YouTube comments",
      authMode: "manual",
      health: "connected",
      nextStep: "Scraper polls public RSS feed and extracts comments via Playwright.",
      scraperConfig: { channelId: "WEDGE_CHANNEL_ID", intervalHours: 24 },
    },
    {
      id: "conn_wedge_reddit",
      clientId: "client_wedge",
      source: "reddit",
      label: "Subreddit monitoring",
      authMode: "manual",
      health: "connected",
      nextStep: "Scraper polls the subreddit's public JSON feed every 12 h.",
      scraperConfig: { subreddit: "wedgeapp", intervalHours: 12 },
    },
    {
      id: "conn_wedge_clickup",
      clientId: "client_wedge",
      source: "clickup",
      label: "Customer Support board",
      authMode: "api_key",
      health: "needs_setup",
      secretRef: "vault://gitwork/wedge/clickup",
      nextStep: "Store API token in vault, then map list statuses.",
    },
  ],

  conversations: [
    {
      id: "conv_fellas_email_code",
      clientId: "client_fellas",
      source: "gmail",
      customerLabel: "Customer F-001",
      subject: "Email code never arrived",
      preview: "Customer cannot find an active account and has been asked for transaction proof.",
      receivedAt: "2026-05-14T12:20:00.000Z",
      unread: true,
      tags: ["access", "subscription", "awaiting-customer"],
      sentiment: "negative",
    },
    {
      id: "conv_wedge_add_players",
      clientId: "client_wedge",
      source: "gmail",
      customerLabel: "Customer W-001",
      subject: "Issue adding players",
      preview: "Technical details requested before sharing with the dev team for investigation.",
      receivedAt: "2026-05-14T09:05:00.000Z",
      unread: true,
      tags: ["bug", "awaiting-customer", "urgent"],
      sentiment: "negative",
    },
    {
      id: "conv_wedge_scorecard_android",
      clientId: "client_wedge",
      source: "reddit",
      customerLabel: "Customer W-002",
      subject: "Android scorecard tracking issue",
      preview: "Shared with the team on 2026-05-05; no follow-up has been logged yet.",
      receivedAt: "2026-05-13T18:41:00.000Z",
      unread: false,
      tags: ["android", "dev-review"],
      sentiment: "neutral",
    },
    {
      id: "conv_wedge_course_request",
      clientId: "client_wedge",
      source: "instagram",
      customerLabel: "Customer W-003",
      subject: "Local course missing",
      preview: "Customer wants a local course added; provider update dependency needs tracking.",
      receivedAt: "2026-05-12T16:15:00.000Z",
      unread: false,
      tags: ["course-data", "provider"],
      sentiment: "negative",
    },
  ],

  messages: [
    {
      id: "msg_fellas_email_code_1",
      conversationId: "conv_fellas_email_code",
      direction: "inbound",
      authorLabel: "Customer F-001",
      body: "I paid but never received the email code. I cannot access the account.",
      createdAt: "2026-05-14T12:20:00.000Z",
    },
    {
      id: "msg_fellas_email_code_2",
      conversationId: "conv_fellas_email_code",
      direction: "outbound",
      authorLabel: "Support",
      body: "Thanks for reaching out. Please send proof of transaction so we can locate the account.",
      createdAt: "2026-05-14T12:34:00.000Z",
    },
    {
      id: "msg_wedge_players_1",
      conversationId: "conv_wedge_add_players",
      direction: "inbound",
      authorLabel: "Customer W-001",
      body: "Adding players breaks before I can save the round.",
      createdAt: "2026-05-14T09:05:00.000Z",
    },
    {
      id: "msg_wedge_players_2",
      conversationId: "conv_wedge_add_players",
      direction: "outbound",
      authorLabel: "Support",
      body: "Could you share device model, app version, and the steps you took before the issue appeared?",
      createdAt: "2026-05-14T09:21:00.000Z",
    },
  ],

  tickets: [
    {
      id: "ticket_fellas_email_code",
      clientId: "client_fellas",
      title: "Email code never arrived",
      customerLabel: "Customer F-001",
      status: "in_progress",
      priority: "high",
      source: "gmail",
      nextAction: "Wait for transaction proof before deciding the next step.",
      issueType: "Account access",
      updatedAt: "2026-05-14T12:34:00.000Z",
      assignedTo: "Support Staff",
    },
    {
      id: "ticket_wedge_add_players",
      clientId: "client_wedge",
      title: "Issue adding players",
      customerLabel: "Customer W-001",
      status: "in_progress",
      priority: "urgent",
      source: "gmail",
      nextAction: "Await technical details before escalating to development.",
      issueType: "App bug",
      updatedAt: "2026-05-14T09:21:00.000Z",
      assignedTo: "Support Staff",
    },
    {
      id: "ticket_wedge_scorecard",
      clientId: "client_wedge",
      title: "Android scorecard tracking issue",
      customerLabel: "Customer W-002",
      status: "dev_review",
      priority: "high",
      source: "reddit",
      nextAction: "Ask dev team whether the May 5 issue has been resolved.",
      issueType: "Android bug",
      updatedAt: "2026-05-13T18:41:00.000Z",
      assignedTo: "Dev Review",
    },
    {
      id: "ticket_wedge_course_request",
      clientId: "client_wedge",
      title: "Local course missing",
      customerLabel: "Customer W-003",
      status: "dev_review",
      priority: "high",
      source: "instagram",
      nextAction: "Add to provider update bundle when the next API report is prepared.",
      issueType: "Course data",
      updatedAt: "2026-05-12T16:15:00.000Z",
      assignedTo: "Dev Review",
    },
    {
      id: "ticket_wedge_course_data",
      clientId: "client_wedge",
      title: "Incorrect course data",
      customerLabel: "8 redacted customers",
      status: "dev_review",
      priority: "normal",
      source: "youtube",
      nextAction: "Include incorrect course data in the next provider update report.",
      issueType: "Course data",
      updatedAt: "2026-05-11T10:00:00.000Z",
      assignedTo: "Dev Review",
    },
  ],

  draftActions: [
    {
      id: "draft_wedge_api_reply",
      clientId: "client_wedge",
      ticketId: "ticket_wedge_course_request",
      type: "reply",
      title: "Course provider update reply",
      body: "Thanks for flagging this. We have added the course request to our provider update list and will follow up when the next data refresh is available.",
      status: "pending_approval",
      risk: "low",
    },
    {
      id: "draft_fellas_stripe_review",
      clientId: "client_fellas",
      ticketId: "ticket_fellas_email_code",
      type: "stripe_cancel",
      title: "Subscription lookup required",
      body: "Find the subscription from transaction proof, then prepare a cancellation or refund action for human approval.",
      status: "pending_approval",
      risk: "high",
    },
  ],

  workflowRules: [
    {
      id: "rule_fellas_cancellation",
      clientId: "client_fellas",
      name: "Subscription cancellation",
      when: "A Fellas Loaded user asks to cancel a subscription.",
      then: "Draft a Stripe lookup/cancellation action and require admin approval.",
      requiresApproval: true,
    },
    {
      id: "rule_wedge_api_issue",
      clientId: "client_wedge",
      name: "Course/API issue",
      when: "A Wedge message mentions course data, course requests, or provider data.",
      then: "Draft template reply and move ticket to Dev Review with provider-report tag.",
      requiresApproval: true,
    },
  ],

  auditLogs: [
    {
      id: "audit_1",
      clientId: "client_wedge",
      actor: "Daniel",
      action: "Imported handover seed",
      target: "Wedge tickets",
      createdAt: "2026-05-15T09:00:00.000Z",
    },
    {
      id: "audit_2",
      clientId: "client_fellas",
      actor: "Daniel",
      action: "Marked credentials for rotation",
      target: "Fellas Loaded account connections",
      createdAt: "2026-05-15T09:10:00.000Z",
    },
  ],
};
