/**
 * Static registry of all 515 Pulse checks.
 * Per-workspace overrides (enabled, label, severity) live in PulseCheckConfig.
 */

export interface CheckDefinition {
  key: string;
  category: string;
  label: string;
}

export const CHECKS_REGISTRY: CheckDefinition[] = [
  { key: "store_app_title", category: "Store Listing", label: "App name / title" },
  { key: "store_description", category: "Store Listing", label: "App description" },
  { key: "store_screenshots", category: "Store Listing", label: "Screenshots / preview assets" },
  { key: "store_ratings", category: "Store Listing", label: "Ratings & reviews" },
  { key: "store_privacy_policy", category: "Store Listing", label: "Privacy policy linked" },
  { key: "store_age_rating", category: "Store Listing", label: "Age / content rating" },
  { key: "store_iap_disclosed", category: "Store Listing", label: "In-app purchases disclosed" },
  { key: "appstore_subtitle", category: "Store Listing", label: "App subtitle (keyword field)" },
  { key: "appstore_privacy_label", category: "Store Listing", label: "Apple privacy nutrition label" },
  { key: "playstore_data_safety", category: "Store Listing", label: "Data Safety section" },
  { key: "playstore_content_rating", category: "Store Listing", label: "IARC content rating" },
  { key: "ssl_valid", category: "SEO", label: "HTTPS / SSL certificate" },
  { key: "http_redirect", category: "Infrastructure", label: "HTTP → HTTPS redirect" },
  { key: "response_time", category: "Infrastructure", label: "Response time" },
  { key: "status_200", category: "Infrastructure", label: "Returns 200 OK" },
  { key: "custom_domain", category: "Infrastructure", label: "Custom domain" },
  { key: "cdn_detected", category: "Infrastructure", label: "CDN present" },
  { key: "meta_title", category: "SEO", label: "<title> tag" },
  { key: "meta_description", category: "SEO", label: "Meta description" },
  { key: "og_tags", category: "SEO", label: "Open Graph tags" },
  { key: "canonical_url", category: "SEO", label: "Canonical URL" },
  { key: "h1_present", category: "SEO", label: "H1 heading" },
  { key: "has_robots_txt", category: "SEO", label: "robots.txt" },
  { key: "has_sitemap", category: "SEO", label: "sitemap.xml" },
  { key: "csp_header", category: "Security", label: "Content-Security-Policy" },
  { key: "hsts_header", category: "Security", label: "HSTS header" },
  { key: "x_frame_options", category: "Security", label: "Clickjacking protection" },
  { key: "no_exposed_env", category: "Security", label: ".env not public" },
  { key: "no_exposed_git", category: "Security", label: ".git directory not public" },
  { key: "compression", category: "Performance", label: "Gzip/Brotli compression" },
  { key: "caching_headers", category: "Performance", label: "Cache-Control headers" },
  { key: "stripe_signals", category: "Payments", label: "Stripe integration" },
  { key: "pricing_page", category: "Payments", label: "Pricing/billing UI" },
  { key: "auth_ui_signals", category: "Authentication", label: "Login/signup UI" },
  { key: "oauth_signals", category: "Authentication", label: "Auth provider" },
  { key: "error_monitoring", category: "Observability", label: "Error monitoring" },
  { key: "analytics_present", category: "Observability", label: "Analytics" },
  { key: "health_endpoint", category: "Observability", label: "/health endpoint" },
  { key: "privacy_policy", category: "Legal & Compliance", label: "Privacy Policy" },
  { key: "terms_of_service", category: "Legal & Compliance", label: "Terms of Service" },
  { key: "cookie_consent", category: "Legal & Compliance", label: "Cookie consent / GDPR" },
  { key: "refund_policy", category: "Legal & Compliance", label: "Refund / Cancellation policy" },
  { key: "about_page", category: "Missing Pages", label: "About / Team page" },
  { key: "contact_page", category: "Missing Pages", label: "Contact page" },
  { key: "faq_page", category: "Missing Pages", label: "FAQ / Help page" },
  { key: "status_page", category: "Missing Pages", label: "Status / uptime page" },
  { key: "changelog", category: "Missing Pages", label: "Changelog / What" },
  { key: "billing_portal", category: "SaaS Readiness", label: "Billing / subscription management" },
  { key: "account_settings", category: "SaaS Readiness", label: "Account settings" },
  { key: "password_reset", category: "SaaS Readiness", label: "Password reset" },
  { key: "support_channel", category: "SaaS Readiness", label: "Support channel" },
  { key: "social_proof", category: "SaaS Readiness", label: "Social proof / testimonials" },
  { key: "onboarding_flow", category: "SaaS Readiness", label: "Onboarding flow" },
  { key: "viewport_meta", category: "Mobile & Accessibility", label: "Viewport meta tag" },
  { key: "html_lang", category: "Mobile & Accessibility", label: "HTML language attribute" },
  { key: "aria_attributes", category: "Mobile & Accessibility", label: "ARIA accessibility attributes" },
  { key: "responsive_images", category: "Mobile & Accessibility", label: "Responsive / optimised images" },
  { key: "og_image", category: "SEO", label: "og:image (social preview)" },
  { key: "twitter_card", category: "SEO", label: "Twitter / X Card" },
  { key: "x_content_type_options", category: "Security", label: "X-Content-Type-Options" },
  { key: "permissions_policy", category: "Security", label: "Permissions-Policy" },
  { key: "referrer_policy", category: "Security", label: "Referrer-Policy" },
  { key: "email_provider", category: "SaaS Readiness", label: "Transactional email provider" },
  { key: "ai_platform_origin", category: "Code Quality", label: "AI platform watermark" },
  { key: "favicon", category: "Mobile & Accessibility", label: "Favicon / app icon" },
  { key: "pwa_manifest", category: "Mobile & Accessibility", label: "Web App Manifest (PWA)" },
  { key: "stripe_webhook", category: "Payments", label: "Stripe webhook endpoint" },
  { key: "apple_touch_icon", category: "App Store & Mobile", label: "Apple touch icon" },
  { key: "apple_app_store", category: "App Store & Mobile", label: "Apple App Store presence" },
  { key: "google_play_store", category: "App Store & Mobile", label: "Google Play Store presence" },
  { key: "universal_links", category: "App Store & Mobile", label: "Universal Links (iOS deep linking)" },
  { key: "android_asset_links", category: "App Store & Mobile", label: "Android App Links (deep linking)" },
  { key: "wallet_payments", category: "App Store & Mobile", label: "Apple Pay / Google Pay / Amazon Pay" },
  { key: "hreflang_tags", category: "Global Distribution", label: "hreflang tags (multi-region SEO)" },
  { key: "charset_utf8", category: "Global Distribution", label: "UTF-8 character encoding" },
  { key: "ccpa_compliance", category: "Global Distribution", label: "CCPA (California privacy rights)" },
  { key: "multi_currency", category: "Global Distribution", label: "Multi-currency pricing" },
  { key: "rtl_support", category: "Global Distribution", label: "RTL language support" },
  { key: "language_switcher", category: "Global Distribution", label: "Language / region switcher" },
  { key: "international_payments", category: "Global Distribution", label: "International payment methods" },
  { key: "eu_vat", category: "Global Distribution", label: "EU VAT / tax handling" },
  { key: "structured_data", category: "SEO", label: "JSON-LD structured data" },
  { key: "preload_hints", category: "SEO", label: "Resource preload hints" },
  { key: "search_engine_verified", category: "SEO", label: "Search engine verification" },
  { key: "meta_robots", category: "SEO", label: "Robots meta tag" },
  { key: "og_site_name", category: "SEO", label: "og:site_name (brand in shares)" },
  { key: "subresource_integrity", category: "Security", label: "Subresource Integrity (SRI)" },
  { key: "secure_cookie_attributes", category: "Security", label: "Secure cookie attributes" },
  { key: "cors_policy", category: "Security", label: "CORS policy" },
  { key: "security_txt", category: "Security", label: "security.txt (responsible disclosure)" },
  { key: "server_header_leakage", category: "Security", label: "Server version not exposed" },
  { key: "no_mixed_content", category: "Security", label: "No mixed HTTP/HTTPS content" },
  { key: "preconnect_hints", category: "Performance", label: "Preconnect / DNS prefetch hints" },
  { key: "native_lazy_loading", category: "Performance", label: "Native image lazy loading" },
  { key: "font_display_swap", category: "Performance", label: "Font display optimisation" },
  { key: "vary_header", category: "Performance", label: "Vary header (content negotiation)" },
  { key: "server_timing", category: "Performance", label: "Server-Timing header" },
  { key: "mfa_signals", category: "Authentication", label: "Multi-factor authentication (MFA)" },
  { key: "email_verification_flow", category: "Authentication", label: "Email verification flow" },
  { key: "magic_link_auth", category: "Authentication", label: "Magic link / passwordless login" },
  { key: "enterprise_sso", category: "Authentication", label: "Enterprise SSO / SAML" },
  { key: "data_deletion_right", category: "Legal & Compliance", label: "Data deletion / right to erasure (GDPR Art. 17)" },
  { key: "accessibility_statement", category: "Legal & Compliance", label: "Accessibility statement" },
  { key: "coppa_signals", category: "Legal & Compliance", label: "COPPA / children" },
  { key: "dpa_available", category: "Legal & Compliance", label: "Data Processing Agreement (GDPR Art. 28)" },
  { key: "icp_license", category: "Legal & Compliance", label: "China ICP license (for CN market)" },
  { key: "privacy_last_updated", category: "Legal & Compliance", label: "Privacy policy maintenance date" },
  { key: "cookie_policy_page", category: "Legal & Compliance", label: "Dedicated cookie policy page" },
  { key: "gdpr_dpo_contact", category: "Legal & Compliance", label: "GDPR privacy contact (DPO)" },
  { key: "blog_resources", category: "Missing Pages", label: "Blog / resources hub" },
  { key: "careers_page", category: "Missing Pages", label: "Careers / jobs page" },
  { key: "press_media", category: "Missing Pages", label: "Press / media page" },
  { key: "documentation", category: "Missing Pages", label: "Documentation / developer docs" },
  { key: "integrations_page", category: "Missing Pages", label: "Integrations / partners page" },
  { key: "custom_404_page", category: "Missing Pages", label: "Custom 404 error page" },
  { key: "demo_booking", category: "SaaS Readiness", label: "Demo booking / discovery call" },
  { key: "free_trial_cta", category: "SaaS Readiness", label: "Free trial / free plan CTA" },
  { key: "api_availability", category: "SaaS Readiness", label: "Public API / developer access" },
  { key: "affiliate_program", category: "SaaS Readiness", label: "Affiliate / referral program" },
  { key: "security_trust_page", category: "SaaS Readiness", label: "Security / trust page" },
  { key: "in_app_notifications", category: "SaaS Readiness", label: "In-app notification system" },
  { key: "uptime_monitoring", category: "Observability", label: "External uptime monitoring" },
  { key: "log_aggregation", category: "Observability", label: "Centralised log aggregation" },
  { key: "apm_signals", category: "Observability", label: "Application Performance Monitoring (APM)" },
  { key: "real_user_monitoring", category: "Observability", label: "Real User Monitoring (RUM)" },
  { key: "payment_trust_badges", category: "Payments", label: "Payment trust badges" },
  { key: "bnpl_options", category: "Payments", label: "Buy Now Pay Later (BNPL)" },
  { key: "crypto_payments", category: "Payments", label: "Cryptocurrency payment option" },
  { key: "smart_app_banner_meta", category: "App Store & Mobile", label: "Smart App Banner (iOS web-to-app)" },
  { key: "amazon_app_store", category: "App Store & Mobile", label: "Amazon Appstore / Fire TV presence" },
  { key: "app_listing_screenshots", category: "App Store & Mobile", label: "App screenshots / listing assets" },
  { key: "app_icon_sizes", category: "App Store & Mobile", label: "App icon multiple resolutions" },
  { key: "country_region_selector", category: "Global Distribution", label: "Country / region selector" },
  { key: "compliance_certifications", category: "Global Distribution", label: "Compliance certifications (SOC 2, ISO 27001)" },
  { key: "eu_data_residency", category: "Global Distribution", label: "EU data residency signals" },
  { key: "company_registration_info", category: "Global Distribution", label: "Company registration info" },
  { key: "timezone_locale_support", category: "Global Distribution", label: "Timezone / locale-aware content" },
  { key: "social_media_links", category: "Trust & Brand", label: "Social media presence" },
  { key: "third_party_reviews", category: "Trust & Brand", label: "Third-party review platform" },
  { key: "press_coverage", category: "Trust & Brand", label: "Press / media coverage section" },
  { key: "team_presence", category: "Trust & Brand", label: "Founder / team bio with photo" },
  { key: "product_hunt_badge", category: "Trust & Brand", label: "Product Hunt launch presence" },
  { key: "media_kit", category: "Trust & Brand", label: "Media kit / brand assets" },
  { key: "no_placeholder_text", category: "Code Quality", label: "No placeholder / lorem ipsum content" },
  { key: "no_hash_routing", category: "Code Quality", label: "Clean URL routing (no hash routes)" },
  { key: "spf_record", category: "Security", label: "SPF record (email spoofing protection)" },
  { key: "dmarc_record", category: "Security", label: "DMARC record (email impersonation protection)" },
  { key: "mx_record", category: "Infrastructure", label: "MX records (email infrastructure)" },
  { key: "no_exposed_admin", category: "Security", label: "Admin panel not publicly accessible" },
  { key: "no_exposed_phpinfo", category: "Security", label: "PHP info page not exposed" },
  { key: "no_exposed_git_config", category: "Security", label: "Git config not publicly accessible" },
  { key: "no_debug_endpoints", category: "Security", label: "Debug/monitoring endpoints not public" },
  { key: "no_exposed_backup", category: "Security", label: "Database backup files not exposed" },
  { key: "http2_enabled", category: "Performance", label: "HTTP/2 protocol" },
  { key: "no_x_powered_by", category: "Security", label: "X-Powered-By header absent" },
  { key: "no_server_version", category: "Security", label: "Server version not disclosed" },
  { key: "cors_not_wildcard", category: "Security", label: "CORS not open to all origins" },
  { key: "has_word_count", category: "SEO", label: "Sufficient page content" },
  { key: "has_heading_hierarchy", category: "SEO", label: "Heading hierarchy (H1→H2→H3)" },
  { key: "image_alt_coverage", category: "Accessibility", label: "Image alt text coverage" },
  { key: "internal_links_present", category: "SEO", label: "Internal linking" },
  { key: "no_broken_inline_scripts", category: "Code Quality", label: "No console.log in production HTML" },
  { key: "service_worker_present", category: "Performance", label: "Service worker (offline/caching)" },
  { key: "web_app_manifest_linked", category: "Performance", label: "Web app manifest linked" },
  { key: "theme_color_defined", category: "Performance", label: "Theme colour meta tag" },
  { key: "third_party_script_count", category: "Performance", label: "Third-party script load" },
  { key: "no_jquery_old", category: "Code Quality", label: "No outdated jQuery" },
  { key: "annual_billing_signal", category: "SaaS Readiness", label: "Annual billing option" },
  { key: "money_back_signal", category: "SaaS Readiness", label: "Money-back guarantee signal" },
  { key: "live_chat_signal", category: "SaaS Readiness", label: "Live chat / support widget" },
  { key: "demo_booking_signal", category: "SaaS Readiness", label: "Demo booking or discovery call" },
  { key: "social_proof_numbers", category: "Trust & Brand", label: "Quantified social proof" },
  { key: "video_embed_present", category: "SaaS Readiness", label: "Product demo video" },
  { key: "api_docs_signal", category: "SaaS Readiness", label: "API documentation" },
  { key: "openapi_endpoint", category: "SaaS Readiness", label: "OpenAPI spec endpoint" },
  { key: "graphql_signal", category: "SaaS Readiness", label: "GraphQL API" },
  { key: "search_functionality", category: "SaaS Readiness", label: "Search functionality" },
  { key: "cookie_consent_granular", category: "Legal & Compliance", label: "Granular cookie consent (accept/reject all)" },
  { key: "newsletter_signup", category: "SaaS Readiness", label: "Newsletter / email list capture" },
  { key: "repo_parse", category: "Code Quality", label: "Repository URL" },
  { key: "has_readme", category: "Code Quality", label: "README.md" },
  { key: "has_tests", category: "Code Quality", label: "Test suite" },
  { key: "has_linter", category: "Code Quality", label: "Linter config" },
  { key: "has_typescript", category: "Code Quality", label: "TypeScript" },
  { key: "has_env_example", category: "Code Quality", label: ".env.example" },
  { key: "ci_cd_present", category: "Code Quality", label: "CI/CD pipeline" },
  { key: "has_license", category: "Code Quality", label: "License file" },
  { key: "has_manifest", category: "Infrastructure", label: "Dependency manifest" },
  { key: "dockerfile_present", category: "Infrastructure", label: "Dockerfile / Docker Compose" },
  { key: "has_contributing", category: "Code Quality", label: "CONTRIBUTING.md" },
  { key: "has_code_of_conduct", category: "Code Quality", label: "Code of Conduct" },
  { key: "has_security_md", category: "Code Quality", label: "SECURITY.md (vulnerability disclosure)" },
  { key: "has_dependabot", category: "Code Quality", label: "Dependabot / automated dependency updates" },
  { key: "has_changelog_file", category: "Code Quality", label: "CHANGELOG.md" },
  { key: "has_openapi_spec", category: "Code Quality", label: "OpenAPI / Swagger spec" },
  { key: "has_editorconfig", category: "Code Quality", label: ".editorconfig (consistent formatting)" },
  { key: "has_gitignore", category: "Code Quality", label: ".gitignore" },
  { key: "has_e2e_tests", category: "Code Quality", label: "E2E test suite (Playwright / Cypress)" },
  { key: "has_unit_test_config", category: "Code Quality", label: "Unit test framework (Jest / Vitest)" },
  { key: "has_git_hooks", category: "Code Quality", label: "Git hooks (Husky / lefthook)" },
  { key: "has_orm_config", category: "Infrastructure", label: "ORM / database configuration" },
  { key: "has_migrations", category: "Infrastructure", label: "Database migrations" },
  { key: "has_renovate", category: "Code Quality", label: "Renovate / automated dependency updates" },
  { key: "has_devcontainer", category: "Infrastructure", label: "Dev container (.devcontainer)" },
  { key: "has_infra_code", category: "Infrastructure", label: "Infrastructure as Code (Terraform / Helm / K8s)" },
  { key: "has_makefile", category: "Code Quality", label: "Makefile / task runner" },
  { key: "is_monorepo", category: "Code Quality", label: "Monorepo tooling (Turbo / Nx / pnpm workspaces)" },
  { key: "has_coverage_config", category: "Code Quality", label: "Code coverage reporting" },

  // ─── Security Extended (30) ─────────────────────────────────────────────────
  { key: "cross_origin_opener_policy", category: "Security", label: "Cross-Origin-Opener-Policy (COOP)" },
  { key: "cross_origin_resource_policy", category: "Security", label: "Cross-Origin-Resource-Policy (CORP)" },
  { key: "cross_origin_embedder_policy", category: "Security", label: "Cross-Origin-Embedder-Policy (COEP)" },
  { key: "csp_report_directive", category: "Security", label: "CSP report-uri / report-to configured" },
  { key: "rate_limiting_headers", category: "Security", label: "Rate-limiting headers present" },
  { key: "caa_dns_record", category: "Security", label: "CAA DNS record (cert authority restriction)" },
  { key: "dnssec_enabled", category: "Security", label: "DNSSEC enabled on domain" },
  { key: "certificate_expiry_30d", category: "Security", label: "SSL cert not expiring within 30 days" },
  { key: "no_exposed_ds_store", category: "Security", label: ".DS_Store not publicly accessible" },
  { key: "no_exposed_composer_json", category: "Security", label: "composer.json not at web root" },
  { key: "no_exposed_package_json_root", category: "Security", label: "package.json not served at root" },
  { key: "no_exposed_swagger_open", category: "Security", label: "Swagger UI not open in production" },
  { key: "no_exposed_actuator", category: "Security", label: "/actuator endpoints not public" },
  { key: "no_exposed_prometheus_metrics", category: "Security", label: "/metrics endpoint not public" },
  { key: "no_graphql_introspection_prod", category: "Security", label: "GraphQL introspection disabled in prod" },
  { key: "no_exposed_source_maps", category: "Security", label: "Source maps not served with page" },
  { key: "no_api_keys_in_html", category: "Security", label: "No API key patterns in HTML source" },
  { key: "csrf_protection_signals", category: "Security", label: "CSRF token protection detected" },
  { key: "bot_protection_present", category: "Security", label: "Bot protection (Cloudflare / reCAPTCHA)" },
  { key: "sql_error_exposure", category: "Security", label: "No SQL errors exposed in responses" },
  { key: "brute_force_protection", category: "Security", label: "Brute force / rate limit on auth" },
  { key: "session_cookie_httponly", category: "Security", label: "HttpOnly flag on session cookies" },
  { key: "session_cookie_samesite", category: "Security", label: "SameSite attribute on cookies" },
  { key: "csp_frame_ancestors", category: "Security", label: "frame-ancestors in CSP policy" },
  { key: "no_exposed_env_variants", category: "Security", label: ".env.prod / .env.docker not accessible" },
  { key: "secret_scanning_github", category: "Security", label: "No secrets / keys in page HTML" },
  { key: "cors_credentials_restricted", category: "Security", label: "CORS credentials not open to all origins" },
  { key: "dependency_audit_clean", category: "Security", label: "No obvious vulnerable library versions" },
  { key: "subdomain_takeover_risk", category: "Security", label: "No dangling CNAME / subdomain takeover risk" },
  { key: "content_security_policy_nonce", category: "Security", label: "CSP uses nonces (not unsafe-inline)" },

  // ─── Legal & Compliance Extended (35) ──────────────────────────────────────
  { key: "gdpr_article13_notice", category: "Legal & Compliance", label: "Data collection notice (GDPR Art. 13/14)" },
  { key: "gdpr_right_to_access", category: "Legal & Compliance", label: "Right to access data (GDPR Art. 15)" },
  { key: "gdpr_right_to_erasure_ui", category: "Legal & Compliance", label: "Right to erasure UI (GDPR Art. 17)" },
  { key: "gdpr_right_to_portability", category: "Legal & Compliance", label: "Data portability (GDPR Art. 20)" },
  { key: "gdpr_right_to_object", category: "Legal & Compliance", label: "Right to object to processing (GDPR Art. 21)" },
  { key: "gdpr_lawful_basis_stated", category: "Legal & Compliance", label: "Lawful basis stated in privacy policy" },
  { key: "gdpr_breach_notification", category: "Legal & Compliance", label: "Breach notification procedure (GDPR Art. 33)" },
  { key: "gdpr_records_processing", category: "Legal & Compliance", label: "Records of Processing Activities (GDPR Art. 30)" },
  { key: "uk_gdpr_ico_registration", category: "Legal & Compliance", label: "ICO registration number shown (UK GDPR)" },
  { key: "eu_representative_contact", category: "Legal & Compliance", label: "EU Art. 27 representative for non-EU companies" },
  { key: "eprivacy_pecr_compliance", category: "Legal & Compliance", label: "UK PECR / ePrivacy cookie compliance" },
  { key: "digital_markets_act", category: "Legal & Compliance", label: "EU Digital Markets Act compliance signals" },
  { key: "eu_ai_act_disclosure", category: "Legal & Compliance", label: "EU AI Act transparency disclosure" },
  { key: "lgpd_brazil", category: "Legal & Compliance", label: "Brazil LGPD compliance" },
  { key: "pipeda_canada", category: "Legal & Compliance", label: "Canada PIPEDA / Law 25 compliance" },
  { key: "pdpa_singapore", category: "Legal & Compliance", label: "Singapore PDPA compliance" },
  { key: "pdpa_thailand", category: "Legal & Compliance", label: "Thailand PDPA compliance" },
  { key: "popia_south_africa", category: "Legal & Compliance", label: "South Africa POPIA compliance" },
  { key: "appi_japan", category: "Legal & Compliance", label: "Japan APPI compliance" },
  { key: "pipl_china", category: "Legal & Compliance", label: "China PIPL compliance" },
  { key: "pipa_korea", category: "Legal & Compliance", label: "South Korea PIPA compliance" },
  { key: "dpdp_india", category: "Legal & Compliance", label: "India DPDP Act compliance" },
  { key: "australian_privacy_act", category: "Legal & Compliance", label: "Australian Privacy Act compliance" },
  { key: "hipaa_signals", category: "Legal & Compliance", label: "HIPAA compliance signals (healthcare)" },
  { key: "pci_dss_scope_reduction", category: "Legal & Compliance", label: "PCI DSS scope reduction evidence" },
  { key: "ferpa_signals", category: "Legal & Compliance", label: "FERPA compliance signals (education)" },
  { key: "cooling_off_period_eu", category: "Legal & Compliance", label: "EU 14-day cancellation right stated" },
  { key: "auto_renewal_disclosure", category: "Legal & Compliance", label: "Auto-renewal terms prominently disclosed" },
  { key: "subscription_cancellation_easy", category: "Legal & Compliance", label: "Easy cancellation (FTC click-to-cancel)" },
  { key: "price_vat_inclusive", category: "Legal & Compliance", label: "Prices shown inc. VAT (EU requirement)" },
  { key: "distance_selling_notice", category: "Legal & Compliance", label: "EU Distance Selling regulations disclosure" },
  { key: "intellectual_property_notice", category: "Legal & Compliance", label: "Copyright notice present" },
  { key: "dmca_policy", category: "Legal & Compliance", label: "DMCA takedown procedure" },
  { key: "age_gate", category: "Legal & Compliance", label: "Age verification / age gate" },
  { key: "contract_terms_b2b", category: "Legal & Compliance", label: "B2B contract terms / SLA documented" },

  // ─── Performance Extended (20) ──────────────────────────────────────────────
  { key: "next_gen_image_formats", category: "Performance", label: "Next-gen image formats (WebP / AVIF)" },
  { key: "image_dimension_attributes", category: "Performance", label: "Image width/height attributes (CLS prevention)" },
  { key: "critical_css_inlined", category: "Performance", label: "Critical CSS inlined in <head>" },
  { key: "css_appears_minified", category: "Performance", label: "CSS appears minified" },
  { key: "js_appears_minified", category: "Performance", label: "JS files appear minified" },
  { key: "http3_quic_support", category: "Performance", label: "HTTP/3 / QUIC support" },
  { key: "early_hints_support", category: "Performance", label: "103 Early Hints support" },
  { key: "stale_while_revalidate", category: "Performance", label: "Stale-while-revalidate cache directive" },
  { key: "immutable_cache_assets", category: "Performance", label: "Immutable cache on hashed assets" },
  { key: "dns_ttl_optimized", category: "Performance", label: "DNS TTL not near-zero" },
  { key: "render_blocking_scripts", category: "Performance", label: "No render-blocking scripts" },
  { key: "lcp_fetchpriority_hint", category: "Performance", label: "fetchpriority=high on LCP image" },
  { key: "image_width_height", category: "Performance", label: "Images have explicit width/height" },
  { key: "font_preload_hint", category: "Performance", label: "Fonts preloaded" },
  { key: "total_page_weight", category: "Performance", label: "Total page weight < 3MB" },
  { key: "third_party_script_blocking", category: "Performance", label: "No render-blocking third-party scripts" },
  { key: "no_unused_javascript", category: "Performance", label: "Code splitting / lazy loading signals" },
  { key: "module_script_type", category: "Performance", label: "type=module on script tags" },
  { key: "resource_hints_comprehensive", category: "Performance", label: "Comprehensive resource hints" },
  { key: "woff2_font_format", category: "Performance", label: "WOFF2 font format used" },

  // ─── WCAG Accessibility (20) ─────────────────────────────────────────────────
  { key: "skip_to_main_content", category: "Accessibility", label: "Skip to main content link" },
  { key: "image_input_alt", category: "Accessibility", label: "<input type=image> has alt text" },
  { key: "video_captions", category: "Accessibility", label: "Video has captions track" },
  { key: "form_labels_present", category: "Accessibility", label: "<label> for every <input>" },
  { key: "form_error_identification", category: "Accessibility", label: "Form errors identify the field" },
  { key: "keyboard_focus_visible", category: "Accessibility", label: ":focus-visible CSS present" },
  { key: "touch_target_size", category: "Accessibility", label: "Sufficient touch target sizing" },
  { key: "no_autoplay_audio", category: "Accessibility", label: "No autoplay audio without controls" },
  { key: "no_autoplay_video", category: "Accessibility", label: "No autoplay video without controls" },
  { key: "session_timeout_warning", category: "Accessibility", label: "Session timeout warning" },
  { key: "valid_html_parsing", category: "Accessibility", label: "No obvious HTML parsing errors" },
  { key: "aria_roles_valid", category: "Accessibility", label: "ARIA landmark roles used" },
  { key: "aria_live_regions", category: "Accessibility", label: "aria-live for dynamic content" },
  { key: "prefers_reduced_motion", category: "Accessibility", label: "prefers-reduced-motion CSS" },
  { key: "prefers_high_contrast", category: "Accessibility", label: "prefers-contrast CSS media query" },
  { key: "sufficient_colour_contrast", category: "Accessibility", label: "No obvious low-contrast inline styles" },
  { key: "text_spacing_supported", category: "Accessibility", label: "Letter/word spacing not fixed" },
  { key: "link_purpose_clear", category: "Accessibility", label: "Links have descriptive text" },
  { key: "page_title_unique", category: "Accessibility", label: "Unique page title" },
  { key: "language_attribute_body", category: "Accessibility", label: "lang attribute on <html> element" },

  // ─── Authentication Extended (15) ───────────────────────────────────────────
  { key: "session_timeout_configured", category: "Authentication", label: "Session timeout configured" },
  { key: "account_lockout_policy", category: "Authentication", label: "Account lockout policy" },
  { key: "password_strength_enforced", category: "Authentication", label: "Password strength requirements" },
  { key: "passkey_webauthn_support", category: "Authentication", label: "Passkeys / WebAuthn support" },
  { key: "breach_password_detection", category: "Authentication", label: "Breach password detection" },
  { key: "account_recovery_options", category: "Authentication", label: "Account recovery beyond email" },
  { key: "jwt_not_in_localstorage", category: "Authentication", label: "JWT not stored in localStorage" },
  { key: "refresh_token_rotation", category: "Authentication", label: "Refresh token rotation" },
  { key: "pkce_oauth_flow", category: "Authentication", label: "PKCE for OAuth public clients" },
  { key: "api_key_creation_ui", category: "Authentication", label: "API key generation UI" },
  { key: "oauth_minimal_scopes", category: "Authentication", label: "Minimal OAuth scope requests" },
  { key: "service_account_support", category: "Authentication", label: "Machine-to-machine / service account tokens" },
  { key: "device_management", category: "Authentication", label: "Trusted device management" },
  { key: "concurrent_session_policy", category: "Authentication", label: "Concurrent session limiting" },
  { key: "token_expiry_short", category: "Authentication", label: "Short-lived access tokens (< 1hr)" },

  // ─── Roles & Permissions (20) ───────────────────────────────────────────────
  { key: "rbac_signals", category: "Roles & Permissions", label: "Role-based access control (RBAC) UI" },
  { key: "admin_role_separation", category: "Roles & Permissions", label: "Admin vs user role separation" },
  { key: "team_management_ui", category: "Roles & Permissions", label: "Team / org management UI" },
  { key: "invite_workflow", category: "Roles & Permissions", label: "User invitation workflow" },
  { key: "permission_matrix_docs", category: "Roles & Permissions", label: "Permissions matrix documentation" },
  { key: "data_scope_isolation", category: "Roles & Permissions", label: "Multi-tenant data isolation signals" },
  { key: "audit_trail_present", category: "Roles & Permissions", label: "Audit log / activity log" },
  { key: "api_scope_documentation", category: "Roles & Permissions", label: "API scopes documented" },
  { key: "least_privilege_api_tokens", category: "Roles & Permissions", label: "Scoped / least-privilege API tokens" },
  { key: "role_hierarchy", category: "Roles & Permissions", label: "Admin > Manager > User role hierarchy" },
  { key: "access_revocation_ui", category: "Roles & Permissions", label: "Account deactivation / access revocation UI" },
  { key: "ip_allowlisting", category: "Roles & Permissions", label: "IP restriction / allowlist available" },
  { key: "sso_scim_provisioning", category: "Roles & Permissions", label: "SCIM provisioning support" },
  { key: "mfa_admin_enforced", category: "Roles & Permissions", label: "MFA required for admin accounts" },
  { key: "guest_anonymous_mode", category: "Roles & Permissions", label: "Guest / view-only mode" },
  { key: "read_only_role", category: "Roles & Permissions", label: "Read-only role available" },
  { key: "data_export_permission", category: "Roles & Permissions", label: "Data export restricted by role" },
  { key: "workspace_tenant_isolation", category: "Roles & Permissions", label: "Workspace / tenant isolation" },
  { key: "permission_inheritance", category: "Roles & Permissions", label: "Permission inheritance (groups)" },
  { key: "gdpr_data_access_control", category: "Roles & Permissions", label: "GDPR data access controlled by role" },

  // ─── Email Deliverability (15) ───────────────────────────────────────────────
  { key: "dkim_record_present", category: "Email Deliverability", label: "DKIM record configured" },
  { key: "bimi_record_present", category: "Email Deliverability", label: "BIMI DNS record (brand in inbox)" },
  { key: "mta_sts_policy", category: "Email Deliverability", label: "MTA-STS enforced mail transfer" },
  { key: "tls_rpt_record", category: "Email Deliverability", label: "TLS-RPT reporting record" },
  { key: "spf_hardfail", category: "Email Deliverability", label: "SPF uses -all (hardfail)" },
  { key: "dmarc_quarantine_reject", category: "Email Deliverability", label: "DMARC policy: quarantine or reject" },
  { key: "email_unsubscribe_signal", category: "Email Deliverability", label: "Unsubscribe / list management link" },
  { key: "transactional_subdomain", category: "Email Deliverability", label: "Dedicated sending subdomain" },
  { key: "can_spam_address", category: "Email Deliverability", label: "Physical address in email footer" },
  { key: "casl_double_optin", category: "Email Deliverability", label: "Double opt-in / CASL signals" },
  { key: "plain_text_email", category: "Email Deliverability", label: "Plain text email alternative" },
  { key: "bounce_handling_signal", category: "Email Deliverability", label: "Bounce handling / list hygiene" },
  { key: "email_preview_configured", category: "Email Deliverability", label: "Email preview text configured" },
  { key: "email_warm_up_signals", category: "Email Deliverability", label: "Reputable ESP detected" },
  { key: "mailing_list_segmentation", category: "Email Deliverability", label: "Email segmentation / tagging signals" },

  // ─── Observability Extended (15) ────────────────────────────────────────────
  { key: "alert_pagerduty_opsgenie", category: "Observability", label: "PagerDuty / OpsGenie / alerting configured" },
  { key: "on_call_configured", category: "Observability", label: "On-call rotation configured" },
  { key: "distributed_tracing", category: "Observability", label: "Distributed tracing configured" },
  { key: "custom_business_metrics", category: "Observability", label: "Custom business metrics / dashboards" },
  { key: "synthetic_monitoring", category: "Observability", label: "Synthetic monitoring (uptime checks)" },
  { key: "structured_logging", category: "Observability", label: "Structured / JSON logging" },
  { key: "log_retention_policy", category: "Observability", label: "Log retention policy configured" },
  { key: "audit_log_api_export", category: "Observability", label: "Audit log accessible via API" },
  { key: "db_performance_monitoring", category: "Observability", label: "Database performance monitoring" },
  { key: "queue_depth_monitoring", category: "Observability", label: "Message queue depth monitoring" },
  { key: "cost_monitoring_signals", category: "Observability", label: "Cloud cost alerting" },
  { key: "error_budget_policy", category: "Observability", label: "SLO / error budget policy" },
  { key: "incident_runbooks", category: "Observability", label: "Incident runbooks / playbooks" },
  { key: "post_mortem_culture", category: "Observability", label: "Post-mortem / incident review culture" },
  { key: "deployment_frequency_tracking", category: "Observability", label: "Deployment frequency / DORA metrics tracked" },

  // ─── Infrastructure Extended (15) ───────────────────────────────────────────
  { key: "ipv6_dns_record", category: "Infrastructure", label: "IPv6 (AAAA) DNS record present" },
  { key: "multi_region_signals", category: "Infrastructure", label: "Multi-region deployment signals" },
  { key: "load_balancer_detected", category: "Infrastructure", label: "Load balancer / reverse proxy detected" },
  { key: "auto_scaling_configured", category: "Infrastructure", label: "Auto-scaling signals" },
  { key: "circuit_breaker_pattern", category: "Infrastructure", label: "Circuit breaker / retry pattern" },
  { key: "graceful_shutdown_configured", category: "Infrastructure", label: "Graceful shutdown / SIGTERM handling" },
  { key: "environment_separation", category: "Infrastructure", label: "Prod / staging / dev separation" },
  { key: "blue_green_canary_deploy", category: "Infrastructure", label: "Blue/green or canary deployment" },
  { key: "feature_flags_system", category: "Infrastructure", label: "Feature flag system" },
  { key: "secrets_manager_used", category: "Infrastructure", label: "Secrets manager (Vault / AWS Secrets Manager)" },
  { key: "database_read_replicas", category: "Infrastructure", label: "Database read replicas" },
  { key: "dns_ttl_healthy", category: "Infrastructure", label: "DNS TTL configured for stability" },
  { key: "backup_domain_configured", category: "Infrastructure", label: "www subdomain / backup domain configured" },
  { key: "object_storage_signals", category: "Infrastructure", label: "Object storage (S3 / GCS) for assets" },
  { key: "cdn_custom_caching_rules", category: "Infrastructure", label: "CDN caching configured" },

  // ─── SaaS Readiness Extended (15) ───────────────────────────────────────────
  { key: "saml_sso_available", category: "SaaS Readiness", label: "SAML / SSO enterprise tier" },
  { key: "scim_user_provisioning", category: "SaaS Readiness", label: "SCIM user provisioning" },
  { key: "custom_branding_available", category: "SaaS Readiness", label: "White-label / custom branding" },
  { key: "enterprise_pricing_tier", category: "SaaS Readiness", label: "Enterprise pricing tier" },
  { key: "keyboard_shortcuts_ui", category: "SaaS Readiness", label: "Keyboard shortcut hints" },
  { key: "dark_mode_supported", category: "SaaS Readiness", label: "Dark mode (prefers-color-scheme)" },
  { key: "bulk_operations_ui", category: "SaaS Readiness", label: "Bulk select / bulk operations" },
  { key: "data_export_csv_pdf", category: "SaaS Readiness", label: "Data export (CSV / PDF / Excel)" },
  { key: "data_import_capability", category: "SaaS Readiness", label: "Data import / migration" },
  { key: "community_forum_slack", category: "SaaS Readiness", label: "Community forum or Slack workspace" },
  { key: "app_marketplace_listed", category: "SaaS Readiness", label: "App marketplace listing" },
  { key: "public_roadmap", category: "SaaS Readiness", label: "Public product roadmap" },
  { key: "partner_reseller_program", category: "SaaS Readiness", label: "Partner / reseller programme" },
  { key: "g2_capterra_listed", category: "SaaS Readiness", label: "G2 or Capterra listing" },
  { key: "volume_discount_signals", category: "SaaS Readiness", label: "Volume discount signals" },

  // ─── Payments Extended (10) ─────────────────────────────────────────────────
  { key: "sepa_bank_transfer", category: "Payments", label: "SEPA / bank transfer option (EU)" },
  { key: "paypal_integration", category: "Payments", label: "PayPal integration" },
  { key: "three_ds_sca_compliant", category: "Payments", label: "3D Secure / PSD2 SCA compliant" },
  { key: "fraud_detection_tool", category: "Payments", label: "Fraud detection (Stripe Radar / Kount)" },
  { key: "pci_saq_evidence", category: "Payments", label: "PCI SAQ / scope reduction evidence" },
  { key: "regional_payment_methods", category: "Payments", label: "Regional payment methods (Klarna, iDEAL, etc.)" },
  { key: "chargeback_prevention", category: "Payments", label: "Chargeback prevention tools" },
  { key: "subscription_proration", category: "Payments", label: "Subscription plan proration" },
  { key: "invoicing_capability", category: "Payments", label: "Invoice generation for B2B" },
  { key: "tax_automation", category: "Payments", label: "Tax automation (Avalara / Stripe Tax)" },

  // ─── SEO Extended (15) ──────────────────────────────────────────────────────
  { key: "faqpage_schema", category: "SEO", label: "FAQPage JSON-LD schema" },
  { key: "product_schema", category: "SEO", label: "Product schema markup" },
  { key: "organization_schema", category: "SEO", label: "Organization schema markup" },
  { key: "article_schema", category: "SEO", label: "Article / BlogPosting schema" },
  { key: "review_schema", category: "SEO", label: "AggregateRating / Review schema" },
  { key: "breadcrumb_schema", category: "SEO", label: "BreadcrumbList schema" },
  { key: "local_business_schema", category: "SEO", label: "LocalBusiness schema" },
  { key: "sitemap_index", category: "SEO", label: "XML sitemap index" },
  { key: "image_sitemap_present", category: "SEO", label: "Image sitemap" },
  { key: "news_sitemap_present", category: "SEO", label: "Google News sitemap" },
  { key: "pagination_rel_links", category: "SEO", label: "Pagination rel=prev/next links" },
  { key: "canonical_self_referencing", category: "SEO", label: "Self-referencing canonical on key pages" },
  { key: "google_business_profile", category: "SEO", label: "Google Business Profile signals" },
  { key: "bing_webmaster_verified", category: "SEO", label: "Bing Webmaster Tools verification" },
  { key: "internal_link_depth", category: "SEO", label: "Key pages within 3 clicks of homepage" },

  // ─── Trust & Brand Extended (10) ────────────────────────────────────────────
  { key: "customer_logo_wall", category: "Trust & Brand", label: "Customer logo wall" },
  { key: "case_studies_present", category: "Trust & Brand", label: "Customer case studies" },
  { key: "awards_recognition", category: "Trust & Brand", label: "Industry awards / recognition badges" },
  { key: "security_whitepaper", category: "Trust & Brand", label: "Security whitepaper / documentation" },
  { key: "github_org_public", category: "Trust & Brand", label: "Public GitHub organisation" },
  { key: "cto_technical_bio", category: "Trust & Brand", label: "CTO / technical lead bio" },
  { key: "investor_backing_listed", category: "Trust & Brand", label: "VC / accelerator backing mentioned" },
  { key: "conference_speaking", category: "Trust & Brand", label: "Conference / speaking appearances" },
  { key: "uptime_history_public", category: "Trust & Brand", label: "Public uptime / reliability history" },
  { key: "named_customer_quotes", category: "Trust & Brand", label: "Named customer quotes (not anonymous)" },

  // ─── Missing Pages Extended (10) ────────────────────────────────────────────
  { key: "legal_hub_page", category: "Missing Pages", label: "/legal hub page" },
  { key: "security_dedicated_page", category: "Missing Pages", label: "/security dedicated page" },
  { key: "api_docs_page", category: "Missing Pages", label: "API documentation page" },
  { key: "system_requirements_page", category: "Missing Pages", label: "System requirements / compatibility" },
  { key: "roadmap_public_page", category: "Missing Pages", label: "Public /roadmap page" },
  { key: "pricing_comparison_table", category: "Missing Pages", label: "Pricing comparison / feature matrix" },
  { key: "migration_import_guide", category: "Missing Pages", label: "Migration / import guide" },
  { key: "partners_ecosystem_page", category: "Missing Pages", label: "/partners or /ecosystem page" },
  { key: "affiliate_programme_page", category: "Missing Pages", label: "/affiliate programme page" },
  { key: "release_notes_page", category: "Missing Pages", label: "/release-notes page" },

  // ─── Global Distribution Extended (10) ─────────────────────────────────────
  { key: "uk_pecr_cookie_law", category: "Global Distribution", label: "UK PECR cookie law compliance" },
  { key: "cnil_france_compliant", category: "Global Distribution", label: "CNIL compliance signals (France)" },
  { key: "eu_art27_representative", category: "Global Distribution", label: "EU Art. 27 representative named" },
  { key: "consumer_law_aus", category: "Global Distribution", label: "Australian Consumer Law signals" },
  { key: "local_phone_numbers", category: "Global Distribution", label: "Local phone numbers for target markets" },
  { key: "vat_moss_oss_signals", category: "Global Distribution", label: "EU VAT OSS (One Stop Shop) compliance" },
  { key: "gdpr_dpa_list_public", category: "Global Distribution", label: "Sub-processors list publicly available" },
  { key: "iso_27701_signals", category: "Global Distribution", label: "ISO 27701 (privacy management) signals" },
  { key: "transfer_impact_assessment", category: "Global Distribution", label: "SCCs / Data Transfer Impact Assessment" },
  { key: "local_legal_notice", category: "Global Distribution", label: "Mentions Légales (France / Belgium)" },

  // ─── Code Quality Extended (10) ─────────────────────────────────────────────
  { key: "github_code_scanning", category: "Code Quality", label: "Code scanning (CodeQL / Snyk)" },
  { key: "github_branch_protection", category: "Code Quality", label: "Branch protection rules" },
  { key: "github_required_reviews", category: "Code Quality", label: "Required PR approvals" },
  { key: "github_codeowners", category: "Code Quality", label: "CODEOWNERS file" },
  { key: "github_secret_scanning", category: "Code Quality", label: "GitHub secret scanning" },
  { key: "github_pr_template", category: "Code Quality", label: "PR description template" },
  { key: "github_issue_templates", category: "Code Quality", label: "Issue templates" },
  { key: "commit_signing_enabled", category: "Code Quality", label: "Signed commits (GPG / Sigstore)" },
  { key: "release_automation", category: "Code Quality", label: "Release automation (semantic-release)" },
  { key: "stale_bot_configured", category: "Code Quality", label: "Stale issue / PR management" },

  // ─── Mobile & Accessibility Extended (10) ───────────────────────────────────
  { key: "web_push_notifications", category: "Mobile & Accessibility", label: "Web Push Notifications support" },
  { key: "push_permission_polite", category: "Mobile & Accessibility", label: "Polite push permission prompt" },
  { key: "offline_mode_capable", category: "Mobile & Accessibility", label: "Service worker offline support" },
  { key: "reduced_motion_css", category: "Mobile & Accessibility", label: "prefers-reduced-motion CSS" },
  { key: "high_contrast_css", category: "Mobile & Accessibility", label: "prefers-contrast CSS media query" },
  { key: "biometric_auth_signals", category: "Mobile & Accessibility", label: "WebAuthn biometric auth signals" },
  { key: "screen_reader_tested_signal", category: "Mobile & Accessibility", label: "Accessibility testing evidence" },
  { key: "gesture_navigation", category: "Mobile & Accessibility", label: "Swipe / gesture navigation" },
  { key: "apple_app_clip_support", category: "Mobile & Accessibility", label: "App Clips support (iOS)" },
  { key: "android_instant_app", category: "Mobile & Accessibility", label: "Android Instant Apps" },

  // ─── Business Operations (15) ───────────────────────────────────────────────
  { key: "physical_address_footer", category: "Business Operations", label: "Physical address in footer" },
  { key: "business_hours_displayed", category: "Business Operations", label: "Business hours displayed" },
  { key: "vat_number_displayed", category: "Business Operations", label: "VAT number in footer (EU B2B)" },
  { key: "uk_companies_house_number", category: "Business Operations", label: "UK Companies House registration number" },
  { key: "eu_director_info", category: "Business Operations", label: "Director / responsible person named" },
  { key: "support_sla_documented", category: "Business Operations", label: "Support SLA / response times documented" },
  { key: "esignature_support", category: "Business Operations", label: "eSignature / contract workflow" },
  { key: "invoice_generation_b2b", category: "Business Operations", label: "Invoice / tax invoice generation" },
  { key: "insurance_mention", category: "Business Operations", label: "Professional indemnity insurance" },
  { key: "gdpr_ropa_maintained", category: "Business Operations", label: "ROPA (Records of Processing Activities)" },
  { key: "data_retention_schedule", category: "Business Operations", label: "Data retention schedule published" },
  { key: "supplier_due_diligence", category: "Business Operations", label: "Vendor / sub-processor due diligence" },
  { key: "modern_slavery_statement", category: "Business Operations", label: "Modern Slavery Act statement" },
  { key: "bribery_act_policy", category: "Business Operations", label: "Anti-bribery policy (UK Bribery Act)" },
  { key: "whistleblower_policy", category: "Business Operations", label: "Whistleblower / speak-up policy" },

  // ─── API Quality (15) ───────────────────────────────────────────────────────
  { key: "api_versioning_present", category: "API Quality", label: "API versioning (/v1/, /v2/ pattern)" },
  { key: "api_rate_limit_documented", category: "API Quality", label: "Rate limits documented" },
  { key: "api_auth_method_documented", category: "API Quality", label: "Auth method documented" },
  { key: "api_error_rfc7807", category: "API Quality", label: "RFC 7807 Problem Details error format" },
  { key: "api_pagination_documented", category: "API Quality", label: "Pagination documented" },
  { key: "api_filtering_sorting", category: "API Quality", label: "Filtering / sorting query params" },
  { key: "api_webhook_docs", category: "API Quality", label: "Webhook documentation" },
  { key: "api_sandbox_test_mode", category: "API Quality", label: "Sandbox / test mode" },
  { key: "api_sdk_packages", category: "API Quality", label: "SDK packages published" },
  { key: "api_versioned_changelog", category: "API Quality", label: "Versioned API changelog" },
  { key: "api_health_status_endpoint", category: "API Quality", label: "/api/health or /status endpoint" },
  { key: "api_deprecation_policy", category: "API Quality", label: "Deprecation policy / sunset headers" },
  { key: "api_sla_documented", category: "API Quality", label: "API SLA / uptime guarantee" },
  { key: "graphql_depth_limiting", category: "API Quality", label: "GraphQL depth / complexity limiting" },
  { key: "openapi_spec_served", category: "API Quality", label: "OpenAPI 3.x spec at /openapi.json" },
];

/** All unique categories in display order */
export const CHECK_CATEGORIES: string[] = [
  "Store Listing",
  "SEO",
  "Infrastructure",
  "Security",
  "Performance",
  "Payments",
  "Authentication",
  "Observability",
  "Legal & Compliance",
  "Missing Pages",
  "SaaS Readiness",
  "Mobile & Accessibility",
  "Accessibility",
  "Code Quality",
  "App Store & Mobile",
  "Global Distribution",
  "Trust & Brand",
  "Roles & Permissions",
  "Email Deliverability",
  "Business Operations",
  "API Quality",
];

export function getCheckDefinition(key: string): CheckDefinition | undefined {
  return CHECKS_REGISTRY.find((c) => c.key === key);
}

export function getChecksByCategory(category: string): CheckDefinition[] {
  return CHECKS_REGISTRY.filter((c) => c.category === category);
}