/**
 * Static registry of all 208 Pulse checks.
 * Auto-extracted from pulse-scan.ts — do not edit manually.
 * Per-workspace overrides (enabled, label, severity) live in PulseCheckConfig.
 */

export interface CheckDefinition {
  key: string;
  category: string;
  label: string;
}

export const CHECKS_REGISTRY: CheckDefinition[] = [
  { key: "store_app_title", category: "Store Listing", label: "App name / title" },
  { key: "store_description", category: "Store Listing", label: "App description" },
  { key: "store_screenshots", category: "Store Listing", label: "Screenshots / preview assets" },
  { key: "store_ratings", category: "Store Listing", label: "Ratings & reviews" },
  { key: "store_privacy_policy", category: "Store Listing", label: "Privacy policy linked" },
  { key: "store_age_rating", category: "Store Listing", label: "Age / content rating" },
  { key: "store_iap_disclosed", category: "Store Listing", label: "In-app purchases disclosed" },
  { key: "appstore_subtitle", category: "Store Listing", label: "App subtitle (keyword field)" },
  { key: "appstore_privacy_label", category: "Store Listing", label: "Apple privacy nutrition label" },
  { key: "playstore_data_safety", category: "Store Listing", label: "Data Safety section" },
  { key: "playstore_content_rating", category: "Store Listing", label: "IARC content rating" },
  { key: "ssl_valid", category: "SEO", label: "HTTPS / SSL certificate" },
  { key: "http_redirect", category: "Infrastructure", label: "HTTP → HTTPS redirect" },
  { key: "response_time", category: "Infrastructure", label: "Response time" },
  { key: "status_200", category: "Infrastructure", label: "Returns 200 OK" },
  { key: "custom_domain", category: "Infrastructure", label: "Custom domain" },
  { key: "cdn_detected", category: "Infrastructure", label: "CDN present" },
  { key: "meta_title", category: "SEO", label: "<title> tag" },
  { key: "meta_description", category: "SEO", label: "Meta description" },
  { key: "og_tags", category: "SEO", label: "Open Graph tags" },
  { key: "canonical_url", category: "SEO", label: "Canonical URL" },
  { key: "h1_present", category: "SEO", label: "H1 heading" },
  { key: "has_robots_txt", category: "SEO", label: "robots.txt" },
  { key: "has_sitemap", category: "SEO", label: "sitemap.xml" },
  { key: "csp_header", category: "Security", label: "Content-Security-Policy" },
  { key: "hsts_header", category: "Security", label: "HSTS header" },
  { key: "x_frame_options", category: "Security", label: "Clickjacking protection" },
  { key: "no_exposed_env", category: "Security", label: ".env not public" },
  { key: "no_exposed_git", category: "Security", label: ".git directory not public" },
  { key: "compression", category: "Performance", label: "Gzip/Brotli compression" },
  { key: "caching_headers", category: "Performance", label: "Cache-Control headers" },
  { key: "stripe_signals", category: "Payments", label: "Stripe integration" },
  { key: "pricing_page", category: "Payments", label: "Pricing/billing UI" },
  { key: "auth_ui_signals", category: "Authentication", label: "Login/signup UI" },
  { key: "oauth_signals", category: "Authentication", label: "Auth provider" },
  { key: "error_monitoring", category: "Observability", label: "Error monitoring" },
  { key: "analytics_present", category: "Observability", label: "Analytics" },
  { key: "health_endpoint", category: "Observability", label: "/health endpoint" },
  { key: "privacy_policy", category: "Legal & Compliance", label: "Privacy Policy" },
  { key: "terms_of_service", category: "Legal & Compliance", label: "Terms of Service" },
  { key: "cookie_consent", category: "Legal & Compliance", label: "Cookie consent / GDPR" },
  { key: "refund_policy", category: "Legal & Compliance", label: "Refund / Cancellation policy" },
  { key: "about_page", category: "Missing Pages", label: "About / Team page" },
  { key: "contact_page", category: "Missing Pages", label: "Contact page" },
  { key: "faq_page", category: "Missing Pages", label: "FAQ / Help page" },
  { key: "status_page", category: "Missing Pages", label: "Status / uptime page" },
  { key: "changelog", category: "Missing Pages", label: "Changelog / What" },
  { key: "billing_portal", category: "SaaS Readiness", label: "Billing / subscription management" },
  { key: "account_settings", category: "SaaS Readiness", label: "Account settings" },
  { key: "password_reset", category: "SaaS Readiness", label: "Password reset" },
  { key: "support_channel", category: "SaaS Readiness", label: "Support channel" },
  { key: "social_proof", category: "SaaS Readiness", label: "Social proof / testimonials" },
  { key: "onboarding_flow", category: "SaaS Readiness", label: "Onboarding flow" },
  { key: "viewport_meta", category: "Mobile & Accessibility", label: "Viewport meta tag" },
  { key: "html_lang", category: "Mobile & Accessibility", label: "HTML language attribute" },
  { key: "aria_attributes", category: "Mobile & Accessibility", label: "ARIA accessibility attributes" },
  { key: "responsive_images", category: "Mobile & Accessibility", label: "Responsive / optimised images" },
  { key: "og_image", category: "SEO", label: "og:image (social preview)" },
  { key: "twitter_card", category: "SEO", label: "Twitter / X Card" },
  { key: "x_content_type_options", category: "Security", label: "X-Content-Type-Options" },
  { key: "permissions_policy", category: "Security", label: "Permissions-Policy" },
  { key: "referrer_policy", category: "Security", label: "Referrer-Policy" },
  { key: "email_provider", category: "SaaS Readiness", label: "Transactional email provider" },
  { key: "ai_platform_origin", category: "Code Quality", label: "AI platform watermark" },
  { key: "favicon", category: "Mobile & Accessibility", label: "Favicon / app icon" },
  { key: "pwa_manifest", category: "Mobile & Accessibility", label: "Web App Manifest (PWA)" },
  { key: "stripe_webhook", category: "Payments", label: "Stripe webhook endpoint" },
  { key: "apple_touch_icon", category: "App Store & Mobile", label: "Apple touch icon" },
  { key: "apple_app_store", category: "App Store & Mobile", label: "Apple App Store presence" },
  { key: "google_play_store", category: "App Store & Mobile", label: "Google Play Store presence" },
  { key: "universal_links", category: "App Store & Mobile", label: "Universal Links (iOS deep linking)" },
  { key: "android_asset_links", category: "App Store & Mobile", label: "Android App Links (deep linking)" },
  { key: "wallet_payments", category: "App Store & Mobile", label: "Apple Pay / Google Pay / Amazon Pay" },
  { key: "hreflang_tags", category: "Global Distribution", label: "hreflang tags (multi-region SEO)" },
  { key: "charset_utf8", category: "Global Distribution", label: "UTF-8 character encoding" },
  { key: "ccpa_compliance", category: "Global Distribution", label: "CCPA (California privacy rights)" },
  { key: "multi_currency", category: "Global Distribution", label: "Multi-currency pricing" },
  { key: "rtl_support", category: "Global Distribution", label: "RTL language support" },
  { key: "language_switcher", category: "Global Distribution", label: "Language / region switcher" },
  { key: "international_payments", category: "Global Distribution", label: "International payment methods" },
  { key: "eu_vat", category: "Global Distribution", label: "EU VAT / tax handling" },
  { key: "structured_data", category: "SEO", label: "JSON-LD structured data" },
  { key: "preload_hints", category: "SEO", label: "Resource preload hints" },
  { key: "search_engine_verified", category: "SEO", label: "Search engine verification" },
  { key: "meta_robots", category: "SEO", label: "Robots meta tag" },
  { key: "og_site_name", category: "SEO", label: "og:site_name (brand in shares)" },
  { key: "subresource_integrity", category: "Security", label: "Subresource Integrity (SRI)" },
  { key: "secure_cookie_attributes", category: "Security", label: "Secure cookie attributes" },
  { key: "cors_policy", category: "Security", label: "CORS policy" },
  { key: "security_txt", category: "Security", label: "security.txt (responsible disclosure)" },
  { key: "server_header_leakage", category: "Security", label: "Server version not exposed" },
  { key: "no_mixed_content", category: "Security", label: "No mixed HTTP/HTTPS content" },
  { key: "preconnect_hints", category: "Performance", label: "Preconnect / DNS prefetch hints" },
  { key: "native_lazy_loading", category: "Performance", label: "Native image lazy loading" },
  { key: "font_display_swap", category: "Performance", label: "Font display optimisation" },
  { key: "vary_header", category: "Performance", label: "Vary header (content negotiation)" },
  { key: "server_timing", category: "Performance", label: "Server-Timing header" },
  { key: "mfa_signals", category: "Authentication", label: "Multi-factor authentication (MFA)" },
  { key: "email_verification_flow", category: "Authentication", label: "Email verification flow" },
  { key: "magic_link_auth", category: "Authentication", label: "Magic link / passwordless login" },
  { key: "enterprise_sso", category: "Authentication", label: "Enterprise SSO / SAML" },
  { key: "data_deletion_right", category: "Legal & Compliance", label: "Data deletion / right to erasure (GDPR Art. 17)" },
  { key: "accessibility_statement", category: "Legal & Compliance", label: "Accessibility statement" },
  { key: "coppa_signals", category: "Legal & Compliance", label: "COPPA / children" },
  { key: "dpa_available", category: "Legal & Compliance", label: "Data Processing Agreement (GDPR Art. 28)" },
  { key: "icp_license", category: "Legal & Compliance", label: "China ICP license (for CN market)" },
  { key: "privacy_last_updated", category: "Legal & Compliance", label: "Privacy policy maintenance date" },
  { key: "cookie_policy_page", category: "Legal & Compliance", label: "Dedicated cookie policy page" },
  { key: "gdpr_dpo_contact", category: "Legal & Compliance", label: "GDPR privacy contact (DPO)" },
  { key: "blog_resources", category: "Missing Pages", label: "Blog / resources hub" },
  { key: "careers_page", category: "Missing Pages", label: "Careers / jobs page" },
  { key: "press_media", category: "Missing Pages", label: "Press / media page" },
  { key: "documentation", category: "Missing Pages", label: "Documentation / developer docs" },
  { key: "integrations_page", category: "Missing Pages", label: "Integrations / partners page" },
  { key: "custom_404_page", category: "Missing Pages", label: "Custom 404 error page" },
  { key: "demo_booking", category: "SaaS Readiness", label: "Demo booking / discovery call" },
  { key: "free_trial_cta", category: "SaaS Readiness", label: "Free trial / free plan CTA" },
  { key: "api_availability", category: "SaaS Readiness", label: "Public API / developer access" },
  { key: "affiliate_program", category: "SaaS Readiness", label: "Affiliate / referral program" },
  { key: "security_trust_page", category: "SaaS Readiness", label: "Security / trust page" },
  { key: "in_app_notifications", category: "SaaS Readiness", label: "In-app notification system" },
  { key: "uptime_monitoring", category: "Observability", label: "External uptime monitoring" },
  { key: "log_aggregation", category: "Observability", label: "Centralised log aggregation" },
  { key: "apm_signals", category: "Observability", label: "Application Performance Monitoring (APM)" },
  { key: "real_user_monitoring", category: "Observability", label: "Real User Monitoring (RUM)" },
  { key: "payment_trust_badges", category: "Payments", label: "Payment trust badges" },
  { key: "bnpl_options", category: "Payments", label: "Buy Now Pay Later (BNPL)" },
  { key: "crypto_payments", category: "Payments", label: "Cryptocurrency payment option" },
  { key: "smart_app_banner_meta", category: "App Store & Mobile", label: "Smart App Banner (iOS web-to-app)" },
  { key: "amazon_app_store", category: "App Store & Mobile", label: "Amazon Appstore / Fire TV presence" },
  { key: "app_listing_screenshots", category: "App Store & Mobile", label: "App screenshots / listing assets" },
  { key: "app_icon_sizes", category: "App Store & Mobile", label: "App icon multiple resolutions" },
  { key: "country_region_selector", category: "Global Distribution", label: "Country / region selector" },
  { key: "compliance_certifications", category: "Global Distribution", label: "Compliance certifications (SOC 2, ISO 27001)" },
  { key: "eu_data_residency", category: "Global Distribution", label: "EU data residency signals" },
  { key: "company_registration_info", category: "Global Distribution", label: "Company registration info" },
  { key: "timezone_locale_support", category: "Global Distribution", label: "Timezone / locale-aware content" },
  { key: "social_media_links", category: "Trust & Brand", label: "Social media presence" },
  { key: "third_party_reviews", category: "Trust & Brand", label: "Third-party review platform" },
  { key: "press_coverage", category: "Trust & Brand", label: "Press / media coverage section" },
  { key: "team_presence", category: "Trust & Brand", label: "Founder / team bio with photo" },
  { key: "product_hunt_badge", category: "Trust & Brand", label: "Product Hunt launch presence" },
  { key: "media_kit", category: "Trust & Brand", label: "Media kit / brand assets" },
  { key: "no_placeholder_text", category: "Code Quality", label: "No placeholder / lorem ipsum content" },
  { key: "no_hash_routing", category: "Code Quality", label: "Clean URL routing (no hash routes)" },
  { key: "spf_record", category: "Security", label: "SPF record (email spoofing protection)" },
  { key: "dmarc_record", category: "Security", label: "DMARC record (email impersonation protection)" },
  { key: "mx_record", category: "Infrastructure", label: "MX records (email infrastructure)" },
  { key: "no_exposed_admin", category: "Security", label: "Admin panel not publicly accessible" },
  { key: "no_exposed_phpinfo", category: "Security", label: "PHP info page not exposed" },
  { key: "no_exposed_git_config", category: "Security", label: "Git config not publicly accessible" },
  { key: "no_debug_endpoints", category: "Security", label: "Debug/monitoring endpoints not public" },
  { key: "no_exposed_backup", category: "Security", label: "Database backup files not exposed" },
  { key: "http2_enabled", category: "Performance", label: "HTTP/2 protocol" },
  { key: "no_x_powered_by", category: "Security", label: "X-Powered-By header absent" },
  { key: "no_server_version", category: "Security", label: "Server version not disclosed" },
  { key: "cors_not_wildcard", category: "Security", label: "CORS not open to all origins" },
  { key: "has_word_count", category: "SEO", label: "Sufficient page content" },
  { key: "has_heading_hierarchy", category: "SEO", label: "Heading hierarchy (H1→H2→H3)" },
  { key: "image_alt_coverage", category: "Accessibility", label: "Image alt text coverage" },
  { key: "internal_links_present", category: "SEO", label: "Internal linking" },
  { key: "no_broken_inline_scripts", category: "Code Quality", label: "No console.log in production HTML" },
  { key: "service_worker_present", category: "Performance", label: "Service worker (offline/caching)" },
  { key: "web_app_manifest_linked", category: "Performance", label: "Web app manifest linked" },
  { key: "theme_color_defined", category: "Performance", label: "Theme colour meta tag" },
  { key: "third_party_script_count", category: "Performance", label: "Third-party script load" },
  { key: "no_jquery_old", category: "Code Quality", label: "No outdated jQuery" },
  { key: "annual_billing_signal", category: "SaaS Readiness", label: "Annual billing option" },
  { key: "money_back_signal", category: "SaaS Readiness", label: "Money-back guarantee signal" },
  { key: "live_chat_signal", category: "SaaS Readiness", label: "Live chat / support widget" },
  { key: "demo_booking_signal", category: "SaaS Readiness", label: "Demo booking or discovery call" },
  { key: "social_proof_numbers", category: "Trust & Brand", label: "Quantified social proof" },
  { key: "video_embed_present", category: "SaaS Readiness", label: "Product demo video" },
  { key: "api_docs_signal", category: "SaaS Readiness", label: "API documentation" },
  { key: "openapi_endpoint", category: "SaaS Readiness", label: "OpenAPI spec endpoint" },
  { key: "graphql_signal", category: "SaaS Readiness", label: "GraphQL API" },
  { key: "search_functionality", category: "SaaS Readiness", label: "Search functionality" },
  { key: "cookie_consent_granular", category: "Legal & Compliance", label: "Granular cookie consent (accept/reject all)" },
  { key: "newsletter_signup", category: "SaaS Readiness", label: "Newsletter / email list capture" },
  { key: "repo_parse", category: "Code Quality", label: "Repository URL" },
  { key: "has_readme", category: "Code Quality", label: "README.md" },
  { key: "has_tests", category: "Code Quality", label: "Test suite" },
  { key: "has_linter", category: "Code Quality", label: "Linter config" },
  { key: "has_typescript", category: "Code Quality", label: "TypeScript" },
  { key: "has_env_example", category: "Code Quality", label: ".env.example" },
  { key: "ci_cd_present", category: "Code Quality", label: "CI/CD pipeline" },
  { key: "has_license", category: "Code Quality", label: "License file" },
  { key: "has_manifest", category: "Infrastructure", label: "Dependency manifest" },
  { key: "dockerfile_present", category: "Infrastructure", label: "Dockerfile / Docker Compose" },
  { key: "has_contributing", category: "Code Quality", label: "CONTRIBUTING.md" },
  { key: "has_code_of_conduct", category: "Code Quality", label: "Code of Conduct" },
  { key: "has_security_md", category: "Code Quality", label: "SECURITY.md (vulnerability disclosure)" },
  { key: "has_dependabot", category: "Code Quality", label: "Dependabot / automated dependency updates" },
  { key: "has_changelog_file", category: "Code Quality", label: "CHANGELOG.md" },
  { key: "has_openapi_spec", category: "Code Quality", label: "OpenAPI / Swagger spec" },
  { key: "has_editorconfig", category: "Code Quality", label: ".editorconfig (consistent formatting)" },
  { key: "has_gitignore", category: "Code Quality", label: ".gitignore" },
  { key: "has_e2e_tests", category: "Code Quality", label: "E2E test suite (Playwright / Cypress)" },
  { key: "has_unit_test_config", category: "Code Quality", label: "Unit test framework (Jest / Vitest)" },
  { key: "has_git_hooks", category: "Code Quality", label: "Git hooks (Husky / lefthook)" },
  { key: "has_orm_config", category: "Infrastructure", label: "ORM / database configuration" },
  { key: "has_migrations", category: "Infrastructure", label: "Database migrations" },
  { key: "has_renovate", category: "Code Quality", label: "Renovate / automated dependency updates" },
  { key: "has_devcontainer", category: "Infrastructure", label: "Dev container (.devcontainer)" },
  { key: "has_infra_code", category: "Infrastructure", label: "Infrastructure as Code (Terraform / Helm / K8s)" },
  { key: "has_makefile", category: "Code Quality", label: "Makefile / task runner" },
  { key: "is_monorepo", category: "Code Quality", label: "Monorepo tooling (Turbo / Nx / pnpm workspaces)" },
  { key: "has_coverage_config", category: "Code Quality", label: "Code coverage reporting" },
];

/** All unique categories in display order */
export const CHECK_CATEGORIES: string[] = [
  "Store Listing",
  "SEO",
  "Infrastructure",
  "Security",
  "Performance",
  "Payments",
  "Authentication",
  "Observability",
  "Legal & Compliance",
  "Missing Pages",
  "SaaS Readiness",
  "Mobile & Accessibility",
  "Code Quality",
  "App Store & Mobile",
  "Global Distribution",
  "Trust & Brand",
  "Accessibility"
];

export function getCheckDefinition(key: string): CheckDefinition | undefined {
  return CHECKS_REGISTRY.find((c) => c.key === key);
}

export function getChecksByCategory(category: string): CheckDefinition[] {
  return CHECKS_REGISTRY.filter((c) => c.category === category);
}