import { CATEGORIES, ORDERED_CATEGORIES, type CheckCategory } from "./pulse-checks/categories";

/**
 * Static registry of every Pulse check (key + category + label). This is the
 * catalogue the Settings → Checks panel and per-workspace overrides
 * (PulseCheckConfig: enabled, label, severity) are built from.
 *
 * Categories come from CATEGORIES (src/server/pulse-checks/categories.ts) — the
 * single source of truth — never a raw string. categories.reconcile.test.ts fails
 * CI if a check module emits a checkKey that isn't listed here.
 */

export interface CheckDefinition {
  key: string;
  category: CheckCategory;
  label: string;
}

export const CHECKS_REGISTRY: CheckDefinition[] = [
  { key: "store_app_title", category: CATEGORIES.STORE_LISTING, label: "App name / title" },
  { key: "store_description", category: CATEGORIES.STORE_LISTING, label: "App description" },
  { key: "store_screenshots", category: CATEGORIES.STORE_LISTING, label: "Screenshots / preview assets" },
  { key: "store_ratings", category: CATEGORIES.STORE_LISTING, label: "Ratings & reviews" },
  { key: "store_privacy_policy", category: CATEGORIES.STORE_LISTING, label: "Privacy policy linked" },
  { key: "store_age_rating", category: CATEGORIES.STORE_LISTING, label: "Age / content rating" },
  { key: "store_iap_disclosed", category: CATEGORIES.STORE_LISTING, label: "In-app purchases disclosed" },
  { key: "appstore_subtitle", category: CATEGORIES.STORE_LISTING, label: "App subtitle (keyword field)" },
  { key: "appstore_privacy_label", category: CATEGORIES.STORE_LISTING, label: "Apple privacy nutrition label" },
  { key: "playstore_data_safety", category: CATEGORIES.STORE_LISTING, label: "Data Safety section" },
  { key: "playstore_content_rating", category: CATEGORIES.STORE_LISTING, label: "IARC content rating" },
  { key: "ssl_valid", category: CATEGORIES.SEO, label: "HTTPS / SSL certificate" },
  { key: "http_redirect", category: CATEGORIES.INFRASTRUCTURE, label: "HTTP → HTTPS redirect" },
  { key: "response_time", category: CATEGORIES.INFRASTRUCTURE, label: "Response time" },
  { key: "status_200", category: CATEGORIES.INFRASTRUCTURE, label: "Returns 200 OK" },
  { key: "custom_domain", category: CATEGORIES.INFRASTRUCTURE, label: "Custom domain" },
  { key: "cdn_detected", category: CATEGORIES.INFRASTRUCTURE, label: "CDN present" },
  { key: "meta_title", category: CATEGORIES.SEO, label: "<title> tag" },
  { key: "meta_description", category: CATEGORIES.SEO, label: "Meta description" },
  { key: "og_tags", category: CATEGORIES.SEO, label: "Open Graph tags" },
  { key: "canonical_url", category: CATEGORIES.SEO, label: "Canonical URL" },
  { key: "h1_present", category: CATEGORIES.SEO, label: "H1 heading" },
  { key: "has_robots_txt", category: CATEGORIES.SEO, label: "robots.txt" },
  { key: "has_sitemap", category: CATEGORIES.SEO, label: "sitemap.xml" },
  { key: "csp_header", category: CATEGORIES.SECURITY, label: "Content-Security-Policy" },
  { key: "hsts_header", category: CATEGORIES.SECURITY, label: "HSTS header" },
  { key: "x_frame_options", category: CATEGORIES.SECURITY, label: "Clickjacking protection" },
  { key: "no_exposed_env", category: CATEGORIES.SECURITY, label: ".env not public" },
  { key: "no_exposed_git", category: CATEGORIES.SECURITY, label: ".git directory not public" },
  { key: "compression", category: CATEGORIES.PERFORMANCE, label: "Gzip/Brotli compression" },
  { key: "caching_headers", category: CATEGORIES.PERFORMANCE, label: "Cache-Control headers" },
  { key: "stripe_signals", category: CATEGORIES.PAYMENTS, label: "Stripe integration" },
  { key: "pricing_page", category: CATEGORIES.PAYMENTS, label: "Pricing/billing UI" },
  { key: "auth_ui_signals", category: CATEGORIES.AUTHENTICATION, label: "Login/signup UI" },
  { key: "oauth_signals", category: CATEGORIES.AUTHENTICATION, label: "Auth provider" },
  { key: "error_monitoring", category: CATEGORIES.OBSERVABILITY, label: "Error monitoring" },
  { key: "analytics_present", category: CATEGORIES.OBSERVABILITY, label: "Analytics" },
  { key: "health_endpoint", category: CATEGORIES.OBSERVABILITY, label: "/health endpoint" },
  { key: "privacy_policy", category: CATEGORIES.LEGAL, label: "Privacy Policy" },
  { key: "terms_of_service", category: CATEGORIES.LEGAL, label: "Terms of Service" },
  { key: "cookie_consent", category: CATEGORIES.LEGAL, label: "Cookie consent / GDPR" },
  { key: "refund_policy", category: CATEGORIES.LEGAL, label: "Refund / Cancellation policy" },
  { key: "about_page", category: CATEGORIES.MISSING_PAGES, label: "About / Team page" },
  { key: "contact_page", category: CATEGORIES.MISSING_PAGES, label: "Contact page" },
  { key: "faq_page", category: CATEGORIES.MISSING_PAGES, label: "FAQ / Help page" },
  { key: "status_page", category: CATEGORIES.MISSING_PAGES, label: "Status / uptime page" },
  { key: "changelog", category: CATEGORIES.MISSING_PAGES, label: "Changelog / What" },
  { key: "billing_portal", category: CATEGORIES.SAAS, label: "Billing / subscription management" },
  { key: "account_settings", category: CATEGORIES.SAAS, label: "Account settings" },
  { key: "password_reset", category: CATEGORIES.SAAS, label: "Password reset" },
  { key: "support_channel", category: CATEGORIES.SAAS, label: "Support channel" },
  { key: "social_proof", category: CATEGORIES.SAAS, label: "Social proof / testimonials" },
  { key: "onboarding_flow", category: CATEGORIES.SAAS, label: "Onboarding flow" },
  { key: "viewport_meta", category: CATEGORIES.MOBILE, label: "Viewport meta tag" },
  { key: "html_lang", category: CATEGORIES.MOBILE, label: "HTML language attribute" },
  { key: "aria_attributes", category: CATEGORIES.MOBILE, label: "ARIA accessibility attributes" },
  { key: "responsive_images", category: CATEGORIES.MOBILE, label: "Responsive / optimised images" },
  { key: "og_image", category: CATEGORIES.SEO, label: "og:image (social preview)" },
  { key: "twitter_card", category: CATEGORIES.SEO, label: "Twitter / X Card" },
  { key: "x_content_type_options", category: CATEGORIES.SECURITY, label: "X-Content-Type-Options" },
  { key: "permissions_policy", category: CATEGORIES.SECURITY, label: "Permissions-Policy" },
  { key: "referrer_policy", category: CATEGORIES.SECURITY, label: "Referrer-Policy" },
  { key: "email_provider", category: CATEGORIES.SAAS, label: "Transactional email provider" },
  { key: "ai_platform_origin", category: CATEGORIES.CODE_QUALITY, label: "AI platform watermark" },
  { key: "favicon", category: CATEGORIES.MOBILE, label: "Favicon / app icon" },
  { key: "pwa_manifest", category: CATEGORIES.MOBILE, label: "Web App Manifest (PWA)" },
  { key: "stripe_webhook", category: CATEGORIES.PAYMENTS, label: "Stripe webhook endpoint" },
  { key: "apple_touch_icon", category: CATEGORIES.APP_STORE, label: "Apple touch icon" },
  { key: "apple_app_store", category: CATEGORIES.APP_STORE, label: "Apple App Store presence" },
  { key: "google_play_store", category: CATEGORIES.APP_STORE, label: "Google Play Store presence" },
  { key: "universal_links", category: CATEGORIES.APP_STORE, label: "Universal Links (iOS deep linking)" },
  { key: "android_asset_links", category: CATEGORIES.APP_STORE, label: "Android App Links (deep linking)" },
  { key: "wallet_payments", category: CATEGORIES.APP_STORE, label: "Apple Pay / Google Pay / Amazon Pay" },
  { key: "hreflang_tags", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "hreflang tags (multi-region SEO)" },
  { key: "charset_utf8", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "UTF-8 character encoding" },
  { key: "ccpa_compliance", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "CCPA (California privacy rights)" },
  { key: "multi_currency", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "Multi-currency pricing" },
  { key: "rtl_support", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "RTL language support" },
  { key: "language_switcher", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "Language / region switcher" },
  { key: "international_payments", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "International payment methods" },
  { key: "eu_vat", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "EU VAT / tax handling" },
  { key: "structured_data", category: CATEGORIES.SEO, label: "JSON-LD structured data" },
  { key: "preload_hints", category: CATEGORIES.SEO, label: "Resource preload hints" },
  { key: "search_engine_verified", category: CATEGORIES.SEO, label: "Search engine verification" },
  { key: "meta_robots", category: CATEGORIES.SEO, label: "Robots meta tag" },
  { key: "og_site_name", category: CATEGORIES.SEO, label: "og:site_name (brand in shares)" },
  { key: "subresource_integrity", category: CATEGORIES.SECURITY, label: "Subresource Integrity (SRI)" },
  { key: "secure_cookie_attributes", category: CATEGORIES.SECURITY, label: "Secure cookie attributes" },
  { key: "cors_policy", category: CATEGORIES.SECURITY, label: "CORS policy" },
  { key: "security_txt", category: CATEGORIES.SECURITY, label: "security.txt (responsible disclosure)" },
  { key: "server_header_leakage", category: CATEGORIES.SECURITY, label: "Server version not exposed" },
  { key: "no_mixed_content", category: CATEGORIES.SECURITY, label: "No mixed HTTP/HTTPS content" },
  { key: "preconnect_hints", category: CATEGORIES.PERFORMANCE, label: "Preconnect / DNS prefetch hints" },
  { key: "native_lazy_loading", category: CATEGORIES.PERFORMANCE, label: "Native image lazy loading" },
  { key: "font_display_swap", category: CATEGORIES.PERFORMANCE, label: "Font display optimisation" },
  { key: "vary_header", category: CATEGORIES.PERFORMANCE, label: "Vary header (content negotiation)" },
  { key: "server_timing", category: CATEGORIES.PERFORMANCE, label: "Server-Timing header" },
  { key: "mfa_signals", category: CATEGORIES.AUTHENTICATION, label: "Multi-factor authentication (MFA)" },
  { key: "email_verification_flow", category: CATEGORIES.AUTHENTICATION, label: "Email verification flow" },
  { key: "magic_link_auth", category: CATEGORIES.AUTHENTICATION, label: "Magic link / passwordless login" },
  { key: "enterprise_sso", category: CATEGORIES.AUTHENTICATION, label: "Enterprise SSO / SAML" },
  { key: "data_deletion_right", category: CATEGORIES.LEGAL, label: "Data deletion / right to erasure (GDPR Art. 17)" },
  { key: "accessibility_statement", category: CATEGORIES.LEGAL, label: "Accessibility statement" },
  { key: "coppa_signals", category: CATEGORIES.LEGAL, label: "COPPA / children" },
  { key: "dpa_available", category: CATEGORIES.LEGAL, label: "Data Processing Agreement (GDPR Art. 28)" },
  { key: "icp_license", category: CATEGORIES.LEGAL, label: "China ICP license (for CN market)" },
  { key: "privacy_last_updated", category: CATEGORIES.LEGAL, label: "Privacy policy maintenance date" },
  { key: "cookie_policy_page", category: CATEGORIES.LEGAL, label: "Dedicated cookie policy page" },
  { key: "gdpr_dpo_contact", category: CATEGORIES.LEGAL, label: "GDPR privacy contact (DPO)" },
  { key: "blog_resources", category: CATEGORIES.MISSING_PAGES, label: "Blog / resources hub" },
  { key: "careers_page", category: CATEGORIES.MISSING_PAGES, label: "Careers / jobs page" },
  { key: "press_media", category: CATEGORIES.MISSING_PAGES, label: "Press / media page" },
  { key: "documentation", category: CATEGORIES.MISSING_PAGES, label: "Documentation / developer docs" },
  { key: "integrations_page", category: CATEGORIES.MISSING_PAGES, label: "Integrations / partners page" },
  { key: "custom_404_page", category: CATEGORIES.MISSING_PAGES, label: "Custom 404 error page" },
  { key: "demo_booking", category: CATEGORIES.SAAS, label: "Demo booking / discovery call" },
  { key: "free_trial_cta", category: CATEGORIES.SAAS, label: "Free trial / free plan CTA" },
  { key: "api_availability", category: CATEGORIES.SAAS, label: "Public API / developer access" },
  { key: "affiliate_program", category: CATEGORIES.SAAS, label: "Affiliate / referral program" },
  { key: "security_trust_page", category: CATEGORIES.SAAS, label: "Security / trust page" },
  { key: "in_app_notifications", category: CATEGORIES.SAAS, label: "In-app notification system" },
  { key: "uptime_monitoring", category: CATEGORIES.OBSERVABILITY, label: "External uptime monitoring" },
  { key: "log_aggregation", category: CATEGORIES.OBSERVABILITY, label: "Centralised log aggregation" },
  { key: "apm_signals", category: CATEGORIES.OBSERVABILITY, label: "Application Performance Monitoring (APM)" },
  { key: "real_user_monitoring", category: CATEGORIES.OBSERVABILITY, label: "Real User Monitoring (RUM)" },
  { key: "payment_trust_badges", category: CATEGORIES.PAYMENTS, label: "Payment trust badges" },
  { key: "bnpl_options", category: CATEGORIES.PAYMENTS, label: "Buy Now Pay Later (BNPL)" },
  { key: "crypto_payments", category: CATEGORIES.PAYMENTS, label: "Cryptocurrency payment option" },
  { key: "smart_app_banner_meta", category: CATEGORIES.APP_STORE, label: "Smart App Banner (iOS web-to-app)" },
  { key: "amazon_app_store", category: CATEGORIES.APP_STORE, label: "Amazon Appstore / Fire TV presence" },
  { key: "app_listing_screenshots", category: CATEGORIES.APP_STORE, label: "App screenshots / listing assets" },
  { key: "app_icon_sizes", category: CATEGORIES.APP_STORE, label: "App icon multiple resolutions" },
  { key: "country_region_selector", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "Country / region selector" },
  { key: "compliance_certifications", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "Compliance certifications (SOC 2, ISO 27001)" },
  { key: "eu_data_residency", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "EU data residency signals" },
  { key: "company_registration_info", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "Company registration info" },
  { key: "timezone_locale_support", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "Timezone / locale-aware content" },
  { key: "social_media_links", category: CATEGORIES.TRUST_BRAND, label: "Social media presence" },
  { key: "third_party_reviews", category: CATEGORIES.TRUST_BRAND, label: "Third-party review platform" },
  { key: "press_coverage", category: CATEGORIES.TRUST_BRAND, label: "Press / media coverage section" },
  { key: "team_presence", category: CATEGORIES.TRUST_BRAND, label: "Founder / team bio with photo" },
  { key: "product_hunt_badge", category: CATEGORIES.TRUST_BRAND, label: "Product Hunt launch presence" },
  { key: "media_kit", category: CATEGORIES.TRUST_BRAND, label: "Media kit / brand assets" },
  { key: "no_placeholder_text", category: CATEGORIES.CODE_QUALITY, label: "No placeholder / lorem ipsum content" },
  { key: "no_hash_routing", category: CATEGORIES.CODE_QUALITY, label: "Clean URL routing (no hash routes)" },
  { key: "spf_record", category: CATEGORIES.SECURITY, label: "SPF record (email spoofing protection)" },
  { key: "dmarc_record", category: CATEGORIES.SECURITY, label: "DMARC record (email impersonation protection)" },
  { key: "mx_record", category: CATEGORIES.INFRASTRUCTURE, label: "MX records (email infrastructure)" },
  { key: "no_exposed_admin", category: CATEGORIES.SECURITY, label: "Admin panel not publicly accessible" },
  { key: "no_exposed_phpinfo", category: CATEGORIES.SECURITY, label: "PHP info page not exposed" },
  { key: "no_exposed_git_config", category: CATEGORIES.SECURITY, label: "Git config not publicly accessible" },
  { key: "no_debug_endpoints", category: CATEGORIES.SECURITY, label: "Debug/monitoring endpoints not public" },
  { key: "no_exposed_backup", category: CATEGORIES.SECURITY, label: "Database backup files not exposed" },
  { key: "http2_enabled", category: CATEGORIES.PERFORMANCE, label: "HTTP/2 protocol" },
  { key: "no_x_powered_by", category: CATEGORIES.SECURITY, label: "X-Powered-By header absent" },
  { key: "no_server_version", category: CATEGORIES.SECURITY, label: "Server version not disclosed" },
  { key: "cors_not_wildcard", category: CATEGORIES.SECURITY, label: "CORS not open to all origins" },
  { key: "has_word_count", category: CATEGORIES.SEO, label: "Sufficient page content" },
  { key: "has_heading_hierarchy", category: CATEGORIES.SEO, label: "Heading hierarchy (H1→H2→H3)" },
  { key: "image_alt_coverage", category: CATEGORIES.ACCESSIBILITY, label: "Image alt text coverage" },
  { key: "internal_links_present", category: CATEGORIES.SEO, label: "Internal linking" },
  { key: "no_broken_inline_scripts", category: CATEGORIES.CODE_QUALITY, label: "No console.log in production HTML" },
  { key: "service_worker_present", category: CATEGORIES.PERFORMANCE, label: "Service worker (offline/caching)" },
  { key: "web_app_manifest_linked", category: CATEGORIES.PERFORMANCE, label: "Web app manifest linked" },
  { key: "theme_color_defined", category: CATEGORIES.PERFORMANCE, label: "Theme colour meta tag" },
  { key: "third_party_script_count", category: CATEGORIES.PERFORMANCE, label: "Third-party script load" },
  { key: "no_jquery_old", category: CATEGORIES.CODE_QUALITY, label: "No outdated jQuery" },
  { key: "annual_billing_signal", category: CATEGORIES.SAAS, label: "Annual billing option" },
  { key: "money_back_signal", category: CATEGORIES.SAAS, label: "Money-back guarantee signal" },
  { key: "live_chat_signal", category: CATEGORIES.SAAS, label: "Live chat / support widget" },
  { key: "demo_booking_signal", category: CATEGORIES.SAAS, label: "Demo booking or discovery call" },
  { key: "social_proof_numbers", category: CATEGORIES.TRUST_BRAND, label: "Quantified social proof" },
  { key: "video_embed_present", category: CATEGORIES.SAAS, label: "Product demo video" },
  { key: "api_docs_signal", category: CATEGORIES.SAAS, label: "API documentation" },
  { key: "openapi_endpoint", category: CATEGORIES.SAAS, label: "OpenAPI spec endpoint" },
  { key: "graphql_signal", category: CATEGORIES.SAAS, label: "GraphQL API" },
  { key: "search_functionality", category: CATEGORIES.SAAS, label: "Search functionality" },
  { key: "cookie_consent_granular", category: CATEGORIES.LEGAL, label: "Granular cookie consent (accept/reject all)" },
  { key: "newsletter_signup", category: CATEGORIES.SAAS, label: "Newsletter / email list capture" },
  { key: "repo_parse", category: CATEGORIES.CODE_QUALITY, label: "Repository URL" },
  { key: "has_readme", category: CATEGORIES.CODE_QUALITY, label: "README.md" },
  { key: "has_tests", category: CATEGORIES.CODE_QUALITY, label: "Test suite" },
  { key: "has_linter", category: CATEGORIES.CODE_QUALITY, label: "Linter config" },
  { key: "has_typescript", category: CATEGORIES.CODE_QUALITY, label: "TypeScript" },
  { key: "has_env_example", category: CATEGORIES.CODE_QUALITY, label: ".env.example" },
  { key: "ci_cd_present", category: CATEGORIES.CODE_QUALITY, label: "CI/CD pipeline" },
  { key: "has_license", category: CATEGORIES.CODE_QUALITY, label: "License file" },
  { key: "has_manifest", category: CATEGORIES.INFRASTRUCTURE, label: "Dependency manifest" },
  { key: "dockerfile_present", category: CATEGORIES.INFRASTRUCTURE, label: "Dockerfile / Docker Compose" },
  { key: "has_contributing", category: CATEGORIES.CODE_QUALITY, label: "CONTRIBUTING.md" },
  { key: "has_code_of_conduct", category: CATEGORIES.CODE_QUALITY, label: "Code of Conduct" },
  { key: "has_security_md", category: CATEGORIES.CODE_QUALITY, label: "SECURITY.md (vulnerability disclosure)" },
  { key: "has_dependabot", category: CATEGORIES.CODE_QUALITY, label: "Dependabot / automated dependency updates" },
  { key: "has_changelog_file", category: CATEGORIES.CODE_QUALITY, label: "CHANGELOG.md" },
  { key: "has_openapi_spec", category: CATEGORIES.CODE_QUALITY, label: "OpenAPI / Swagger spec" },
  { key: "has_editorconfig", category: CATEGORIES.CODE_QUALITY, label: ".editorconfig (consistent formatting)" },
  { key: "has_gitignore", category: CATEGORIES.CODE_QUALITY, label: ".gitignore" },
  { key: "has_e2e_tests", category: CATEGORIES.CODE_QUALITY, label: "E2E test suite (Playwright / Cypress)" },
  { key: "has_unit_test_config", category: CATEGORIES.CODE_QUALITY, label: "Unit test framework (Jest / Vitest)" },
  { key: "has_git_hooks", category: CATEGORIES.CODE_QUALITY, label: "Git hooks (Husky / lefthook)" },
  { key: "has_orm_config", category: CATEGORIES.INFRASTRUCTURE, label: "ORM / database configuration" },
  { key: "has_migrations", category: CATEGORIES.INFRASTRUCTURE, label: "Database migrations" },
  { key: "has_renovate", category: CATEGORIES.CODE_QUALITY, label: "Renovate / automated dependency updates" },
  { key: "has_devcontainer", category: CATEGORIES.INFRASTRUCTURE, label: "Dev container (.devcontainer)" },
  { key: "has_infra_code", category: CATEGORIES.INFRASTRUCTURE, label: "Infrastructure as Code (Terraform / Helm / K8s)" },
  { key: "has_makefile", category: CATEGORIES.CODE_QUALITY, label: "Makefile / task runner" },
  { key: "is_monorepo", category: CATEGORIES.CODE_QUALITY, label: "Monorepo tooling (Turbo / Nx / pnpm workspaces)" },
  { key: "has_coverage_config", category: CATEGORIES.CODE_QUALITY, label: "Code coverage reporting" },

  // ─── Security Extended (30) ─────────────────────────────────────────────────
  { key: "cross_origin_opener_policy", category: CATEGORIES.SECURITY, label: "Cross-Origin-Opener-Policy (COOP)" },
  { key: "cross_origin_resource_policy", category: CATEGORIES.SECURITY, label: "Cross-Origin-Resource-Policy (CORP)" },
  { key: "cross_origin_embedder_policy", category: CATEGORIES.SECURITY, label: "Cross-Origin-Embedder-Policy (COEP)" },
  { key: "csp_report_directive", category: CATEGORIES.SECURITY, label: "CSP report-uri / report-to configured" },
  { key: "rate_limiting_headers", category: CATEGORIES.SECURITY, label: "Rate-limiting headers present" },
  { key: "caa_dns_record", category: CATEGORIES.SECURITY, label: "CAA DNS record (cert authority restriction)" },
  { key: "dnssec_enabled", category: CATEGORIES.SECURITY, label: "DNSSEC enabled on domain" },
  { key: "certificate_expiry_30d", category: CATEGORIES.SECURITY, label: "SSL cert not expiring within 30 days" },
  { key: "no_exposed_ds_store", category: CATEGORIES.SECURITY, label: ".DS_Store not publicly accessible" },
  { key: "no_exposed_composer_json", category: CATEGORIES.SECURITY, label: "composer.json not at web root" },
  { key: "no_exposed_package_json_root", category: CATEGORIES.SECURITY, label: "package.json not served at root" },
  { key: "no_exposed_swagger_open", category: CATEGORIES.SECURITY, label: "Swagger UI not open in production" },
  { key: "no_exposed_actuator", category: CATEGORIES.SECURITY, label: "/actuator endpoints not public" },
  { key: "no_exposed_prometheus_metrics", category: CATEGORIES.SECURITY, label: "/metrics endpoint not public" },
  { key: "no_graphql_introspection_prod", category: CATEGORIES.SECURITY, label: "GraphQL introspection disabled in prod" },
  { key: "no_exposed_source_maps", category: CATEGORIES.SECURITY, label: "Source maps not served with page" },
  { key: "no_api_keys_in_html", category: CATEGORIES.SECURITY, label: "No API key patterns in HTML source" },
  { key: "csrf_protection_signals", category: CATEGORIES.SECURITY, label: "CSRF token protection detected" },
  { key: "bot_protection_present", category: CATEGORIES.SECURITY, label: "Bot protection (Cloudflare / reCAPTCHA)" },
  { key: "sql_error_exposure", category: CATEGORIES.SECURITY, label: "No SQL errors exposed in responses" },
  { key: "brute_force_protection", category: CATEGORIES.SECURITY, label: "Brute force / rate limit on auth" },
  { key: "session_cookie_httponly", category: CATEGORIES.SECURITY, label: "HttpOnly flag on session cookies" },
  { key: "session_cookie_samesite", category: CATEGORIES.SECURITY, label: "SameSite attribute on cookies" },
  { key: "csp_frame_ancestors", category: CATEGORIES.SECURITY, label: "frame-ancestors in CSP policy" },
  { key: "no_exposed_env_variants", category: CATEGORIES.SECURITY, label: ".env.prod / .env.docker not accessible" },
  { key: "secret_scanning_github", category: CATEGORIES.SECURITY, label: "No secrets / keys in page HTML" },
  { key: "cors_credentials_restricted", category: CATEGORIES.SECURITY, label: "CORS credentials not open to all origins" },
  { key: "dependency_audit_clean", category: CATEGORIES.SECURITY, label: "No obvious vulnerable library versions" },
  { key: "subdomain_takeover_risk", category: CATEGORIES.SECURITY, label: "No dangling CNAME / subdomain takeover risk" },
  { key: "content_security_policy_nonce", category: CATEGORIES.SECURITY, label: "CSP uses nonces (not unsafe-inline)" },

  // ─── Legal & Compliance Extended (35) ──────────────────────────────────────
  { key: "gdpr_article13_notice", category: CATEGORIES.LEGAL, label: "Data collection notice (GDPR Art. 13/14)" },
  { key: "gdpr_right_to_access", category: CATEGORIES.LEGAL, label: "Right to access data (GDPR Art. 15)" },
  { key: "gdpr_right_to_erasure_ui", category: CATEGORIES.LEGAL, label: "Right to erasure UI (GDPR Art. 17)" },
  { key: "gdpr_right_to_portability", category: CATEGORIES.LEGAL, label: "Data portability (GDPR Art. 20)" },
  { key: "gdpr_right_to_object", category: CATEGORIES.LEGAL, label: "Right to object to processing (GDPR Art. 21)" },
  { key: "gdpr_lawful_basis_stated", category: CATEGORIES.LEGAL, label: "Lawful basis stated in privacy policy" },
  { key: "gdpr_breach_notification", category: CATEGORIES.LEGAL, label: "Breach notification procedure (GDPR Art. 33)" },
  { key: "gdpr_records_processing", category: CATEGORIES.LEGAL, label: "Records of Processing Activities (GDPR Art. 30)" },
  { key: "uk_gdpr_ico_registration", category: CATEGORIES.LEGAL, label: "ICO registration number shown (UK GDPR)" },
  { key: "eu_representative_contact", category: CATEGORIES.LEGAL, label: "EU Art. 27 representative for non-EU companies" },
  { key: "eprivacy_pecr_compliance", category: CATEGORIES.LEGAL, label: "UK PECR / ePrivacy cookie compliance" },
  { key: "digital_markets_act", category: CATEGORIES.LEGAL, label: "EU Digital Markets Act compliance signals" },
  { key: "eu_ai_act_disclosure", category: CATEGORIES.LEGAL, label: "EU AI Act transparency disclosure" },
  { key: "lgpd_brazil", category: CATEGORIES.LEGAL, label: "Brazil LGPD compliance" },
  { key: "pipeda_canada", category: CATEGORIES.LEGAL, label: "Canada PIPEDA / Law 25 compliance" },
  { key: "pdpa_singapore", category: CATEGORIES.LEGAL, label: "Singapore PDPA compliance" },
  { key: "pdpa_thailand", category: CATEGORIES.LEGAL, label: "Thailand PDPA compliance" },
  { key: "popia_south_africa", category: CATEGORIES.LEGAL, label: "South Africa POPIA compliance" },
  { key: "appi_japan", category: CATEGORIES.LEGAL, label: "Japan APPI compliance" },
  { key: "pipl_china", category: CATEGORIES.LEGAL, label: "China PIPL compliance" },
  { key: "pipa_korea", category: CATEGORIES.LEGAL, label: "South Korea PIPA compliance" },
  { key: "dpdp_india", category: CATEGORIES.LEGAL, label: "India DPDP Act compliance" },
  { key: "australian_privacy_act", category: CATEGORIES.LEGAL, label: "Australian Privacy Act compliance" },
  { key: "hipaa_signals", category: CATEGORIES.LEGAL, label: "HIPAA compliance signals (healthcare)" },
  { key: "pci_dss_scope_reduction", category: CATEGORIES.LEGAL, label: "PCI DSS scope reduction evidence" },
  { key: "ferpa_signals", category: CATEGORIES.LEGAL, label: "FERPA compliance signals (education)" },
  { key: "cooling_off_period_eu", category: CATEGORIES.LEGAL, label: "EU 14-day cancellation right stated" },
  { key: "auto_renewal_disclosure", category: CATEGORIES.LEGAL, label: "Auto-renewal terms prominently disclosed" },
  { key: "subscription_cancellation_easy", category: CATEGORIES.LEGAL, label: "Easy cancellation (FTC click-to-cancel)" },
  { key: "price_vat_inclusive", category: CATEGORIES.LEGAL, label: "Prices shown inc. VAT (EU requirement)" },
  { key: "distance_selling_notice", category: CATEGORIES.LEGAL, label: "EU Distance Selling regulations disclosure" },
  { key: "intellectual_property_notice", category: CATEGORIES.LEGAL, label: "Copyright notice present" },
  { key: "dmca_policy", category: CATEGORIES.LEGAL, label: "DMCA takedown procedure" },
  { key: "age_gate", category: CATEGORIES.LEGAL, label: "Age verification / age gate" },
  { key: "contract_terms_b2b", category: CATEGORIES.LEGAL, label: "B2B contract terms / SLA documented" },

  // ─── Performance Extended (20) ──────────────────────────────────────────────
  { key: "next_gen_image_formats", category: CATEGORIES.PERFORMANCE, label: "Next-gen image formats (WebP / AVIF)" },
  { key: "image_dimension_attributes", category: CATEGORIES.PERFORMANCE, label: "Image width/height attributes (CLS prevention)" },
  { key: "critical_css_inlined", category: CATEGORIES.PERFORMANCE, label: "Critical CSS inlined in <head>" },
  { key: "css_appears_minified", category: CATEGORIES.PERFORMANCE, label: "CSS appears minified" },
  { key: "js_appears_minified", category: CATEGORIES.PERFORMANCE, label: "JS files appear minified" },
  { key: "http3_quic_support", category: CATEGORIES.PERFORMANCE, label: "HTTP/3 / QUIC support" },
  { key: "early_hints_support", category: CATEGORIES.PERFORMANCE, label: "103 Early Hints support" },
  { key: "stale_while_revalidate", category: CATEGORIES.PERFORMANCE, label: "Stale-while-revalidate cache directive" },
  { key: "immutable_cache_assets", category: CATEGORIES.PERFORMANCE, label: "Immutable cache on hashed assets" },
  { key: "dns_ttl_optimized", category: CATEGORIES.PERFORMANCE, label: "DNS TTL not near-zero" },
  { key: "render_blocking_scripts", category: CATEGORIES.PERFORMANCE, label: "No render-blocking scripts" },
  { key: "lcp_fetchpriority_hint", category: CATEGORIES.PERFORMANCE, label: "fetchpriority=high on LCP image" },
  { key: "image_width_height", category: CATEGORIES.PERFORMANCE, label: "Images have explicit width/height" },
  { key: "font_preload_hint", category: CATEGORIES.PERFORMANCE, label: "Fonts preloaded" },
  { key: "total_page_weight", category: CATEGORIES.PERFORMANCE, label: "Total page weight < 3MB" },
  { key: "third_party_script_blocking", category: CATEGORIES.PERFORMANCE, label: "No render-blocking third-party scripts" },
  { key: "no_unused_javascript", category: CATEGORIES.PERFORMANCE, label: "Code splitting / lazy loading signals" },
  { key: "module_script_type", category: CATEGORIES.PERFORMANCE, label: "type=module on script tags" },
  { key: "resource_hints_comprehensive", category: CATEGORIES.PERFORMANCE, label: "Comprehensive resource hints" },
  { key: "woff2_font_format", category: CATEGORIES.PERFORMANCE, label: "WOFF2 font format used" },

  // ─── WCAG Accessibility (20) ─────────────────────────────────────────────────
  { key: "skip_to_main_content", category: CATEGORIES.ACCESSIBILITY, label: "Skip to main content link" },
  { key: "image_input_alt", category: CATEGORIES.ACCESSIBILITY, label: "<input type=image> has alt text" },
  { key: "video_captions", category: CATEGORIES.ACCESSIBILITY, label: "Video has captions track" },
  { key: "form_labels_present", category: CATEGORIES.ACCESSIBILITY, label: "<label> for every <input>" },
  { key: "form_error_identification", category: CATEGORIES.ACCESSIBILITY, label: "Form errors identify the field" },
  { key: "keyboard_focus_visible", category: CATEGORIES.ACCESSIBILITY, label: ":focus-visible CSS present" },
  { key: "touch_target_size", category: CATEGORIES.ACCESSIBILITY, label: "Sufficient touch target sizing" },
  { key: "no_autoplay_audio", category: CATEGORIES.ACCESSIBILITY, label: "No autoplay audio without controls" },
  { key: "no_autoplay_video", category: CATEGORIES.ACCESSIBILITY, label: "No autoplay video without controls" },
  { key: "session_timeout_warning", category: CATEGORIES.ACCESSIBILITY, label: "Session timeout warning" },
  { key: "valid_html_parsing", category: CATEGORIES.ACCESSIBILITY, label: "No obvious HTML parsing errors" },
  { key: "aria_roles_valid", category: CATEGORIES.ACCESSIBILITY, label: "ARIA landmark roles used" },
  { key: "aria_live_regions", category: CATEGORIES.ACCESSIBILITY, label: "aria-live for dynamic content" },
  { key: "prefers_reduced_motion", category: CATEGORIES.ACCESSIBILITY, label: "prefers-reduced-motion CSS" },
  { key: "prefers_high_contrast", category: CATEGORIES.ACCESSIBILITY, label: "prefers-contrast CSS media query" },
  { key: "sufficient_colour_contrast", category: CATEGORIES.ACCESSIBILITY, label: "No obvious low-contrast inline styles" },
  { key: "text_spacing_supported", category: CATEGORIES.ACCESSIBILITY, label: "Letter/word spacing not fixed" },
  { key: "link_purpose_clear", category: CATEGORIES.ACCESSIBILITY, label: "Links have descriptive text" },
  { key: "page_title_unique", category: CATEGORIES.ACCESSIBILITY, label: "Unique page title" },
  { key: "language_attribute_body", category: CATEGORIES.ACCESSIBILITY, label: "lang attribute on <html> element" },

  // ─── Authentication Extended (15) ───────────────────────────────────────────
  { key: "session_timeout_configured", category: CATEGORIES.AUTHENTICATION, label: "Session timeout configured" },
  { key: "account_lockout_policy", category: CATEGORIES.AUTHENTICATION, label: "Account lockout policy" },
  { key: "password_strength_enforced", category: CATEGORIES.AUTHENTICATION, label: "Password strength requirements" },
  { key: "passkey_webauthn_support", category: CATEGORIES.AUTHENTICATION, label: "Passkeys / WebAuthn support" },
  { key: "breach_password_detection", category: CATEGORIES.AUTHENTICATION, label: "Breach password detection" },
  { key: "account_recovery_options", category: CATEGORIES.AUTHENTICATION, label: "Account recovery beyond email" },
  { key: "jwt_not_in_localstorage", category: CATEGORIES.AUTHENTICATION, label: "JWT not stored in localStorage" },
  { key: "refresh_token_rotation", category: CATEGORIES.AUTHENTICATION, label: "Refresh token rotation" },
  { key: "pkce_oauth_flow", category: CATEGORIES.AUTHENTICATION, label: "PKCE for OAuth public clients" },
  { key: "api_key_creation_ui", category: CATEGORIES.AUTHENTICATION, label: "API key generation UI" },
  { key: "oauth_minimal_scopes", category: CATEGORIES.AUTHENTICATION, label: "Minimal OAuth scope requests" },
  { key: "service_account_support", category: CATEGORIES.AUTHENTICATION, label: "Machine-to-machine / service account tokens" },
  { key: "device_management", category: CATEGORIES.AUTHENTICATION, label: "Trusted device management" },
  { key: "concurrent_session_policy", category: CATEGORIES.AUTHENTICATION, label: "Concurrent session limiting" },
  { key: "token_expiry_short", category: CATEGORIES.AUTHENTICATION, label: "Short-lived access tokens (< 1hr)" },
  { key: "otp_expiry_configured", category: CATEGORIES.AUTHENTICATION, label: "OTP code expiry" },
  { key: "otp_resend_cooldown", category: CATEGORIES.AUTHENTICATION, label: "OTP resend cooldown" },
  { key: "otp_attempt_limiting", category: CATEGORIES.AUTHENTICATION, label: "OTP attempt / brute-force limiting" },

  // ─── Roles & Permissions (20) ───────────────────────────────────────────────
  { key: "rbac_signals", category: CATEGORIES.ROLES, label: "Role-based access control (RBAC) UI" },
  { key: "admin_role_separation", category: CATEGORIES.ROLES, label: "Admin vs user role separation" },
  { key: "team_management_ui", category: CATEGORIES.ROLES, label: "Team / org management UI" },
  { key: "invite_workflow", category: CATEGORIES.ROLES, label: "User invitation workflow" },
  { key: "permission_matrix_docs", category: CATEGORIES.ROLES, label: "Permissions matrix documentation" },
  { key: "data_scope_isolation", category: CATEGORIES.ROLES, label: "Multi-tenant data isolation signals" },
  { key: "audit_trail_present", category: CATEGORIES.ROLES, label: "Audit log / activity log" },
  { key: "api_scope_documentation", category: CATEGORIES.ROLES, label: "API scopes documented" },
  { key: "least_privilege_api_tokens", category: CATEGORIES.ROLES, label: "Scoped / least-privilege API tokens" },
  { key: "role_hierarchy", category: CATEGORIES.ROLES, label: "Admin > Manager > User role hierarchy" },
  { key: "access_revocation_ui", category: CATEGORIES.ROLES, label: "Account deactivation / access revocation UI" },
  { key: "ip_allowlisting", category: CATEGORIES.ROLES, label: "IP restriction / allowlist available" },
  { key: "sso_scim_provisioning", category: CATEGORIES.ROLES, label: "SCIM provisioning support" },
  { key: "mfa_admin_enforced", category: CATEGORIES.ROLES, label: "MFA required for admin accounts" },
  { key: "guest_anonymous_mode", category: CATEGORIES.ROLES, label: "Guest / view-only mode" },
  { key: "read_only_role", category: CATEGORIES.ROLES, label: "Read-only role available" },
  { key: "data_export_permission", category: CATEGORIES.ROLES, label: "Data export restricted by role" },
  { key: "workspace_tenant_isolation", category: CATEGORIES.ROLES, label: "Workspace / tenant isolation" },
  { key: "permission_inheritance", category: CATEGORIES.ROLES, label: "Permission inheritance (groups)" },
  { key: "gdpr_data_access_control", category: CATEGORIES.ROLES, label: "GDPR data access controlled by role" },

  // ─── Email Deliverability (15) ───────────────────────────────────────────────
  { key: "dkim_record_present", category: CATEGORIES.EMAIL, label: "DKIM record configured" },
  { key: "bimi_record_present", category: CATEGORIES.EMAIL, label: "BIMI DNS record (brand in inbox)" },
  { key: "mta_sts_policy", category: CATEGORIES.EMAIL, label: "MTA-STS enforced mail transfer" },
  { key: "tls_rpt_record", category: CATEGORIES.EMAIL, label: "TLS-RPT reporting record" },
  { key: "spf_hardfail", category: CATEGORIES.EMAIL, label: "SPF uses -all (hardfail)" },
  { key: "dmarc_quarantine_reject", category: CATEGORIES.EMAIL, label: "DMARC policy: quarantine or reject" },
  { key: "email_unsubscribe_signal", category: CATEGORIES.EMAIL, label: "Unsubscribe / list management link" },
  { key: "transactional_subdomain", category: CATEGORIES.EMAIL, label: "Dedicated sending subdomain" },
  { key: "can_spam_address", category: CATEGORIES.EMAIL, label: "Physical address in email footer" },
  { key: "casl_double_optin", category: CATEGORIES.EMAIL, label: "Double opt-in / CASL signals" },
  { key: "plain_text_email", category: CATEGORIES.EMAIL, label: "Plain text email alternative" },
  { key: "bounce_handling_signal", category: CATEGORIES.EMAIL, label: "Bounce handling / list hygiene" },
  { key: "email_preview_configured", category: CATEGORIES.EMAIL, label: "Email preview text configured" },
  { key: "email_warm_up_signals", category: CATEGORIES.EMAIL, label: "Reputable ESP detected" },
  { key: "mailing_list_segmentation", category: CATEGORIES.EMAIL, label: "Email segmentation / tagging signals" },

  // ─── Observability Extended (15) ────────────────────────────────────────────
  { key: "alert_pagerduty_opsgenie", category: CATEGORIES.OBSERVABILITY, label: "PagerDuty / OpsGenie / alerting configured" },
  { key: "on_call_configured", category: CATEGORIES.OBSERVABILITY, label: "On-call rotation configured" },
  { key: "distributed_tracing", category: CATEGORIES.OBSERVABILITY, label: "Distributed tracing configured" },
  { key: "custom_business_metrics", category: CATEGORIES.OBSERVABILITY, label: "Custom business metrics / dashboards" },
  { key: "synthetic_monitoring", category: CATEGORIES.OBSERVABILITY, label: "Synthetic monitoring (uptime checks)" },
  { key: "structured_logging", category: CATEGORIES.OBSERVABILITY, label: "Structured / JSON logging" },
  { key: "log_retention_policy", category: CATEGORIES.OBSERVABILITY, label: "Log retention policy configured" },
  { key: "audit_log_api_export", category: CATEGORIES.OBSERVABILITY, label: "Audit log accessible via API" },
  { key: "db_performance_monitoring", category: CATEGORIES.OBSERVABILITY, label: "Database performance monitoring" },
  { key: "queue_depth_monitoring", category: CATEGORIES.OBSERVABILITY, label: "Message queue depth monitoring" },
  { key: "cost_monitoring_signals", category: CATEGORIES.OBSERVABILITY, label: "Cloud cost alerting" },
  { key: "error_budget_policy", category: CATEGORIES.OBSERVABILITY, label: "SLO / error budget policy" },
  { key: "incident_runbooks", category: CATEGORIES.OBSERVABILITY, label: "Incident runbooks / playbooks" },
  { key: "post_mortem_culture", category: CATEGORIES.OBSERVABILITY, label: "Post-mortem / incident review culture" },
  { key: "deployment_frequency_tracking", category: CATEGORIES.OBSERVABILITY, label: "Deployment frequency / DORA metrics tracked" },

  // ─── Infrastructure Extended (15) ───────────────────────────────────────────
  { key: "ipv6_dns_record", category: CATEGORIES.INFRASTRUCTURE, label: "IPv6 (AAAA) DNS record present" },
  { key: "multi_region_signals", category: CATEGORIES.INFRASTRUCTURE, label: "Multi-region deployment signals" },
  { key: "load_balancer_detected", category: CATEGORIES.INFRASTRUCTURE, label: "Load balancer / reverse proxy detected" },
  { key: "auto_scaling_configured", category: CATEGORIES.INFRASTRUCTURE, label: "Auto-scaling signals" },
  { key: "circuit_breaker_pattern", category: CATEGORIES.INFRASTRUCTURE, label: "Circuit breaker / retry pattern" },
  { key: "graceful_shutdown_configured", category: CATEGORIES.INFRASTRUCTURE, label: "Graceful shutdown / SIGTERM handling" },
  { key: "environment_separation", category: CATEGORIES.INFRASTRUCTURE, label: "Prod / staging / dev separation" },
  { key: "blue_green_canary_deploy", category: CATEGORIES.INFRASTRUCTURE, label: "Blue/green or canary deployment" },
  { key: "feature_flags_system", category: CATEGORIES.INFRASTRUCTURE, label: "Feature flag system" },
  { key: "secrets_manager_used", category: CATEGORIES.INFRASTRUCTURE, label: "Secrets manager (Vault / AWS Secrets Manager)" },
  { key: "database_read_replicas", category: CATEGORIES.INFRASTRUCTURE, label: "Database read replicas" },
  { key: "dns_ttl_healthy", category: CATEGORIES.INFRASTRUCTURE, label: "DNS TTL configured for stability" },
  { key: "backup_domain_configured", category: CATEGORIES.INFRASTRUCTURE, label: "www subdomain / backup domain configured" },
  { key: "object_storage_signals", category: CATEGORIES.INFRASTRUCTURE, label: "Object storage (S3 / GCS) for assets" },
  { key: "cdn_custom_caching_rules", category: CATEGORIES.INFRASTRUCTURE, label: "CDN caching configured" },

  // ─── SaaS Readiness Extended (15) ───────────────────────────────────────────
  { key: "saml_sso_available", category: CATEGORIES.SAAS, label: "SAML / SSO enterprise tier" },
  { key: "scim_user_provisioning", category: CATEGORIES.SAAS, label: "SCIM user provisioning" },
  { key: "custom_branding_available", category: CATEGORIES.SAAS, label: "White-label / custom branding" },
  { key: "enterprise_pricing_tier", category: CATEGORIES.SAAS, label: "Enterprise pricing tier" },
  { key: "keyboard_shortcuts_ui", category: CATEGORIES.SAAS, label: "Keyboard shortcut hints" },
  { key: "dark_mode_supported", category: CATEGORIES.SAAS, label: "Dark mode (prefers-color-scheme)" },
  { key: "bulk_operations_ui", category: CATEGORIES.SAAS, label: "Bulk select / bulk operations" },
  { key: "data_export_csv_pdf", category: CATEGORIES.SAAS, label: "Data export (CSV / PDF / Excel)" },
  { key: "data_import_capability", category: CATEGORIES.SAAS, label: "Data import / migration" },
  { key: "community_forum_slack", category: CATEGORIES.SAAS, label: "Community forum or Slack workspace" },
  { key: "app_marketplace_listed", category: CATEGORIES.SAAS, label: "App marketplace listing" },
  { key: "public_roadmap", category: CATEGORIES.SAAS, label: "Public product roadmap" },
  { key: "partner_reseller_program", category: CATEGORIES.SAAS, label: "Partner / reseller programme" },
  { key: "g2_capterra_listed", category: CATEGORIES.SAAS, label: "G2 or Capterra listing" },
  { key: "volume_discount_signals", category: CATEGORIES.SAAS, label: "Volume discount signals" },

  // ─── Payments Extended (10) ─────────────────────────────────────────────────
  { key: "sepa_bank_transfer", category: CATEGORIES.PAYMENTS, label: "SEPA / bank transfer option (EU)" },
  { key: "paypal_integration", category: CATEGORIES.PAYMENTS, label: "PayPal integration" },
  { key: "three_ds_sca_compliant", category: CATEGORIES.PAYMENTS, label: "3D Secure / PSD2 SCA compliant" },
  { key: "fraud_detection_tool", category: CATEGORIES.PAYMENTS, label: "Fraud detection (Stripe Radar / Kount)" },
  { key: "pci_saq_evidence", category: CATEGORIES.PAYMENTS, label: "PCI SAQ / scope reduction evidence" },
  { key: "regional_payment_methods", category: CATEGORIES.PAYMENTS, label: "Regional payment methods (Klarna, iDEAL, etc.)" },
  { key: "chargeback_prevention", category: CATEGORIES.PAYMENTS, label: "Chargeback prevention tools" },
  { key: "subscription_proration", category: CATEGORIES.PAYMENTS, label: "Subscription plan proration" },
  { key: "invoicing_capability", category: CATEGORIES.PAYMENTS, label: "Invoice generation for B2B" },
  { key: "tax_automation", category: CATEGORIES.PAYMENTS, label: "Tax automation (Avalara / Stripe Tax)" },

  // ─── SEO Extended (15) ──────────────────────────────────────────────────────
  { key: "faqpage_schema", category: CATEGORIES.SEO, label: "FAQPage JSON-LD schema" },
  { key: "product_schema", category: CATEGORIES.SEO, label: "Product schema markup" },
  { key: "organization_schema", category: CATEGORIES.SEO, label: "Organization schema markup" },
  { key: "article_schema", category: CATEGORIES.SEO, label: "Article / BlogPosting schema" },
  { key: "review_schema", category: CATEGORIES.SEO, label: "AggregateRating / Review schema" },
  { key: "breadcrumb_schema", category: CATEGORIES.SEO, label: "BreadcrumbList schema" },
  { key: "local_business_schema", category: CATEGORIES.SEO, label: "LocalBusiness schema" },
  { key: "sitemap_index", category: CATEGORIES.SEO, label: "XML sitemap index" },
  { key: "image_sitemap_present", category: CATEGORIES.SEO, label: "Image sitemap" },
  { key: "news_sitemap_present", category: CATEGORIES.SEO, label: "Google News sitemap" },
  { key: "pagination_rel_links", category: CATEGORIES.SEO, label: "Pagination rel=prev/next links" },
  { key: "canonical_self_referencing", category: CATEGORIES.SEO, label: "Self-referencing canonical on key pages" },
  { key: "google_business_profile", category: CATEGORIES.SEO, label: "Google Business Profile signals" },
  { key: "bing_webmaster_verified", category: CATEGORIES.SEO, label: "Bing Webmaster Tools verification" },
  { key: "internal_link_depth", category: CATEGORIES.SEO, label: "Key pages within 3 clicks of homepage" },

  // ─── Trust & Brand Extended (10) ────────────────────────────────────────────
  { key: "customer_logo_wall", category: CATEGORIES.TRUST_BRAND, label: "Customer logo wall" },
  { key: "case_studies_present", category: CATEGORIES.TRUST_BRAND, label: "Customer case studies" },
  { key: "awards_recognition", category: CATEGORIES.TRUST_BRAND, label: "Industry awards / recognition badges" },
  { key: "security_whitepaper", category: CATEGORIES.TRUST_BRAND, label: "Security whitepaper / documentation" },
  { key: "github_org_public", category: CATEGORIES.TRUST_BRAND, label: "Public GitHub organisation" },
  { key: "cto_technical_bio", category: CATEGORIES.TRUST_BRAND, label: "CTO / technical lead bio" },
  { key: "investor_backing_listed", category: CATEGORIES.TRUST_BRAND, label: "VC / accelerator backing mentioned" },
  { key: "conference_speaking", category: CATEGORIES.TRUST_BRAND, label: "Conference / speaking appearances" },
  { key: "uptime_history_public", category: CATEGORIES.TRUST_BRAND, label: "Public uptime / reliability history" },
  { key: "named_customer_quotes", category: CATEGORIES.TRUST_BRAND, label: "Named customer quotes (not anonymous)" },

  // ─── Missing Pages Extended (10) ────────────────────────────────────────────
  { key: "legal_hub_page", category: CATEGORIES.MISSING_PAGES, label: "/legal hub page" },
  { key: "security_dedicated_page", category: CATEGORIES.MISSING_PAGES, label: "/security dedicated page" },
  { key: "api_docs_page", category: CATEGORIES.MISSING_PAGES, label: "API documentation page" },
  { key: "system_requirements_page", category: CATEGORIES.MISSING_PAGES, label: "System requirements / compatibility" },
  { key: "roadmap_public_page", category: CATEGORIES.MISSING_PAGES, label: "Public /roadmap page" },
  { key: "pricing_comparison_table", category: CATEGORIES.MISSING_PAGES, label: "Pricing comparison / feature matrix" },
  { key: "migration_import_guide", category: CATEGORIES.MISSING_PAGES, label: "Migration / import guide" },
  { key: "partners_ecosystem_page", category: CATEGORIES.MISSING_PAGES, label: "/partners or /ecosystem page" },
  { key: "affiliate_programme_page", category: CATEGORIES.MISSING_PAGES, label: "/affiliate programme page" },
  { key: "release_notes_page", category: CATEGORIES.MISSING_PAGES, label: "/release-notes page" },

  // ─── Global Distribution Extended (10) ─────────────────────────────────────
  { key: "uk_pecr_cookie_law", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "UK PECR cookie law compliance" },
  { key: "cnil_france_compliant", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "CNIL compliance signals (France)" },
  { key: "eu_art27_representative", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "EU Art. 27 representative named" },
  { key: "consumer_law_aus", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "Australian Consumer Law signals" },
  { key: "local_phone_numbers", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "Local phone numbers for target markets" },
  { key: "vat_moss_oss_signals", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "EU VAT OSS (One Stop Shop) compliance" },
  { key: "gdpr_dpa_list_public", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "Sub-processors list publicly available" },
  { key: "iso_27701_signals", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "ISO 27701 (privacy management) signals" },
  { key: "transfer_impact_assessment", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "SCCs / Data Transfer Impact Assessment" },
  { key: "local_legal_notice", category: CATEGORIES.GLOBAL_DISTRIBUTION, label: "Mentions Légales (France / Belgium)" },

  // ─── Code Quality Extended (10) ─────────────────────────────────────────────
  { key: "github_code_scanning", category: CATEGORIES.CODE_QUALITY, label: "Code scanning (CodeQL / Snyk)" },
  { key: "github_branch_protection", category: CATEGORIES.CODE_QUALITY, label: "Branch protection rules" },
  { key: "github_required_reviews", category: CATEGORIES.CODE_QUALITY, label: "Required PR approvals" },
  { key: "github_codeowners", category: CATEGORIES.CODE_QUALITY, label: "CODEOWNERS file" },
  { key: "github_secret_scanning", category: CATEGORIES.CODE_QUALITY, label: "GitHub secret scanning" },
  { key: "github_pr_template", category: CATEGORIES.CODE_QUALITY, label: "PR description template" },
  { key: "github_issue_templates", category: CATEGORIES.CODE_QUALITY, label: "Issue templates" },
  { key: "commit_signing_enabled", category: CATEGORIES.CODE_QUALITY, label: "Signed commits (GPG / Sigstore)" },
  { key: "release_automation", category: CATEGORIES.CODE_QUALITY, label: "Release automation (semantic-release)" },
  { key: "stale_bot_configured", category: CATEGORIES.CODE_QUALITY, label: "Stale issue / PR management" },

  // ─── Mobile & Accessibility Extended (10) ───────────────────────────────────
  { key: "web_push_notifications", category: CATEGORIES.MOBILE, label: "Web Push Notifications support" },
  { key: "push_permission_polite", category: CATEGORIES.MOBILE, label: "Polite push permission prompt" },
  { key: "offline_mode_capable", category: CATEGORIES.MOBILE, label: "Service worker offline support" },
  { key: "reduced_motion_css", category: CATEGORIES.MOBILE, label: "prefers-reduced-motion CSS" },
  { key: "high_contrast_css", category: CATEGORIES.MOBILE, label: "prefers-contrast CSS media query" },
  { key: "biometric_auth_signals", category: CATEGORIES.MOBILE, label: "WebAuthn biometric auth signals" },
  { key: "screen_reader_tested_signal", category: CATEGORIES.MOBILE, label: "Accessibility testing evidence" },
  { key: "gesture_navigation", category: CATEGORIES.MOBILE, label: "Swipe / gesture navigation" },
  { key: "apple_app_clip_support", category: CATEGORIES.MOBILE, label: "App Clips support (iOS)" },
  { key: "android_instant_app", category: CATEGORIES.MOBILE, label: "Android Instant Apps" },

  // ─── Business Operations (15) ───────────────────────────────────────────────
  { key: "physical_address_footer", category: CATEGORIES.BUSINESS_OPS, label: "Physical address in footer" },
  { key: "business_hours_displayed", category: CATEGORIES.BUSINESS_OPS, label: "Business hours displayed" },
  { key: "vat_number_displayed", category: CATEGORIES.BUSINESS_OPS, label: "VAT number in footer (EU B2B)" },
  { key: "uk_companies_house_number", category: CATEGORIES.BUSINESS_OPS, label: "UK Companies House registration number" },
  { key: "eu_director_info", category: CATEGORIES.BUSINESS_OPS, label: "Director / responsible person named" },
  { key: "support_sla_documented", category: CATEGORIES.BUSINESS_OPS, label: "Support SLA / response times documented" },
  { key: "esignature_support", category: CATEGORIES.BUSINESS_OPS, label: "eSignature / contract workflow" },
  { key: "invoice_generation_b2b", category: CATEGORIES.BUSINESS_OPS, label: "Invoice / tax invoice generation" },
  { key: "insurance_mention", category: CATEGORIES.BUSINESS_OPS, label: "Professional indemnity insurance" },
  { key: "gdpr_ropa_maintained", category: CATEGORIES.BUSINESS_OPS, label: "ROPA (Records of Processing Activities)" },
  { key: "data_retention_schedule", category: CATEGORIES.BUSINESS_OPS, label: "Data retention schedule published" },
  { key: "supplier_due_diligence", category: CATEGORIES.BUSINESS_OPS, label: "Vendor / sub-processor due diligence" },
  { key: "modern_slavery_statement", category: CATEGORIES.BUSINESS_OPS, label: "Modern Slavery Act statement" },
  { key: "bribery_act_policy", category: CATEGORIES.BUSINESS_OPS, label: "Anti-bribery policy (UK Bribery Act)" },
  { key: "whistleblower_policy", category: CATEGORIES.BUSINESS_OPS, label: "Whistleblower / speak-up policy" },

  // ─── API Quality (15) ───────────────────────────────────────────────────────
  { key: "api_versioning_present", category: CATEGORIES.API_QUALITY, label: "API versioning (/v1/, /v2/ pattern)" },
  { key: "api_rate_limit_documented", category: CATEGORIES.API_QUALITY, label: "Rate limits documented" },
  { key: "api_auth_method_documented", category: CATEGORIES.API_QUALITY, label: "Auth method documented" },
  { key: "api_error_rfc7807", category: CATEGORIES.API_QUALITY, label: "RFC 7807 Problem Details error format" },
  { key: "api_pagination_documented", category: CATEGORIES.API_QUALITY, label: "Pagination documented" },
  { key: "api_filtering_sorting", category: CATEGORIES.API_QUALITY, label: "Filtering / sorting query params" },
  { key: "api_webhook_docs", category: CATEGORIES.API_QUALITY, label: "Webhook documentation" },
  { key: "api_sandbox_test_mode", category: CATEGORIES.API_QUALITY, label: "Sandbox / test mode" },
  { key: "api_sdk_packages", category: CATEGORIES.API_QUALITY, label: "SDK packages published" },
  { key: "api_versioned_changelog", category: CATEGORIES.API_QUALITY, label: "Versioned API changelog" },
  { key: "api_health_status_endpoint", category: CATEGORIES.API_QUALITY, label: "/api/health or /status endpoint" },
  { key: "api_deprecation_policy", category: CATEGORIES.API_QUALITY, label: "Deprecation policy / sunset headers" },
  { key: "api_sla_documented", category: CATEGORIES.API_QUALITY, label: "API SLA / uptime guarantee" },
  { key: "graphql_depth_limiting", category: CATEGORIES.API_QUALITY, label: "GraphQL depth / complexity limiting" },
  { key: "openapi_spec_served", category: CATEGORIES.API_QUALITY, label: "OpenAPI 3.x spec at /openapi.json" },
  { key: "api_endpoint_broken", category: CATEGORIES.API_QUALITY, label: "Referenced API endpoints don't error" },
  { key: "api_endpoint_incomplete", category: CATEGORIES.API_QUALITY, label: "API errors return structured responses" },
  { key: "api_endpoint_unverified", category: CATEGORIES.API_QUALITY, label: "No dead API references" },

  // ─── AEO & AI Discoverability (8) ───────────────────────────────────────────
  { key: "aeo_llms_txt", category: CATEGORIES.AEO, label: "llms.txt AI guidance file" },
  { key: "aeo_ai_crawlers_allowed", category: CATEGORIES.AEO, label: "AI crawlers allowed in robots.txt" },
  { key: "aeo_structured_data_valid", category: CATEGORIES.AEO, label: "Valid structured data (JSON-LD)" },
  { key: "aeo_content_server_rendered", category: CATEGORIES.AEO, label: "Content readable without JavaScript" },
  { key: "aeo_semantic_html", category: CATEGORIES.AEO, label: "Semantic HTML landmarks" },
  { key: "aeo_content_feed", category: CATEGORIES.AEO, label: "Machine-readable content feed (RSS/Atom)" },
  { key: "aeo_agent_instructions", category: CATEGORIES.AEO, label: "AI agent instructions (CLAUDE.md / AGENTS.md)" },
  { key: "aeo_repo_llms_txt", category: CATEGORIES.AEO, label: "llms.txt published in repo" },

  // ─── Backfilled to complete the catalogue (AI-era / vibe / US-privacy / store) ─
  { key: "repo_secret_keys", category: CATEGORIES.SECRETS_KEYS, label: "No exposed API keys in committed source" },
  { key: "repo_env_committed", category: CATEGORIES.SECRETS_KEYS, label: "No committed .env / secret files" },
  { key: "repo_prompt_injection_risk", category: CATEGORIES.SECRETS_KEYS, label: "No prompt-injection vectors in source" },
  { key: "store_page_live", category: CATEGORIES.STORE_LISTING, label: "App Store / Play listing is live" },
  { key: "store_preview_video", category: CATEGORIES.STORE_LISTING, label: "App preview / promo video" },
  { key: "accessibility_statement_eaa", category: CATEGORIES.ACCESSIBILITY, label: "Accessibility statement (EU Accessibility Act)" },
  { key: "ai_ai_act_disclosure", category: CATEGORIES.AI_READINESS, label: "EU AI Act transparency disclosure" },
  { key: "ai_content_safety_signal", category: CATEGORIES.AI_READINESS, label: "Content moderation / safety layer" },
  { key: "ai_cost_monitoring_script", category: CATEGORIES.AI_READINESS, label: "AI cost / usage monitoring tool" },
  { key: "ai_endpoint_rate_limited", category: CATEGORIES.AI_SAFETY, label: "AI endpoint rate-limiting signals" },
  { key: "ai_error_fallback_ui", category: CATEGORIES.AI_READINESS, label: "AI error / fallback state in UI" },
  { key: "ai_feedback_ui", category: CATEGORIES.AI_READINESS, label: "User feedback loop on AI outputs" },
  { key: "ai_has_evals", category: CATEGORIES.AI_READINESS, label: "AI evaluation / testing framework" },
  { key: "ai_has_monitoring_dep", category: CATEGORIES.AI_READINESS, label: "AI observability / LLM tracing dependency" },
  { key: "ai_has_retry_dep", category: CATEGORIES.AI_READINESS, label: "Retry / resilience library for AI API calls" },
  { key: "ai_has_validation_dep", category: CATEGORIES.AI_READINESS, label: "Output validation library for AI responses" },
  { key: "ai_human_review_signal", category: CATEGORIES.AI_READINESS, label: "Human-in-the-loop review signal" },
  { key: "ai_llm_key_not_client_exposed", category: CATEGORIES.AI_SAFETY, label: "LLM API key not in client bundle" },
  { key: "ai_output_validation", category: CATEGORIES.AI_SAFETY, label: "LLM output validated before use" },
  { key: "ai_prompt_injection_guardrail", category: CATEGORIES.AI_SAFETY, label: "Prompt-injection guardrail present" },
  { key: "ai_provider_detected", category: CATEGORIES.AI_READINESS, label: "AI provider detected on page" },
  { key: "ai_rate_limit_ui", category: CATEGORIES.AI_READINESS, label: "Rate limit / quota UI signal" },
  { key: "ai_streaming_ui", category: CATEGORIES.AI_READINESS, label: "Streaming AI response pattern" },
  { key: "ai_system_prompt_not_client_exposed", category: CATEGORIES.AI_SAFETY, label: "System prompt not shipped to the client" },
  { key: "ccpa_do_not_sell", category: CATEGORIES.LEGAL, label: "“Do Not Sell or Share My Personal Information” link (CCPA/CPRA)" },
  { key: "ccpa_notice_at_collection", category: CATEGORIES.LEGAL, label: "Notice at Collection (CCPA/CPRA)" },
  { key: "firebase_rules_locked", category: CATEGORIES.SECURITY, label: "Firebase security rules locked down" },
  { key: "no_public_secret_env", category: CATEGORIES.SECURITY, label: "No secret-looking NEXT_PUBLIC_* variables" },
  { key: "no_service_role_key_exposed", category: CATEGORIES.SECURITY, label: "No service-role / secret key in client bundle" },
  { key: "supabase_rls_enforced", category: CATEGORIES.SECURITY, label: "Supabase Row-Level Security enforced" },
  { key: "us_privacy_rights_request", category: CATEGORIES.LEGAL, label: "Consumer privacy-rights request mechanism (US state laws)" },
  { key: "us_state_optout_signals", category: CATEGORIES.LEGAL, label: "Opt-out preference signal support (GPC / “Your Privacy Choices”)" },
  { key: "vibe_ai_builder", category: CATEGORIES.VIBE_HYGIENE, label: "Builder / platform origin" },
  { key: "vibe_ai_comment_markers", category: CATEGORIES.VIBE_HYGIENE, label: "No AI-generated comment markers in page source" },
  { key: "vibe_broken_links", category: CATEGORIES.VIBE_HYGIENE, label: "Internal links resolve (no broken links)" },
  { key: "vibe_debug_mode", category: CATEGORIES.VIBE_HYGIENE, label: "No debug or development mode signals" },
  { key: "vibe_default_title", category: CATEGORIES.VIBE_HYGIENE, label: "Meaningful page title (not a framework default)" },
  { key: "vibe_empty_alt_images", category: CATEGORIES.VIBE_HYGIENE, label: "Images have descriptive alt text" },
  { key: "vibe_env_not_committed", category: CATEGORIES.VIBE_HYGIENE, label: ".env file not committed to repo" },
  { key: "vibe_hardcoded_creds_html", category: CATEGORIES.VIBE_HYGIENE, label: "No hardcoded test credentials in page HTML" },
  { key: "vibe_no_custom_404", category: CATEGORIES.VIBE_HYGIENE, label: "Custom 404 page for missing routes" },
  { key: "vibe_node_modules_not_committed", category: CATEGORIES.VIBE_HYGIENE, label: "node_modules/ not committed to repo" },
  { key: "vibe_placeholder_content", category: CATEGORIES.VIBE_HYGIENE, label: "No placeholder / filler content in production" },
  { key: "vibe_placeholder_images", category: CATEGORIES.VIBE_HYGIENE, label: "No placeholder / stock filler images" },
  { key: "spa_client_rendered", category: CATEGORIES.VIBE_HYGIENE, label: "Content is server-rendered (not a JS-only shell)" },
  { key: "wcag22_consistent_help", category: CATEGORIES.ACCESSIBILITY, label: "Consistent help mechanism (WCAG 3.3.6)" },
  { key: "wcag22_dragging_alternative", category: CATEGORIES.ACCESSIBILITY, label: "Dragging movements have an alternative (WCAG 2.5.7)" },

  // ─── Agent-emitted checks (Code Intelligence / PageSpeed / secret-scanner) ───
  { key: "branch_protection", category: CATEGORIES.CODE_QUALITY, label: "Branch protection on default branch" },
  { key: "build_time", category: CATEGORIES.INFRASTRUCTURE, label: "Average build time" },
  { key: "build_warnings", category: CATEGORIES.CODE_QUALITY, label: "Build warnings in latest deployment" },
  { key: "commit_velocity", category: CATEGORIES.CODE_QUALITY, label: "Active development velocity" },
  { key: "crux_overall", category: CATEGORIES.PERFORMANCE, label: "Real-user experience (Chrome UX Report)" },
  { key: "dependency_vulnerabilities", category: CATEGORIES.CODE_QUALITY, label: "Known dependency vulnerabilities" },
  { key: "deployment_success_rate", category: CATEGORIES.INFRASTRUCTURE, label: "Deployment success rate" },
  { key: "github_stars", category: CATEGORIES.TRUST_BRAND, label: "GitHub stars (social proof)" },
  { key: "has_license_graphql", category: CATEGORIES.CODE_QUALITY, label: "License (via GitHub)" },
  { key: "has_releases", category: CATEGORIES.CODE_QUALITY, label: "GitHub releases / version tags" },
  { key: "issue_close_rate", category: CATEGORIES.CODE_QUALITY, label: "Issue closure rate" },
  { key: "pr_review_culture", category: CATEGORIES.CODE_QUALITY, label: "Pull request review culture" },
  { key: "primary_language", category: CATEGORIES.CODE_QUALITY, label: "Primary language detected" },
  { key: "psi_accessibility", category: CATEGORIES.ACCESSIBILITY, label: "Lighthouse accessibility score" },
  { key: "psi_best_practices", category: CATEGORIES.SECURITY, label: "Lighthouse best practices score" },
  { key: "psi_cls", category: CATEGORIES.PERFORMANCE, label: "Cumulative Layout Shift (CLS)" },
  { key: "psi_fcp", category: CATEGORIES.PERFORMANCE, label: "First Contentful Paint (FCP)" },
  { key: "psi_lcp", category: CATEGORIES.PERFORMANCE, label: "Largest Contentful Paint (LCP)" },
  { key: "psi_performance", category: CATEGORIES.PERFORMANCE, label: "Lighthouse performance score (mobile)" },
  { key: "psi_seo", category: CATEGORIES.SEO, label: "Lighthouse SEO score" },
  { key: "psi_tbt", category: CATEGORIES.PERFORMANCE, label: "Total Blocking Time (TBT)" },
  { key: "repo_not_archived", category: CATEGORIES.CODE_QUALITY, label: "Repository is not archived" },

  // ── Native iOS app family (src/server/pulse-checks/ios-app.ts) ──────────────
  // Emitted only when the scanned repo is detected as a native iOS project. The
  // generic repo checks are web/JS-shaped; these cover what an App Store binary
  // is actually judged on. Android will add an `android_*` block alongside.
  { key: "ios_debug_guards", category: CATEGORIES.SECURITY, label: "Debug-only code is compile-gated (#if DEBUG)" },
  { key: "ios_release_logging", category: CATEGORIES.SECURITY, label: "Console logging disabled in Release builds" },
  { key: "ios_sensitive_payload_logging", category: CATEGORIES.SECURITY, label: "Request/response bodies not logged in Release" },
  { key: "ios_ats_arbitrary_loads", category: CATEGORIES.SECURITY, label: "App Transport Security enforced" },
  { key: "ios_cert_pinning", category: CATEGORIES.SECURITY, label: "Certificate pinning on API traffic" },
  { key: "ios_env_switcher_in_release", category: CATEGORIES.SECURITY, label: "Staging/QA environment switch excluded from Release" },
  { key: "ios_token_storage", category: CATEGORIES.SECRETS_KEYS, label: "Auth tokens stored in the Keychain" },
  { key: "ios_password_retention", category: CATEGORIES.SECRETS_KEYS, label: "User password is not persisted on device" },
  { key: "ios_keychain_accessibility", category: CATEGORIES.SECRETS_KEYS, label: "Keychain items use a restrictive accessibility class" },
  { key: "ios_privacy_manifest", category: CATEGORIES.APP_STORE, label: "Privacy manifest (PrivacyInfo.xcprivacy)" },
  { key: "ios_usage_descriptions", category: CATEGORIES.APP_STORE, label: "Permission usage descriptions present" },
  { key: "ios_aps_environment", category: CATEGORIES.APP_STORE, label: "Push notification environment" },
  { key: "ios_background_modes_declared", category: CATEGORIES.APP_STORE, label: "Declared background modes are actually used" },
  { key: "ios_encryption_declaration", category: CATEGORIES.APP_STORE, label: "Export-compliance declaration (ITSAppUsesNonExemptEncryption)" },
  { key: "ios_deployment_target", category: CATEGORIES.APP_STORE, label: "iOS deployment target is current" },
  { key: "ios_dynamic_type", category: CATEGORIES.ACCESSIBILITY, label: "Dynamic Type supported" },
  { key: "ios_accessibility_labels", category: CATEGORIES.ACCESSIBILITY, label: "VoiceOver labels on interactive elements" },
  { key: "ios_low_data_mode", category: CATEGORIES.PERFORMANCE, label: "Adapts to Low Data Mode / constrained networks" },
  { key: "ios_adaptive_streaming", category: CATEGORIES.PERFORMANCE, label: "Video uses adaptive-bitrate streaming (HLS)" },
  { key: "ios_url_cache", category: CATEGORIES.PERFORMANCE, label: "HTTP response caching configured" },
  { key: "ios_image_cache", category: CATEGORIES.PERFORMANCE, label: "Image caching in place" },
  { key: "ios_image_downsampling", category: CATEGORIES.PERFORMANCE, label: "Images downsampled before display" },
  { key: "ios_request_timeout", category: CATEGORIES.PERFORMANCE, label: "Explicit network timeouts set" },
  { key: "ios_offline_cache_fallback", category: CATEGORIES.PERFORMANCE, label: "Serves cached data when offline" },
  { key: "ios_test_target", category: CATEGORIES.CODE_QUALITY, label: "Unit test target present" },
  { key: "ios_ui_test_target", category: CATEGORIES.CODE_QUALITY, label: "UI test target present" },
  { key: "ios_dependency_pinning", category: CATEGORIES.CODE_QUALITY, label: "Dependencies pinned (Podfile.lock / Package.resolved)" },
  { key: "ios_vendored_deps_committed", category: CATEGORIES.CODE_QUALITY, label: "Dependency sources not committed" },
  { key: "ios_swiftlint", category: CATEGORIES.CODE_QUALITY, label: "Swift linter configured (SwiftLint / swift-format)" },
  { key: "ios_force_unwrap_density", category: CATEGORIES.CODE_QUALITY, label: "Force-unwrap / force-cast density" },
  { key: "ios_http_status_discarded", category: CATEGORIES.CODE_QUALITY, label: "HTTP status codes propagated to error handling" },
  { key: "ios_committed_junk", category: CATEGORIES.CODE_QUALITY, label: "No editor / OS cruft committed" },
];

/** All unique categories in display order */
/** All categories in canonical display order — derived from the SoT, never hand-listed. */
export const CHECK_CATEGORIES: readonly CheckCategory[] = ORDERED_CATEGORIES;

export function getCheckDefinition(key: string): CheckDefinition | undefined {
  return CHECKS_REGISTRY.find((c) => c.key === key);
}

export function getChecksByCategory(category: string): CheckDefinition[] {
  return CHECKS_REGISTRY.filter((c) => c.category === category);
}