import { prisma } from "@/lib/prisma";

// ── Built-in Handbook seed ───────────────────────────────────────────────────────
// A starter set of ~25 developer-facing articles — Gitwork standards and how we operate —
// so the Handbook isn't a cold start. Seeded from bootstrap.ts ONLY when the workspace has
// zero articles (see seedHandbookArticles), so it never clobbers edits: once a Handbook
// exists, this never touches it again. These are meant to be edited and grown in-app.

interface SeedArticle {
  slug: string;
  title: string;
  category: string;
  summary: string;
  tags: string[];
  featured?: boolean;
  content: string;
}

/** Join markdown lines. Written in double-quoted strings so inline `code` and ```fences``` need no escaping. */
function md(...lines: string[]): string {
  return lines.join("\n");
}

export const HANDBOOK_SEED: SeedArticle[] = [
  // ── Getting Started ──────────────────────────────────────────────────────────
  {
    slug: "welcome-how-we-work",
    title: "Welcome to Gitwork — how we work",
    category: "Getting Started",
    summary: "The operating principles behind every Gitwork build. Read this first.",
    tags: ["culture", "principles", "onboarding"],
    featured: true,
    content: md(
      "Gitwork is a design-and-build agency. We ship production software for clients on tight timelines, and our reputation rides on the quality of what we put live. This handbook is the canonical record of how we do that — read it, and keep it honest by editing it when reality changes.",
      "",
      "## The principles",
      "",
      "1. **Ship small, ship often.** A small change that's live beats a big one that's almost ready. Every merge to `main` deploys — treat that with respect, not fear.",
      "2. **Own the outcome, not the ticket.** You're responsible for the thing working in production for the client, not for closing a task.",
      "3. **Leave it better.** Every branch should leave the codebase a little cleaner than you found it. No broken windows.",
      "4. **Say the true thing.** If tests fail, say so. If you're blocked, say so today, not at standup tomorrow. Bad news early is a gift.",
      "5. **The client's trust is the product.** We move fast, but we never surprise a client with a regression, a blown deadline, or a bill they didn't expect.",
      "",
      "## What good looks like here",
      "",
      "- Clean, readable code that matches the surrounding style.",
      "- Pull requests a reviewer can understand in one pass.",
      "- Commits that read like a changelog.",
      "- Work that's demoed and verified, not just \"done\".",
      "",
      "When in doubt, ask in the team channel. Nobody here loses points for asking a good question early.",
    ),
  },
  {
    slug: "first-week-checklist",
    title: "Your first week — dev onboarding checklist",
    category: "Getting Started",
    summary: "Everything to get set up, connected and shipping in your first five days.",
    tags: ["onboarding", "checklist", "setup"],
    content: md(
      "Welcome aboard. This is the path from zero to your first merged PR.",
      "",
      "## Day 1 — access",
      "- Get your `@gitwork.co.uk` Google account and sign in to Foundry.",
      "- Join the team Slack and the client channels you've been assigned.",
      "- Get added to the `Git-Dann/docs-by-gitwork` GitHub repo.",
      "- Read [Welcome to Gitwork](/app/handbook) and the code style standards.",
      "",
      "## Day 2 — local setup",
      "- Follow [Local environment setup](/app/handbook) to run Foundry locally.",
      "- Confirm you can build (`npm run build`) and lint (`npm run lint`) clean.",
      "",
      "## Days 3–4 — first change",
      "- Pick a small starter task with your lead.",
      "- Branch, build, open a PR following [Writing great pull requests](/app/handbook).",
      "- Get it reviewed and squash-merged.",
      "",
      "## Day 5 — rhythm",
      "- Push your first AM and PM standup on the task board.",
      "- Skim the Release & Deploys and Security sections so nothing surprises you later.",
      "",
      "By the end of week one you should have shipped something small to production and know where to find answers.",
    ),
  },
  {
    slug: "local-environment-setup",
    title: "Local environment setup",
    category: "Getting Started",
    summary: "Node, environment variables, database and running the Foundry app locally.",
    tags: ["setup", "environment", "local-dev"],
    content: md(
      "Foundry is a Next.js 15 app (App Router, React 19, TypeScript) on Prisma + PostgreSQL.",
      "",
      "## Prerequisites",
      "- Node 20+ and npm.",
      "- Access to a Postgres database (a connection string for local dev).",
      "",
      "## Steps",
      "1. Clone the repo and run `npm install`.",
      "2. Create `.env.local` with at least `DATABASE_URL` and `DIRECT_URL` (see the env reference in `CLAUDE.md`), plus `ANTHROPIC_API_KEY` and `API_KEY`.",
      "3. Generate the Prisma client: `npm run db:generate`.",
      "4. Push the schema to your dev DB: `npm run db:push`.",
      "5. Start the dev server: `npm run dev` → http://localhost:3000.",
      "",
      "## Useful commands",
      "- `npm run dev` — local dev server.",
      "- `npm run build` — full production build (`prisma generate` → `db push` → `next build`).",
      "- `npm run lint` — ESLint.",
      "- `npm run db:migrate` — create a named migration.",
      "",
      "## Notes",
      "- The app is auth-gated (Google sign-in). For UI work without a DB, verify with `tsc` and `eslint` rather than the browser.",
      "- Never commit `.env.local` or any secret. See [Handling secrets & credentials](/app/handbook).",
    ),
  },

  // ── Standards ────────────────────────────────────────────────────────────────
  {
    slug: "code-style-and-conventions",
    title: "Code style & conventions",
    category: "Standards",
    summary: "TypeScript, naming, file layout and the rules that keep the codebase coherent.",
    tags: ["typescript", "style", "conventions"],
    featured: true,
    content: md(
      "Consistency beats cleverness. New code should read like the code around it.",
      "",
      "## TypeScript",
      "- Prefer explicit types on public function signatures; let inference handle locals.",
      "- Avoid `any`. If you must, leave a comment saying why and open a follow-up.",
      "- Model data with types/interfaces in `src/types/`; keep server DTOs separate from Prisma rows.",
      "",
      "## Naming",
      "- Files: kebab-case (`client-metrics.ts`). Components: PascalCase. Hooks: `useThing`.",
      "- Server modules live one-per-domain at `src/server/{domain}.ts`; agents go in `{domain}-agents/`.",
      "",
      "## Structure",
      "- API routes use `apiOk` / `apiError` / `fromError` from `src/lib/api-response.ts`.",
      "- Validate every request body with a Zod schema from `src/server/validators.ts`.",
      "- Fetch data with React Query hooks in `src/hooks/`; wrap `fetch` calls in `src/lib/api.ts`.",
      "",
      "## The bar",
      "- Match the comment density and idioms of the file you're editing.",
      "- Delete dead code rather than commenting it out.",
      "- A function that needs a paragraph to explain probably wants splitting.",
    ),
  },
  {
    slug: "definition-of-done",
    title: "Definition of Done",
    category: "Standards",
    summary: "A change isn't done when it compiles — here's the checklist that says it's done.",
    tags: ["quality", "process", "checklist"],
    content: md(
      "\"Done\" is a shared word here. It means all of the following are true.",
      "",
      "## The checklist",
      "- [ ] The change does what the task asked, verified by actually exercising it — not just \"it builds\".",
      "- [ ] `npm run build` and `npm run lint` pass clean.",
      "- [ ] New behaviour is covered by a test where the code has a testable surface.",
      "- [ ] No secrets, no debug logging, no commented-out code left behind.",
      "- [ ] The PR description explains what and why, with a screenshot for UI changes.",
      "- [ ] Any schema change is additive or has a migration plan (see the Prisma footgun doc).",
      "- [ ] Docs updated if behaviour or setup changed.",
      "",
      "## Not done",
      "- \"Works on my machine\" with no verification.",
      "- A green build but the feature was never clicked through.",
      "- A PR that leaves the reviewer guessing at intent.",
      "",
      "If you can't tick the boxes, the task is in progress — say so.",
    ),
  },
  {
    slug: "writing-great-pull-requests",
    title: "Writing great pull requests",
    category: "Standards",
    summary: "How to open a PR a reviewer can approve in one pass.",
    tags: ["pull-requests", "review", "collaboration"],
    content: md(
      "A PR is a piece of writing aimed at a reviewer. Make their job easy and yours gets easier too.",
      "",
      "## Keep it small",
      "One logical change per PR. If you're touching five unrelated things, that's five PRs. Small PRs get reviewed faster and break less.",
      "",
      "## Write the description",
      "- **What** changed, in one line.",
      "- **Why** — the problem or the ask.",
      "- **How to verify** — the steps you took, so the reviewer can repeat them.",
      "- A screenshot or clip for anything visual.",
      "",
      "## Before you request review",
      "- Re-read your own diff top to bottom. You'll catch half the comments yourself.",
      "- Make sure the build and lint pass.",
      "- Title it as a Conventional Commit (`feat:`, `fix:`, `chore:` …) — it becomes the squash-merge commit and the deploy label.",
      "",
      "## During review",
      "- Respond to every comment, even if just \"done\".",
      "- Push fixes as new commits; we squash on merge so history stays clean.",
    ),
  },
  {
    slug: "code-review-standards",
    title: "Code review standards",
    category: "Standards",
    summary: "How we review — as the author and as the reviewer. Kind, but rigorous.",
    tags: ["review", "quality", "collaboration"],
    content: md(
      "Review is how we keep quality high and share knowledge. It is not a gate to resent — it's the team thinking together.",
      "",
      "## As the reviewer",
      "- Review promptly. A PR waiting a day is a person blocked.",
      "- Look for correctness first, then clarity, then style. Don't bikeshed formatting a linter could catch.",
      "- Distinguish blocking issues from suggestions. Prefix nits with `nit:`.",
      "- Ask questions rather than issuing orders. \"What happens if this is null?\" beats \"this is wrong\".",
      "- Approve when it's good enough to ship, not when it's perfect.",
      "",
      "## As the author",
      "- Assume good faith. Comments are about the code, not you.",
      "- Push back with reasons when you disagree — reviewers are sometimes wrong.",
      "- Don't merge over unresolved blocking comments.",
      "",
      "## What we block on",
      "- Correctness bugs, security holes, data-loss risk.",
      "- Missing validation on a mutation.",
      "- Anything that would surprise a client in production.",
    ),
  },

  // ── Git & Workflow ─────────────────────────────────────────────────────────────
  {
    slug: "branching-and-commits",
    title: "Branching & commit conventions",
    category: "Git & Workflow",
    summary: "Conventional Commits, feature branches, and why we squash-merge everything.",
    tags: ["git", "commits", "conventions"],
    content: md(
      "`main` is the production branch. Every push to it deploys. We keep its history clean and readable.",
      "",
      "## Commits",
      "Use [Conventional Commits](https://www.conventionalcommits.org): `feat:`, `fix:`, `chore:`, `docs:`, `refactor:`. The message is what appears in the deploy feed — make it descriptive.",
      "",
      "```",
      "fix(tasks): scope bulk-assign picker to the client's devs",
      "feat(desk): needs-you-today = reminders + mentions + key mail",
      "```",
      "",
      "## Branches",
      "- **Small fixes** → commit directly to `main` with a clear Conventional Commit message.",
      "- **Features** → branch (`feature/...`), open a PR, let it **squash-merge**. One feature → one clean deploy line.",
      "",
      "## Squash-merge only",
      "Merge commits and rebase-merge are disabled. Each PR lands as a single commit titled with the PR title. Branches auto-delete on merge. This keeps the deploy feed a readable changelog.",
      "",
      "See [Keeping a branch in sync](/app/handbook) for how to update a feature branch without polluting history.",
    ),
  },
  {
    slug: "keeping-a-branch-in-sync",
    title: "Keeping a branch in sync",
    category: "Git & Workflow",
    summary: "Rebase onto main — never merge main into your branch and push that.",
    tags: ["git", "rebase", "workflow"],
    content: md(
      "When `main` moves ahead of your feature branch, bring your branch up to date by **rebasing**, not merging.",
      "",
      "## Do this",
      "```",
      "git fetch origin",
      "git rebase origin/main",
      "```",
      "Resolve any conflicts, then force-push your branch (`git push --force-with-lease`).",
      "",
      "## Never do this on a branch you'll merge to main",
      "```",
      "git merge main   # ← creates a \"Merge origin/main into feature/x\" commit",
      "```",
      "Those merge commits land on production as unreadable deploy lines. This was historically the single biggest source of deploy-feed noise.",
      "",
      "## Why it matters",
      "We squash-merge, so a clean, linear branch produces a clean single deploy commit. A branch littered with merge commits makes conflicts harder and history worse.",
    ),
  },
  {
    slug: "git-hygiene-and-repo-health",
    title: "Git hygiene & repo health",
    category: "Git & Workflow",
    summary: "Prune worktrees and stale branches so the object store stays healthy.",
    tags: ["git", "maintenance", "hygiene"],
    content: md(
      "Accumulated worktrees and stale local branches can corrupt the git object store over time. A little routine maintenance prevents a painful repair.",
      "",
      "## Run periodically (from the main repo, not a worktree)",
      "```",
      "git worktree prune",
      "git branch | grep claude/ | xargs git branch -D 2>/dev/null || true",
      "git gc --prune=now",
      "```",
      "",
      "## If `git gc` fails with \"bad tree object\"",
      "Don't use a shallow clone to repair — shallow packs have their own missing bases. Instead do a full mirror clone and copy the pack files:",
      "```",
      "git clone --mirror https://github.com/Git-Dann/docs-by-gitwork.git /tmp/repair",
      "cp /tmp/repair/objects/pack/*.{pack,idx} .git/objects/pack/",
      "rm -rf /tmp/repair && git gc --prune=now",
      "```",
      "",
      "Keep active branches few and delete merged ones (auto-delete handles the remote side).",
    ),
  },

  // ── Release & Deploys ──────────────────────────────────────────────────────────
  {
    slug: "release-process",
    title: "Our release process — Staging → QA → Production",
    category: "Release & Deploys",
    summary: "The three gates every change passes through before a client sees it.",
    tags: ["release", "qa", "process"],
    featured: true,
    content: md(
      "Every change moves through three gates. Skipping one is how regressions reach clients.",
      "",
      "## i. Staging",
      "Work is built and self-verified. The author exercises the actual flow — not just a green build. Screenshots or a clip go on the PR. Nothing moves forward on \"it should work\".",
      "",
      "## ii. QA",
      "A second person reviews the code and, for anything user-facing, clicks through it. We check the happy path and the obvious failure paths. Correctness, security and data-loss risk are blocking; style nits are not.",
      "",
      "## iii. Production",
      "The PR squash-merges to `main` and auto-deploys. The author watches the deploy land and does a quick smoke check on production. If it's wrong, we roll forward with a fix fast — see [Incident response](/app/handbook).",
      "",
      "## The rule",
      "> A change is only \"released\" once it's verified live. Merging is the middle of the process, not the end.",
    ),
  },
  {
    slug: "deploying-foundry",
    title: "Deploying Foundry",
    category: "Release & Deploys",
    summary: "How a push to main becomes a live deploy on the VPS.",
    tags: ["deploy", "ci-cd", "infrastructure"],
    content: md(
      "Foundry runs on a Fasthosts VPS via Docker Compose — the Next.js app container plus a self-hosted PostgreSQL container, behind a reverse proxy with a Let's Encrypt cert.",
      "",
      "## The pipeline",
      "Push to `main` triggers GitHub Actions (`.github/workflows/deploy.yml`):",
      "1. Build the image and push to GHCR.",
      "2. SSH to the VPS.",
      "3. `docker compose pull` the app + bring up the DB.",
      "4. `prisma db push` (without `--accept-data-loss`).",
      "5. Restart the app container and prune old images.",
      "",
      "End to end is roughly six minutes.",
      "",
      "## Things to know",
      "- DNS (`foundry.gitwork.co.uk`) points at the VPS via an A record managed in Squarespace.",
      "- Crons, DB backups and cert renewal are self-managed on the box (not a platform service).",
      "- Vercel still builds in parallel but is vestigial — DNS doesn't point at it.",
      "- To roll back: repoint DNS and the database URLs to the standby (kept live read-only).",
    ),
  },
  {
    slug: "database-changes-prisma-footgun",
    title: "Database changes & the Prisma db-push footgun",
    category: "Release & Deploys",
    summary: "Why a \"purely additive\" schema change can still fail to reach production.",
    tags: ["prisma", "database", "schema", "gotcha"],
    content: md(
      "The deploy runs `prisma db push` **without** `--accept-data-loss` — deliberately, so no branch can silently mutate the shared production database. This has a sharp edge worth understanding.",
      "",
      "## The footgun",
      "Prisma's safety check is **all-or-nothing per push**. If the schema diff contains *anything* Prisma deems potentially data-losing — even a removed column on an unrelated table — the **whole sync is skipped**, additive parts included. So a \"purely additive\" PR can fail to apply to prod if the schema also carries an unrelated pending drop.",
      "",
      "The Prisma client generates fine and TypeScript compiles, but the live DB never gets the column → `upsert()` calls fail at runtime with *\"the column does not exist\"*.",
      "",
      "## Before merging a schema change",
      "1. `git diff origin/main -- prisma/schema.prisma` — look for anything dropped (columns, tables, enum values, indices, FKs).",
      "2. If everything is purely additive and main matches prod, the build applies it cleanly.",
      "3. If there's ANY drop/rename: apply it manually first (`prisma db push --accept-data-loss` against prod, verified), or switch the PR to proper migrations (`migrate deploy`).",
      "",
      "Keep migrations additive whenever you can — new nullable columns and new tables are always safe.",
    ),
  },

  // ── Frontend ─────────────────────────────────────────────────────────────────
  {
    slug: "frontend-standards",
    title: "Frontend standards",
    category: "Frontend",
    summary: "React and Next.js patterns we hold to across the app.",
    tags: ["react", "nextjs", "frontend"],
    content: md(
      "Foundry is Next.js App Router + React 19. A few patterns keep the frontend predictable.",
      "",
      "## Data",
      "- Fetch with TanStack React Query hooks in `src/hooks/`. Never fetch ad-hoc in a component.",
      "- Keep query keys stable and invalidate them on mutation `onSuccess`.",
      "- Server components fetch directly; client components (`\"use client\"`) use hooks.",
      "",
      "## Components",
      "- One component, one job. Lift shared UI into `src/components/ui/`.",
      "- Use the shared `Button`, `Modal`, `toast` primitives — never hand-roll a fourth variant.",
      "- Guard rendering on permissions with `usePermissions()`, but remember the server is authoritative.",
      "",
      "## Images",
      "- Use `next/image` for static assets in `public/`.",
      "- Raw `<img>` only for dynamic/user-uploaded images, with the eslint-disable comment.",
      "",
      "## Accessibility",
      "- Real buttons for actions, real links for navigation.",
      "- Every interactive control needs an accessible label.",
      "",
      "For anything visual, build against the [Foundry design system](/app/handbook).",
    ),
  },
  {
    slug: "building-on-the-design-system",
    title: "Building on the Foundry design system",
    category: "Design System",
    summary: "The widget signature, tokens, and the rules that make the app feel like one system.",
    tags: ["design-system", "ui", "brand"],
    featured: true,
    content: md(
      "The design system is documented in `DESIGN.md` — treat it as canonical. The short version:",
      "",
      "## The brand signature",
      "Every dashboard panel and data card opens with a numbered monospace header — `01 // WIDGET NAME` — in JetBrains Mono. This is THE Foundry signature. Never skip it, never restyle it.",
      "",
      "## Type",
      "- **Inter** for all UI: labels, body, buttons.",
      "- **DM Serif Display** for large stat figures and editorial hero text only.",
      "- **JetBrains Mono** for widget headers, timestamps and data-unit labels.",
      "",
      "## Colour & shape",
      "- Gitwork Blue (`--brand-*`) on all interactive elements and active states. No accent colours outside the blue family and the semantic set.",
      "- Cards use `--surface-0` faces with hairline borders (`--border-2`) — no drop shadows on flat cards.",
      "- 6px radius on controls, 10px on cards. `rounded-full` is for 6px status dots only — never pills.",
      "",
      "## Tokens, always",
      "Use CSS variables (`--text-*`, `--surface-*`, `--border-*`, `--brand-*`) so dark mode works. Never hardcode `#hex` for text on the navy shell — it goes invisible.",
    ),
  },
  {
    slug: "responsive-and-mobile-standards",
    title: "Responsive & mobile standards",
    category: "Frontend",
    summary: "How we approach breakpoints and mobile without siloing fixes to one screen.",
    tags: ["responsive", "mobile", "css"],
    content: md(
      "Responsive work is a whole-system concern, not a per-screen patch. The `docs/mobile-playbook.md` is the mandatory operating standard — read it before any layout work.",
      "",
      "## Principles",
      "- Fix responsive issues at the shared primitive, not the one screen where you noticed it. A one-off fix usually means five other screens are still broken.",
      "- Respect the documented breakpoints (mobile < 640, tablet 640–1023, desktop 1024–1279, wide ≥ 1280).",
      "- Content that can't shrink (tables, diagrams, wide code) scrolls inside its own `overflow-x-auto` container — the page body never scrolls sideways.",
      "",
      "## Verify",
      "- Test at mobile, tablet and desktop widths, and in dark mode.",
      "- Use relative units and flex/grid; `max-width: 100%` on media.",
      "",
      "## Blast radius",
      "Before shipping a layout change, ask what else uses this component. If the answer is \"lots\", verify a couple of those too.",
    ),
  },

  // ── Backend ─────────────────────────────────────────────────────────────────
  {
    slug: "api-route-conventions",
    title: "API route conventions",
    category: "Backend",
    summary: "The shape every /api route follows — responses, validation, params and auth.",
    tags: ["api", "backend", "conventions"],
    content: md(
      "Every route under `src/app/api/` follows the same shape so they're predictable to read and safe by default.",
      "",
      "## Responses",
      "Always use the helpers from `src/lib/api-response.ts`:",
      "```",
      "return apiOk(data);",
      "return apiError(\"Not found\", 404);",
      "return fromError(error);   // in the catch",
      "```",
      "",
      "## Validation",
      "Parse every request body with a Zod schema from `src/server/validators.ts`. Never trust the client shape.",
      "",
      "## Params",
      "In Next.js 15 route params arrive as a Promise — always `await params`:",
      "```",
      "const { id } = await params;",
      "```",
      "",
      "## Auth & gating",
      "- All `/api/` routes except `/api/health` are gated by the `API_KEY` middleware.",
      "- For per-user checks, resolve the effective user and `assertCan(user, canDoThing, \"…\")`.",
      "- Gate sensitive fields server-side — blank them in the payload, don't just hide them in the UI.",
    ),
  },
  {
    slug: "data-and-prisma-conventions",
    title: "Data & Prisma conventions",
    category: "Backend",
    summary: "How we model data, scope queries, and keep serialization clean.",
    tags: ["prisma", "database", "backend"],
    content: md(
      "Prisma is our ORM against PostgreSQL. A few conventions keep data access safe and tidy.",
      "",
      "## Access",
      "- Import the singleton from `src/lib/prisma.ts` — never construct a client.",
      "- Scope every query to the workspace (and to the user's assigned clients where relevant). Multi-tenant leaks are serious.",
      "",
      "## Serialization",
      "- Don't return raw Prisma rows to the client. Map them to a DTO in the server module and convert `Date` → ISO string.",
      "- Keep the DTO type next to its serializer so client and server share one source of truth.",
      "",
      "## Schema changes",
      "- Prefer additive changes (new nullable columns, new tables) — they apply cleanly on deploy.",
      "- Read [the Prisma db-push footgun](/app/handbook) before any drop or rename.",
      "- Index the columns you filter and sort on.",
      "",
      "## Performance",
      "Watch for N+1 queries. Batch with `findMany` + `include`, or compute aggregates in one grouped query.",
    ),
  },
  {
    slug: "working-with-ai-providers",
    title: "Working with AI providers",
    category: "Backend",
    summary: "How we call models in Foundry — never hardcode a model name.",
    tags: ["ai", "anthropic", "backend"],
    content: md(
      "Foundry uses multiple AI providers (Anthropic by default, OpenAI/Gemini optional), configurable per workspace.",
      "",
      "## The rules",
      "- **Never hardcode a model name.** Resolve it from workspace settings via the shared resolver (`resolveAiConfig` in `src/server/ai-provider.ts`, or `getModelForTask()` for Pulse).",
      "- Reuse `completeText` / `parseJsonObject` from `ai-provider.ts` rather than re-implementing provider calls.",
      "- Default new work to the latest, most capable Claude models.",
      "",
      "## Reliability",
      "- Model calls fail and time out. Always have a fallback path — a checks-only result, a cached value, or a clear error to the user.",
      "- Keep long-running AI work off the request path; persist partial results so a failure still leaves something usable.",
      "",
      "## Cost & safety",
      "- Don't send secrets or full client datasets into a prompt without a reason.",
      "- Cache where the same input recurs.",
    ),
  },

  // ── Security ─────────────────────────────────────────────────────────────────
  {
    slug: "security-baseline",
    title: "Security baseline",
    category: "Security",
    summary: "The non-negotiables: auth, gating, input validation and least privilege.",
    tags: ["security", "auth", "baseline"],
    featured: true,
    content: md(
      "Security isn't a phase — it's a default we hold on every change.",
      "",
      "## Auth & access",
      "- Every `/api/` route (except `/api/health`) is gated by the `API_KEY` middleware; browser traffic carries an HttpOnly session cookie.",
      "- Gate by role/permission server-side with `assertCan`. UI hiding is cosmetic — the server must blank or reject.",
      "- Scope every query to the workspace and, for restricted users, to their assigned clients.",
      "",
      "## Input",
      "- Validate every mutation body with Zod. Reject unexpected shapes.",
      "- Sanitize any user-supplied URL or HTML. We render markdown to React elements, never `dangerouslySetInnerHTML` with untrusted input.",
      "",
      "## Least privilege",
      "- New capabilities default OFF. Grant them explicitly, per person.",
      "- High-risk actions (public sharing, fix-agent PRs, bulk delete) require their own permission and are flagged.",
      "",
      "## When you find a hole",
      "Fix it or flag it immediately — don't sit on it. If it's live, treat it as an incident.",
    ),
  },
  {
    slug: "handling-secrets-and-credentials",
    title: "Handling secrets & credentials",
    category: "Security",
    summary: "Where secrets live, how they're stored, and what never goes in git or Slack.",
    tags: ["security", "secrets", "credentials"],
    content: md(
      "Secrets leaking is one of the fastest ways to lose a client's trust. Handle them with care.",
      "",
      "## Where secrets live",
      "- Production env lives in the VPS `.env`, loaded by Docker Compose — not in the repo.",
      "- Local secrets go in `.env.local`, which is git-ignored. Never commit it.",
      "",
      "## Rules",
      "- Never paste a live secret into Slack, a PR, a commit message, or a ticket. If one is exposed, rotate it.",
      "- Client data encrypted at rest (e.g. onboarding bank details via AES-256-GCM) depends on `ENCRYPTION_KEY` staying stable — never regenerate it casually or encrypted data becomes unreadable.",
      "- API tokens for client integrations are stored per-connection server-side, never in `localStorage`.",
      "",
      "## Access",
      "Request the minimum access you need. Prefer per-user OAuth over shared credentials. When someone leaves a project, revoke promptly.",
    ),
  },

  // ── Process ────────────────────────────────────────────────────────────────────
  {
    slug: "standups-and-communication",
    title: "Daily standups & communication",
    category: "Process",
    summary: "How we run standups, keep clients informed, and communicate async.",
    tags: ["communication", "standups", "process"],
    content: md(
      "We're a distributed team on tight timelines. Good communication is what makes that work.",
      "",
      "## Daily standups",
      "- Push an **AM \"Doing\"** on the task board — what you're working on today.",
      "- Push a **PM \"Done\"** — what actually shipped. On Mondays add a \"this week\" note.",
      "- These roll up to the client channels automatically, so clients see momentum without a meeting.",
      "",
      "## Async first",
      "- Default to writing things down where the team can find them later (channel > DM).",
      "- Make requests actionable: what you need, from whom, by when.",
      "- Over-communicate blockers. \"I'm stuck on X\" today beats a missed deadline tomorrow.",
      "",
      "## With clients",
      "- Keep the tone calm and specific. Under-promise, over-deliver.",
      "- Never surprise a client. Flag slips and risks early, with a plan attached.",
    ),
  },
  {
    slug: "scoping-and-estimation",
    title: "How we scope & estimate work",
    category: "Process",
    summary: "Turning a vague ask into a plan you can commit to.",
    tags: ["estimation", "scoping", "planning"],
    content: md(
      "Estimates are promises to a client. We make them carefully and honestly.",
      "",
      "## Scope first",
      "- Get clear on the outcome, not the feature list. What does \"done\" look like for the client?",
      "- Break work into pieces you can each ship independently.",
      "- Name the unknowns explicitly — the parts you'd need to spike before you'd trust an estimate.",
      "",
      "## Estimate honestly",
      "- Estimate the whole thing: build, review, QA, deploy, and the inevitable fixes — not just the happy-path coding.",
      "- Pad for the unknowns you named. If you can't estimate a piece, timebox a spike instead of guessing.",
      "- Prefer ranges and assumptions over false precision.",
      "",
      "## Commit and track",
      "- Once scoped, put it on the board as feature blocks and tasks.",
      "- If reality diverges from the estimate, raise it early — don't quietly absorb the slip.",
    ),
  },

  // ── Playbooks ──────────────────────────────────────────────────────────────────
  {
    slug: "incident-response",
    title: "Incident response — when prod breaks",
    category: "Playbooks",
    summary: "The calm, fast path from \"production is down\" to \"fixed and understood\".",
    tags: ["incident", "production", "playbook"],
    content: md(
      "Production will break sometimes. What matters is how fast and how calmly we handle it.",
      "",
      "## 1. Assess",
      "- What's the impact — who's affected, how badly? A broken admin page is not a down site.",
      "- Post in the team channel: what's happening, who's on it. One owner, coordinating.",
      "",
      "## 2. Stabilise",
      "- If a recent deploy caused it, the fastest fix is usually to roll forward with a small targeted fix, or roll back.",
      "- If a schema-using route is crashing because a column never applied, apply the schema to prod manually (see the Prisma footgun doc) — that's often a ten-second fix.",
      "",
      "## 3. Fix & verify",
      "- Ship the fix through the normal gates, but fast. Verify on production, not just locally.",
      "",
      "## 4. Learn",
      "- Write down what happened and why, briefly. Add a check or a doc so it can't happen the same way twice.",
      "",
      "> Blameless. We fix the system, not the person.",
    ),
  },
  {
    slug: "client-handover-checklist",
    title: "Client handover checklist",
    category: "Playbooks",
    summary: "What we hand over when a project ships, so the client is genuinely self-sufficient.",
    tags: ["handover", "client", "playbook"],
    content: md(
      "A clean handover is the difference between a client who trusts us and one who feels stranded.",
      "",
      "## Access",
      "- [ ] Client owns their repos, hosting, domains and third-party accounts (not us, on their behalf).",
      "- [ ] Credentials transferred securely and our temporary access revoked where appropriate.",
      "",
      "## Documentation",
      "- [ ] A clear README / runbook: how to run, build, deploy and configure.",
      "- [ ] Architecture overview and the key decisions behind it.",
      "- [ ] Known limitations and any deliberate trade-offs, written down.",
      "",
      "## Operations",
      "- [ ] Monitoring and backups in place and explained.",
      "- [ ] A named contact and an agreed support/aftercare arrangement.",
      "",
      "## The walkthrough",
      "- [ ] A live handover session, recorded, covering the above.",
      "",
      "Handover starts at the beginning of a project, not the end — build it so it's handoverable.",
    ),
  },
];

/**
 * Seed the starter Handbook articles — ONLY when the workspace has none yet. This makes the
 * module land populated on first boot after deploy, but never touches an existing Handbook, so
 * edits and deletions are preserved. Idempotent and safe to call on every boot.
 */
export async function seedHandbookArticles(workspaceId: string): Promise<number> {
  const existing = await prisma.handbookArticle.count({ where: { workspaceId } });
  if (existing > 0) return 0;

  const now = new Date();
  const result = await prisma.handbookArticle.createMany({
    data: HANDBOOK_SEED.map((a, i) => {
      const words = a.content.trim().split(/\s+/).filter(Boolean).length;
      return {
        workspaceId,
        title: a.title,
        slug: a.slug,
        summary: a.summary,
        category: a.category,
        content: a.content,
        tags: a.tags,
        status: "PUBLISHED" as const,
        featured: a.featured ?? false,
        readMinutes: Math.max(1, Math.round(words / 200)),
        orderKey: i,
        publishedAt: now,
      };
    }),
    skipDuplicates: true,
  });
  return result.count;
}
