import { prisma } from "@/lib/prisma";

// ── Built-in Handbook seed ───────────────────────────────────────────────────────
// The shipped starter set of developer-facing articles — Gitwork standards and how we operate.
// Seeded from bootstrap.ts and VERSION-GATED (see seedHandbookArticles + HANDBOOK_SEED_VERSION):
// when a workspace's stored handbookSeedVersion is below the current one, the built-in articles
// are re-upserted by slug once, then the version advances. This ships improved built-in content on
// deploy WITHOUT clobbering members' own edits between version bumps. Articles are meant to be
// edited and grown in-app; new hand-authored articles (different slugs) are never touched.

// Bump this whenever the built-in content below is revised so the change reaches existing
// workspaces on the next deploy. v1 = initial skeletons; v2 = fully fleshed-out articles.
export const HANDBOOK_SEED_VERSION = 2;

interface SeedArticle {
  slug: string;
  title: string;
  category: string;
  summary: string;
  tags: string[];
  featured?: boolean;
  content: string;
}

/** Join markdown lines. Written in double-quoted strings so inline `code` and ```fences``` need no escaping. */
function md(...lines: string[]): string {
  return lines.join("\n");
}

export const HANDBOOK_SEED: SeedArticle[] = [
  // ── Getting Started ──────────────────────────────────────────────────────────
  {
    slug: "welcome-how-we-work",
    title: "Welcome to Gitwork — how we work",
    category: "Getting Started",
    summary: "The operating philosophy behind every Gitwork build. Start here — everything else is downstream of this.",
    tags: ["culture", "principles", "onboarding"],
    featured: true,
    content: md(
      "Gitwork is a design-and-build agency. We take clients from an idea, a Figma file, or a struggling MVP to production software that works — on timelines that are always tighter than anyone would like. Our reputation isn't built on what we can demo; it's built on what stays up, stable and cared-for, months after we've shipped it.",
      "",
      "This handbook is the canonical record of how we do that. It's a living document — when reality diverges from what's written here, fix the doc, don't quietly work around it.",
      "",
      "## The five principles",
      "",
      "**1. Ship small, ship often.** A small change that's live beats a big one that's almost ready. Every merge to `main` deploys to production in about six minutes — that's a feature, not a hazard. It means feedback is fast and blast radius is small. Break work into pieces you can ship independently.",
      "",
      "**2. Own the outcome, not the ticket.** You are responsible for the thing working in production for the client — not for moving a card to Done. \"The API returns 200\" is not the goal; \"the client's user completed the flow\" is.",
      "",
      "**3. Leave it better.** Every branch should leave the codebase slightly cleaner than you found it. No broken windows — a small mess tolerated becomes a big mess assumed. If you touch a file with a rough edge and fixing it is cheap, fix it.",
      "",
      "**4. Say the true thing, early.** If tests fail, say so. If you're blocked, say so today — not at tomorrow's standup. If an estimate is slipping, flag it while there's still time to react. Bad news early is a gift; bad news late is a betrayal of trust.",
      "",
      "**5. The client's trust is the product.** We move fast, but we never surprise a client with a regression, a blown deadline, or a bill they didn't see coming. Under-promise, over-deliver, and communicate like an adult.",
      "",
      "## What \"good\" looks like here",
      "",
      "| Signal | Good | Not good |",
      "|---|---|---|",
      "| A pull request | One idea, reviewable in a single pass, verified | A 40-file grab-bag \"should work\" |",
      "| A commit message | Reads like a changelog line | `wip`, `fix stuff`, `.` |",
      "| \"Done\" | Demoed and verified in production | Compiles on my machine |",
      "| A blocker | Raised the moment you hit it | Discovered at the deadline |",
      "",
      "## When you're unsure",
      "",
      "> Ask early, ask specifically, ask in the open channel. Nobody here loses points for a good question asked on day one. People lose trust for a wrong assumption shipped in week three.",
      "",
      "Read the rest of the **Getting Started** section next, then skim **Standards** and **Release & Deploys** before your first PR.",
    ),
  },
  {
    slug: "first-week-checklist",
    title: "Your first week — dev onboarding checklist",
    category: "Getting Started",
    summary: "The exact path from zero access to your first merged, deployed pull request — day by day.",
    tags: ["onboarding", "checklist", "setup"],
    content: md(
      "Welcome aboard. The goal of week one is simple: **ship one small thing to production and know where to find answers.** Everything below serves that.",
      "",
      "## Day 1 — access & orientation",
      "- [ ] `@gitwork.co.uk` Google account, and you can sign in to Foundry (`foundry.gitwork.co.uk`).",
      "- [ ] Added to Slack — the team channel plus any client channels for work you're assigned.",
      "- [ ] Collaborator on the `Git-Dann/docs-by-gitwork` GitHub repo.",
      "- [ ] Read [Welcome to Gitwork](/app/handbook) and [Code style & conventions](/app/handbook).",
      "- [ ] Meet your lead; confirm which clients you're assigned to (this scopes what you see in Portal, Care and the task board).",
      "",
      "## Day 2 — local environment",
      "- [ ] Follow [Local environment setup](/app/handbook) end to end.",
      "- [ ] `npm run build` and `npm run lint` both pass clean on a fresh clone.",
      "- [ ] You can run the app locally and sign in.",
      "",
      "## Days 3–4 — your first change",
      "- [ ] Pick a genuinely small starter task with your lead (a copy fix, a small UI tweak — something low-risk).",
      "- [ ] Branch, build, self-verify by actually clicking through it.",
      "- [ ] Open a PR following [Writing great pull requests](/app/handbook) — small, described, with a screenshot.",
      "- [ ] Get it reviewed, address comments, and squash-merge it.",
      "- [ ] Watch it deploy and confirm it live. **That's the whole loop — you've now done the thing.**",
      "",
      "## Day 5 — settle into the rhythm",
      "- [ ] Push your first **AM \"Doing\"** and **PM \"Done\"** standup on the task board.",
      "- [ ] Skim [Our release process](/app/handbook), [Security baseline](/app/handbook) and [Daily standups & communication](/app/handbook) so nothing surprises you.",
      "- [ ] Note anything in this handbook that was wrong or missing — and fix it. Improving the onboarding docs is a perfect first contribution.",
      "",
      "## What to optimise for",
      "> Speed of your first real loop matters more than the size of your first change. A tiny thing shipped and verified in three days teaches you the whole pipeline. A big thing half-built in three days teaches you nothing yet.",
    ),
  },
  {
    slug: "local-environment-setup",
    title: "Local environment setup",
    category: "Getting Started",
    summary: "Node, environment variables, database and running Foundry locally — plus the commands you'll live in.",
    tags: ["setup", "environment", "local-dev"],
    content: md(
      "Foundry is a **Next.js 15** app (App Router, React 19, TypeScript) on **Prisma + PostgreSQL**, styled with **Tailwind CSS v4**. Here's how to get it running.",
      "",
      "## Prerequisites",
      "- **Node 20+** and npm.",
      "- Access to a **PostgreSQL** database for local dev (a local Postgres, or a dev branch connection string). The DB needs the `pgvector` extension for Care's semantic search.",
      "",
      "## Setup",
      "```bash",
      "git clone https://github.com/Git-Dann/docs-by-gitwork.git",
      "cd docs-by-gitwork",
      "npm install",
      "cp .env.local.example .env.local   # then fill it in (see below)",
      "npm run db:generate                # generate the Prisma client",
      "npm run db:push                    # sync the schema to your dev DB",
      "npm run dev                        # http://localhost:3000",
      "```",
      "",
      "## Environment variables",
      "At minimum, `.env.local` needs:",
      "",
      "| Var | What it's for |",
      "|---|---|",
      "| `DATABASE_URL` / `DIRECT_URL` | Postgres connection (both required by Prisma) |",
      "| `ANTHROPIC_API_KEY` | The default AI provider |",
      "| `API_KEY` | Gates all `/api/` routes (except `/api/health`) |",
      "| `ENCRYPTION_KEY` | AES-256-GCM for encrypted client data — must match prod to read prod data |",
      "",
      "The full reference lives in `CLAUDE.md`. **Never commit `.env.local`** — see [Handling secrets & credentials](/app/handbook).",
      "",
      "## The commands you'll live in",
      "```bash",
      "npm run dev          # local dev server (hot reload)",
      "npm run build        # full prod build: prisma generate → db push → next build",
      "npm run lint         # ESLint — must pass before you push",
      "npm run db:push      # push schema changes to your DB (additive-safe)",
      "npm run db:migrate   # create a named migration when you need one",
      "npx tsc --noEmit     # typecheck the whole project",
      "```",
      "",
      "## Verifying without the browser",
      "The app is auth-gated (Google sign-in) and needs a DB, so for a lot of UI work the fastest reliable check is **`npx tsc --noEmit` + `npm run lint`**, not spinning up the full stack. Reach for the running app when behaviour genuinely needs to be exercised.",
      "",
      "## Troubleshooting",
      "- **`handbookArticle does not exist` / any missing model** → your generated client is stale: `npm run db:generate`.",
      "- **Type errors after pulling** → regenerate the client; schema may have changed.",
      "- **Build fails on `db push`** → a data-losing schema diff is being refused. Read [the Prisma db-push footgun](/app/handbook).",
    ),
  },

  // ── Standards ────────────────────────────────────────────────────────────────
  {
    slug: "code-style-and-conventions",
    title: "Code style & conventions",
    category: "Standards",
    summary: "TypeScript, naming, structure and the house rules that keep a large codebase coherent.",
    tags: ["typescript", "style", "conventions"],
    featured: true,
    content: md(
      "Consistency beats cleverness. New code should read like the code already around it — a reviewer should not be able to tell which of us wrote a given file. These are the conventions that make that possible.",
      "",
      "## TypeScript",
      "- **Type the boundaries, infer the middle.** Explicit types on exported function signatures and public data shapes; let inference handle locals.",
      "- **Avoid `any`.** It switches off the type checker exactly where bugs hide. If you genuinely must, leave a comment saying why and open a follow-up. (We carry some legacy `any` — don't add to it.)",
      "- **Model data in `src/types/`.** Keep server DTOs distinct from Prisma row types — never leak a raw Prisma row to the client.",
      "- **Prefer `type` unions and narrow discriminated unions** over loose objects with optional everything.",
      "",
      "## Naming",
      "| Thing | Convention | Example |",
      "|---|---|---|",
      "| Files | kebab-case | `client-metrics.ts` |",
      "| Components | PascalCase | `HandbookLibrary` |",
      "| Hooks | `useThing` | `useHandbookList` |",
      "| Server modules | one per domain | `src/server/handbook.ts` |",
      "| Agents | in `{domain}-agents/` | `pulse-agents/orchestrator.ts` |",
      "",
      "## Structure & the house helpers",
      "Reach for the established primitives instead of rolling your own:",
      "- API routes return via `apiOk` / `apiError` / `fromError` (`src/lib/api-response.ts`).",
      "- Every mutation body is parsed by a Zod schema from `src/server/validators.ts`.",
      "- Data is fetched with React Query hooks in `src/hooks/`; `fetch` calls are wrapped in `src/lib/api.ts`.",
      "- Conditional classnames use `cn()` from `src/lib/format.ts`.",
      "- UI reuses `Button`, `Modal`, `toast` from `src/components/ui/` — don't hand-roll a fourth button.",
      "",
      "## The bar for a diff",
      "```ts",
      "// Good: reads like the file, one job, typed at the edge",
      "export function estimateReadMinutes(content: string): number | null {",
      "  const words = content.trim().split(/\\s+/).filter(Boolean).length;",
      "  return words === 0 ? null : Math.max(1, Math.round(words / 200));",
      "}",
      "```",
      "",
      "- Match the comment density and idioms of the file you're editing.",
      "- Delete dead code rather than commenting it out — git remembers it.",
      "- A function that needs a paragraph of prose to explain probably wants splitting.",
      "",
      "> Formatting is not a matter of taste here — the linter is the referee. If `npm run lint` is happy, move on; don't relitigate style in review.",
    ),
  },
  {
    slug: "definition-of-done",
    title: "Definition of Done",
    category: "Standards",
    summary: "\"Done\" is a shared word with a precise meaning. Here's the bar, and what falls short of it.",
    tags: ["quality", "process", "checklist"],
    content: md(
      "\"Done\" is one of the most dangerous words in software because everyone hears something different. At Gitwork it has a precise, shared meaning. A change is done when **all** of the following are true.",
      "",
      "## The checklist",
      "- [ ] It **does what the task asked**, verified by actually exercising the behaviour — not \"it builds\".",
      "- [ ] `npm run build` and `npm run lint` pass clean.",
      "- [ ] `npx tsc --noEmit` introduces no new type errors.",
      "- [ ] New behaviour has a **test** where there's a testable surface (logic, edge cases, a bug you're fixing).",
      "- [ ] No secrets, no stray `console.log`, no commented-out code, no `TODO` without a ticket.",
      "- [ ] The **PR describes what and why**, with a screenshot or clip for anything visual.",
      "- [ ] Any **schema change is additive** or carries a migration plan (see [the Prisma footgun](/app/handbook)).",
      "- [ ] **Docs updated** if behaviour, setup or an interface changed — including this handbook.",
      "- [ ] Verified **in production** after deploy, not just locally.",
      "",
      "## Levels of done",
      "It helps to name where a change actually is:",
      "",
      "| State | Meaning |",
      "|---|---|",
      "| In progress | Code exists; not yet verified |",
      "| Code complete | Builds, lints, reviewed — but unproven in the real flow |",
      "| **Done** | Verified working in production; the checklist is fully ticked |",
      "",
      "Only the last one is \"done\". If you're at \"code complete\", say that — it's honest and useful.",
      "",
      "## Not done (however tempting to call it that)",
      "- \"Works on my machine\" with no verification of the actual flow.",
      "- A green build where the feature was never clicked through.",
      "- A PR that leaves the reviewer reverse-engineering your intent.",
      "- \"I'll add the test in a follow-up\" for logic that needed one.",
      "",
      "> The Definition of Done exists so that when you say \"done\", a teammate or a client can act on it without checking your work. That's the whole point — protect the word.",
    ),
  },
  {
    slug: "writing-great-pull-requests",
    title: "Writing great pull requests",
    category: "Standards",
    summary: "A PR is a piece of writing aimed at a reviewer. Make it small, make it clear, and reviews get fast.",
    tags: ["pull-requests", "review", "collaboration"],
    content: md(
      "A pull request is not a code dump — it's a short piece of persuasive writing aimed at a reviewer, arguing \"this change is correct and safe to ship\". The better you make that argument, the faster it merges.",
      "",
      "## Keep it small",
      "One logical change per PR. If you're touching five unrelated things, that's five PRs. Small PRs:",
      "- get reviewed in minutes, not days,",
      "- are far easier to reason about and revert,",
      "- produce clean, single-purpose deploy lines (we squash-merge).",
      "",
      "If a feature is genuinely large, stack it: land the schema, then the server, then the UI, each reviewable on its own.",
      "",
      "## Write the description",
      "A good PR body answers four questions:",
      "```md",
      "## What",
      "One line: what this changes.",
      "",
      "## Why",
      "The problem or the client ask driving it.",
      "",
      "## How to verify",
      "The exact steps you took, so the reviewer can repeat them.",
      "",
      "## Screenshots",
      "Before / after for anything visual.",
      "```",
      "",
      "## Title it as a Conventional Commit",
      "The title becomes the squash-merge commit and the **deploy-feed label**, so make it descriptive:",
      "```",
      "feat(handbook): super-admin developer knowledgebase + seed articles",
      "fix(tasks): scope bulk-assign picker to the client's devs",
      "```",
      "",
      "## Before you hit \"request review\"",
      "- **Re-read your own diff, top to bottom.** You'll catch half the review comments yourself.",
      "- Confirm build + lint pass.",
      "- Remove debug logging and dead code.",
      "- Check you didn't commit a secret or a `.env` file.",
      "",
      "## During review",
      "- Respond to every comment, even just \"done\".",
      "- Push fixes as new commits — don't force-push mid-review; we squash on merge so history stays clean anyway.",
      "- Disagree with reasons, not silence. Reviewers are sometimes wrong.",
    ),
  },
  {
    slug: "code-review-standards",
    title: "Code review standards",
    category: "Standards",
    summary: "How we review — as author and as reviewer. Kind, prompt, rigorous. It's the team thinking together.",
    tags: ["review", "quality", "collaboration"],
    content: md(
      "Review is where quality is defended and knowledge spreads. It is not a hazing ritual or a rubber stamp — it's the team thinking together about a change before it reaches a client.",
      "",
      "## As the reviewer",
      "- **Review promptly.** A PR sitting for a day is a teammate blocked and a context lost. Aim for same-day.",
      "- **Order of attention:** correctness → clarity → style. Don't bikeshed formatting a linter already enforces.",
      "- **Separate blocking from optional.** Prefix non-blocking thoughts with `nit:` so the author knows what actually gates merge.",
      "- **Ask, don't decree.** \"What happens if this is null?\" invites a fix and a conversation; \"this is wrong\" invites defensiveness.",
      "- **Approve at good-enough-to-ship, not perfect.** Perfect is a follow-up PR.",
      "- **Teach in comments.** A link or a one-line why turns a correction into learning.",
      "",
      "## As the author",
      "- Assume good faith — comments are about the code, not you.",
      "- Make the reviewer's job easy: small PR, clear description (see [Writing great PRs](/app/handbook)).",
      "- Never merge over an unresolved **blocking** comment.",
      "",
      "## What we block on",
      "| Block | Don't block |",
      "|---|---|",
      "| Correctness bugs, wrong logic | Naming preferences a linter allows |",
      "| Security holes, missing auth/validation | Whitespace / formatting |",
      "| Data-loss risk (see the Prisma footgun) | \"I'd have structured it differently\" |",
      "| Anything that would surprise a client in prod | Optional refactors better done later |",
      "",
      "## The mindset",
      "> Review the code you got, not the code you'd have written. If it's correct, clear and safe, approve it — even if your instincts would have taken a different path.",
    ),
  },

  // ── Git & Workflow ─────────────────────────────────────────────────────────────
  {
    slug: "branching-and-commits",
    title: "Branching & commit conventions",
    category: "Git & Workflow",
    summary: "Conventional Commits, feature branches, and why every merge is a squash-merge.",
    tags: ["git", "commits", "conventions"],
    content: md(
      "`main` is the production branch. **Every push to it deploys.** That single fact drives all of our git conventions — we keep `main`'s history clean, linear and readable, because it *is* the deploy feed and the changelog.",
      "",
      "## Commit messages — Conventional Commits",
      "Use a [Conventional Commit](https://www.conventionalcommits.org) type prefix. The message is what shows in the deploy feed, so make it descriptive and scoped:",
      "```",
      "feat(desk): needs-you-today = reminders + mentions + key mail",
      "fix(wiki): clamp Add New menu to the viewport",
      "chore(deps): bump prisma to 6.16",
      "docs(handbook): flesh out the release process article",
      "```",
      "",
      "| Prefix | Use for |",
      "|---|---|",
      "| `feat` | A new capability |",
      "| `fix` | A bug fix |",
      "| `chore` | Tooling, deps, config |",
      "| `refactor` | Behaviour-preserving restructure |",
      "| `docs` | Documentation only |",
      "",
      "## Two paths to `main`",
      "- **Small fixes** → commit directly to `main` with a clear Conventional Commit message. Fast path for low-risk changes.",
      "- **Features** → branch (`feature/short-name`), open a PR, let it **squash-merge**. One feature → one clean deploy line, with review in between.",
      "",
      "## Squash-merge only",
      "Merge commits and rebase-merge are **disabled** on the repo. Every PR lands as a single commit titled with the PR title, and merged branches auto-delete. Why:",
      "- `main`'s history reads as a clean changelog — one line per shipped thing.",
      "- Reverting a feature is reverting one commit.",
      "- The deploy feed stays legible for everyone (including future you at 6pm on a Friday).",
      "",
      "## Keeping current",
      "When `main` moves ahead of your branch, **rebase** — never merge `main` in and push that. See [Keeping a branch in sync](/app/handbook) for exactly how, and why the merge-in habit used to pollute the whole deploy feed.",
    ),
  },
  {
    slug: "keeping-a-branch-in-sync",
    title: "Keeping a branch in sync",
    category: "Git & Workflow",
    summary: "Rebase onto main — never merge main into your branch and push the merge. Here's how, and why.",
    tags: ["git", "rebase", "workflow"],
    content: md(
      "When `main` moves ahead of your feature branch, bring your branch up to date by **rebasing onto `main`**. This keeps history linear so the eventual squash-merge produces one clean deploy line.",
      "",
      "## Do this",
      "```bash",
      "git fetch origin",
      "git rebase origin/main",
      "# resolve any conflicts, then for each:",
      "git add <file>",
      "git rebase --continue",
      "# once done, publish the rewritten branch:",
      "git push --force-with-lease",
      "```",
      "`--force-with-lease` (not `--force`) refuses to overwrite if someone else pushed to your branch — a safety net worth the extra typing.",
      "",
      "## Never do this on a branch bound for `main`",
      "```bash",
      "git merge main   # ← creates a \"Merge origin/main into feature/x\" commit",
      "```",
      "Those merge commits ride onto production as unreadable deploy lines. Historically this was the single biggest source of deploy-feed noise before it was cleaned up — don't reintroduce it.",
      "",
      "## Resolving conflicts sanely",
      "1. `git status` shows the conflicted files.",
      "2. Open each, find the `<<<<<<<` / `=======` / `>>>>>>>` markers.",
      "3. Keep the correct content (often *both* sides, merged by hand), delete the markers.",
      "4. `git add` the file, then `git rebase --continue`.",
      "",
      "> Gotcha: running `prisma format` reflows whitespace across the whole schema, which turns a tiny change into a schema-wide conflict against someone else's edit. Format deliberately, and don't commit a pure-whitespace reformat.",
      "",
      "## If a rebase goes wrong",
      "`git rebase --abort` puts you back exactly where you started. Nothing is lost — you can always retry.",
    ),
  },
  {
    slug: "git-hygiene-and-repo-health",
    title: "Git hygiene & repo health",
    category: "Git & Workflow",
    summary: "Prune worktrees and stale branches so the object store stays healthy — and how to repair it if it doesn't.",
    tags: ["git", "maintenance", "hygiene"],
    content: md(
      "Tooling that creates a git worktree per session (like AI coding agents) can, left unmaintained, accumulate worktrees and stale local branches until the object store corrupts — missing delta bases, orphaned objects — which breaks `git gc`, `prune` and `fsck`. A little routine hygiene prevents a painful repair. This has bitten us before; it required a full mirror-clone to fix.",
      "",
      "## Routine maintenance",
      "Run every few sessions, or whenever you have more than ~5 active worktrees. **From the main repo, not a worktree:**",
      "```bash",
      "git worktree prune",
      "git branch | grep claude/ | xargs git branch -D 2>/dev/null || true",
      "git gc --prune=now",
      "```",
      "",
      "## If `git gc` fails (\"bad tree object\", \"unable to read <sha>\")",
      "The object store is corrupt. **Do not** use a shallow clone (`--depth`) to repair — shallow packs have their own missing bases and make it worse. Do a full mirror clone and copy the pack files in:",
      "```bash",
      "git clone --mirror https://github.com/Git-Dann/docs-by-gitwork.git /tmp/repair",
      "cp /tmp/repair/objects/pack/*.{pack,idx} .git/objects/pack/",
      "rm -rf /tmp/repair",
      "git gc --prune=now   # should now succeed",
      "```",
      "",
      "## Keep the repo tidy",
      "- Delete merged branches (auto-delete handles the remote side after a squash-merge).",
      "- Don't leave dozens of abandoned local branches around.",
      "- `git worktree list` to see what's active; prune the dead ones.",
      "",
      "> Healthy repos fail loudly and early. A repo that's quietly corrupting is a bad afternoon waiting to happen — the five-second `gc` is cheap insurance.",
    ),
  },

  // ── Release & Deploys ──────────────────────────────────────────────────────────
  {
    slug: "release-process",
    title: "Our release process — Staging → QA → Production",
    category: "Release & Deploys",
    summary: "The three gates every change passes before a client sees it. Skipping one is how regressions escape.",
    tags: ["release", "qa", "process"],
    featured: true,
    content: md(
      "Every change moves through three gates. They exist because the failure mode we care most about — a client discovering a regression before we do — almost always traces back to a skipped gate. Speed comes from small changes and fast reviews, never from cutting the gate.",
      "",
      "## i. Staging — build & self-verify",
      "The author builds the change and **exercises the actual flow** — not just a green build. This is the step people skip and regret.",
      "- Click through the happy path and the obvious failure paths.",
      "- Attach a screenshot or short clip to the PR.",
      "- Confirm `npm run build` and `npm run lint` are clean.",
      "",
      "> \"It should work\" is not staging. Staging is watching it work.",
      "",
      "## ii. QA — a second pair of eyes",
      "A reviewer reads the code and, for anything user-facing, clicks through it themselves. See [Code review standards](/app/handbook) for what we block on.",
      "- Correctness, security and data-loss risk are **blocking**.",
      "- Style nits are **not** blocking.",
      "- For a UI change, the reviewer should actually see the rendered result, not just the diff.",
      "",
      "## iii. Production — merge, deploy, smoke-check",
      "The PR squash-merges to `main` and **auto-deploys to the VPS in ~6 minutes** (see [Deploying Foundry](/app/handbook)).",
      "- The author **watches the deploy land** and does a quick smoke check on production.",
      "- If it's wrong, roll forward with a fast fix or roll back — see [Incident response](/app/handbook).",
      "",
      "## The one rule",
      "```",
      "  i. Staging  →  ii. QA  →  iii. Production",
      "  build &        second       merge, deploy,",
      "  self-verify    review        verify LIVE",
      "```",
      "> A change is only *released* once it's verified live. Merging is the middle of the process, not the end. The gate you're tempted to skip is exactly the one protecting the client.",
    ),
  },
  {
    slug: "deploying-foundry",
    title: "Deploying Foundry",
    category: "Release & Deploys",
    summary: "How a push to main becomes a live deploy on the VPS — the pipeline, the infra, and how to roll back.",
    tags: ["deploy", "ci-cd", "infrastructure"],
    content: md(
      "Foundry runs on a **Fasthosts VPS** via **Docker Compose** — the Next.js app container plus a self-hosted **PostgreSQL** container (with pgvector), behind a reverse proxy terminating TLS with a Let's Encrypt cert. (We migrated off Vercel + Neon; those are kept read-only as a rollback path.)",
      "",
      "## The pipeline",
      "A push to `main` triggers GitHub Actions (`.github/workflows/deploy.yml`):",
      "```",
      "1. Build the Docker image",
      "2. Push it to GHCR (ghcr.io/git-dann/docs-by-gitwork:latest + :sha)",
      "3. SSH to the VPS",
      "4. docker compose pull app   +   docker compose up -d db",
      "5. prisma db push            (NO --accept-data-loss — deliberate)",
      "6. docker compose up -d --no-deps app   +   prune old images",
      "```",
      "End to end: **~6 minutes.**",
      "",
      "## What lives where",
      "| Concern | Where |",
      "|---|---|",
      "| App + DB | Docker Compose on the VPS (`194.164.127.222`) |",
      "| DNS | `foundry.gitwork.co.uk` → A record, managed in Squarespace |",
      "| Secrets / env | The VPS `.env`, loaded by Compose (not the repo, not Vercel) |",
      "| TLS | Auto-renewing Let's Encrypt cert |",
      "| Crons, DB backups, cert renewal | **Self-managed on the box** (no platform doing it for you) |",
      "",
      "## Watch your deploy",
      "After merging, watch the GitHub Actions run go green, then smoke-check production. A deploy isn't finished when the merge lands — it's finished when you've seen the change live.",
      "",
      "## Rolling back",
      "The Vercel + Neon standby is kept live read-only. To roll back in an emergency: repoint the `foundry` A record and switch `DATABASE_URL`/`DIRECT_URL` back to the standby. For a bad code deploy, the faster path is usually to **roll forward** with a small fix (see [Incident response](/app/handbook)).",
      "",
      "> Because every merge deploys, the discipline that keeps prod safe is upstream — in [the release process](/app/handbook) and review — not in the deploy step itself.",
    ),
  },
  {
    slug: "database-changes-prisma-footgun",
    title: "Database changes & the Prisma db-push footgun",
    category: "Release & Deploys",
    summary: "Why a \"purely additive\" schema change can silently fail to reach production — and how to ship one safely.",
    tags: ["prisma", "database", "schema", "gotcha"],
    content: md(
      "This is the single most expensive gotcha in the codebase to learn the hard way. Read it before you touch `schema.prisma`.",
      "",
      "## The setup",
      "The deploy runs `prisma db push` **without** `--accept-data-loss` — deliberately, so no branch can silently drop a column or mutate the shared production database. Good default. But it has a sharp edge.",
      "",
      "## The footgun",
      "> Prisma's safety check is **all-or-nothing per push.** If the schema diff contains *anything* Prisma judges potentially data-losing — even a removed column on an unrelated table — the **entire sync is skipped, additive parts included.**",
      "",
      "So a \"purely additive\" PR (new table, new nullable column) can still fail to apply to prod if the schema *also* carries an unrelated pending drop from an earlier commit. The insidious part: **the Prisma client generates fine and TypeScript compiles**, so everything looks green — but the live DB never gets your column, and at runtime `upsert()` throws *\"the column does not exist in the current database\"*.",
      "",
      "## Before merging a schema change",
      "1. Diff it against prod's baseline:",
      "```bash",
      "git diff origin/main -- prisma/schema.prisma",
      "```",
      "2. Scan for **anything dropped** — columns, tables, enum values, indices, FKs, renames.",
      "3. Decide:",
      "",
      "| Diff contains | Action |",
      "|---|---|",
      "| Only additions (new nullable cols, new tables) | Safe — the build applies it cleanly on deploy |",
      "| Any drop / rename (yours or pending) | Won't apply via the build — handle it manually |",
      "",
      "## Handling a data-losing change",
      "- **(a) Apply manually first:** with the prod URLs, run `prisma db push --accept-data-loss` from your machine, verify, *then* merge.",
      "- **(b) Use proper migrations:** `prisma migrate dev` locally to generate the SQL, commit the migration file; the build runs `migrate deploy`. Heavier, but reproducible — the right long-term answer as schema changes get frequent.",
      "",
      "## The habit that avoids all of this",
      "Keep schema changes **additive**: new nullable columns, new tables, new enum values. Additive changes always apply cleanly. When you must drop something, do it in its own deliberate, manually-applied change — never bundled with a feature.",
    ),
  },

  // ── Frontend ─────────────────────────────────────────────────────────────────
  {
    slug: "frontend-standards",
    title: "Frontend standards",
    category: "Frontend",
    summary: "React and Next.js patterns we hold to — data, components, images and accessibility.",
    tags: ["react", "nextjs", "frontend"],
    content: md(
      "Foundry is Next.js App Router + React 19 + TypeScript on Tailwind v4. A handful of patterns keep the frontend predictable across dozens of screens.",
      "",
      "## Data fetching",
      "- **Never fetch ad-hoc in a component.** Use a TanStack React Query hook from `src/hooks/`, backed by a fetcher in `src/lib/api.ts`.",
      "- Keep query keys stable and structured (`[\"handbook\", \"list\", filters]`).",
      "- Invalidate the right keys in a mutation's `onSuccess` — stale UI after a write is a bug.",
      "- Server components fetch directly; client components (`\"use client\"`) use hooks.",
      "```ts",
      "const { data, isLoading } = useHandbookList({ q, category });",
      "// mutation:",
      "onSuccess: () => qc.invalidateQueries({ queryKey: [\"handbook\", \"list\"] })",
      "```",
      "",
      "## Components",
      "- One component, one job. Lift shared UI into `src/components/ui/`.",
      "- Use the shared `Button`, `Modal`, `toast`, `Tooltip` primitives — don't hand-roll a fifth variant.",
      "- Gate rendering on `usePermissions()` for UX, but remember it's **cosmetic** — the server is authoritative and blanks/reject gated data regardless (see [Security baseline](/app/handbook)).",
      "",
      "## Images",
      "- `next/image` (`<Image>`) for static assets in `public/`.",
      "- Raw `<img>` **only** for dynamic/user-uploaded images, with the `eslint-disable-next-line @next/next/no-img-element` comment above it.",
      "",
      "## Accessibility (not optional)",
      "- Real `<button>` for actions, real `<a>`/`<Link>` for navigation — never a clickable `<div>`.",
      "- Every icon-only control needs an `aria-label`.",
      "- Inputs need associated `<label>`s; focus states must be visible.",
      "- Wide content (tables, code) scrolls inside its own `overflow-x-auto` container so the page never scrolls sideways.",
      "",
      "## Loading & empty states",
      "Every list has three states, and all three ship: **loading** (skeletons, not a spinner void), **empty** (a real message + the primary action), and **populated**. A screen that only handles the happy path isn't done.",
      "",
      "For anything visual, build against the [Foundry design system](/app/handbook) — the widget grammar isn't decoration, it's the brand.",
    ),
  },
  {
    slug: "building-on-the-design-system",
    title: "Building on the Foundry design system",
    category: "Design System",
    summary: "The widget signature, the type triple, tokens and the rules that make the whole app feel like one instrument.",
    tags: ["design-system", "ui", "brand"],
    featured: true,
    content: md(
      "The full system is documented in `DESIGN.md` — treat every token and component name there as canonical, and update the doc when patterns change. This is the working summary.",
      "",
      "## The brand signature — numbered widget headers",
      "Every dashboard panel and data card opens with a numbered monospace header:",
      "```",
      "01 // WIDGET NAME",
      "```",
      "in `{typography.widget-header}` (JetBrains Mono, 10px, uppercase, wide tracking). **This is THE Foundry signature** — it appears on every card, every module, without exception. Never skip it, never restyle it into Inter or serif. Number sections sequentially within a view.",
      "",
      "## The type triple — three fonts, three lanes",
      "| Family | Lane |",
      "|---|---|",
      "| **Inter** | All UI: labels, body, buttons, nav |",
      "| **DM Serif Display** | Large stat figures and editorial hero text — the *only* place the app reads warm |",
      "| **JetBrains Mono** | Widget headers, timestamps, data-unit labels, code |",
      "Never use DM Serif for body or UI labels; never render a widget header in anything but mono.",
      "",
      "## Colour & shape",
      "- **Gitwork Blue** (`--brand-*`, #1D4ED8) on all interactive elements, active states and data highlights. **No accent colours outside the blue family** and the semantic set (success/warning/danger).",
      "- Cards: `--surface-0` face, hairline border (`--border-2`), **no drop shadow** on flat cards. Shadow means modal or overlay.",
      "- Radius: **6px** on controls, **10px** on cards. `rounded-full` is for 6px status dots only — **never pills, never buttons.**",
      "- Canvas is warm off-white (`--surface-canvas`), never pure `#FFFFFF`.",
      "",
      "## Always use tokens",
      "Style with the CSS variables — `--text-*`, `--surface-*`, `--border-*`, `--brand-*` — so light and dark mode both work.",
      "```tsx",
      "// Good — flips correctly in dark mode",
      "<div className=\"border border-[var(--border-2)] bg-[var(--surface-0)] text-[var(--text-1)]\">",
      "```",
      "> Gotcha: hardcoding a hex for text on the navy dark shell makes it **invisible** in dark mode. The dark remap covers `bg-white` and semantic tokens but not `text-slate-500` etc. Use the tokens.",
      "",
      "## Editorial liberties",
      "Some surfaces (the Desk, the statement-style Docs render, this Handbook's article view) take editorial liberties — serif titles, mono eyebrows, section rails — but always **on brand-blue**, class-scoped so they never leak into the app chrome. That's the ceiling: expressive within the system, never outside it.",
    ),
  },
  {
    slug: "responsive-and-mobile-standards",
    title: "Responsive & mobile standards",
    category: "Frontend",
    summary: "How we do responsive work without siloing a fix to the one screen where we noticed the bug.",
    tags: ["responsive", "mobile", "css"],
    content: md(
      "Responsive work is a whole-system concern, not a per-screen patch. `docs/mobile-playbook.md` is the **mandatory operating standard** — read it before any layout work. This is the short version.",
      "",
      "## Breakpoints",
      "| Name | Width | Key changes |",
      "|---|---|---|",
      "| Mobile | < 640px | Single-column bento; stat sizes scale down |",
      "| Tablet | 640–1023px | 2-column (6-col base) |",
      "| Desktop | 1024–1279px | Full 3-column bento; sidebar icons |",
      "| Wide | ≥ 1280px | Sidebar expands with labels; 12-col bento |",
      "",
      "## The blast-radius rule",
      "> Fix responsive issues at the **shared primitive**, not the one screen where you noticed them. A one-off fix almost always means five other screens are still broken the same way.",
      "",
      "When you fix a layout bug, ask: *what else renders this component or pattern?* Then verify a couple of those too. A fix that only helps the screen in front of you is half a fix.",
      "",
      "## Rules that prevent most bugs",
      "- **Nothing scrolls the page sideways.** Wide content (tables, diagrams, code, Gantt) lives in its own `overflow-x-auto` container.",
      "- Use relative units and flex/grid; `max-width: 100%` on media.",
      "- Design mobile-first, then enhance up — it's easier than cramming a desktop layout down.",
      "- Tap targets are finger-sized on mobile (≥ 40px), not mouse-sized.",
      "",
      "## Verify at real widths",
      "Test at mobile, tablet and desktop, **and in dark mode**, before you call it done. A layout that only works at your laptop width isn't responsive — it's lucky.",
    ),
  },

  // ── Backend ─────────────────────────────────────────────────────────────────
  {
    slug: "api-route-conventions",
    title: "API route conventions",
    category: "Backend",
    summary: "The exact shape every /api route follows — responses, validation, params, and auth gating.",
    tags: ["api", "backend", "conventions"],
    content: md(
      "Every route under `src/app/api/` follows one shape. That uniformity is what makes the API safe by default and quick to read — you should be able to guess how any route is structured before opening it.",
      "",
      "## The canonical route",
      "```ts",
      "import { apiOk, apiError, fromError } from \"@/lib/api-response\";",
      "import { thingSchema } from \"@/server/validators\";",
      "import { assertCan, canDoThing, getEffectiveUserOrNull } from \"@/server/auth/effective-user\";",
      "",
      "export const dynamic = \"force-dynamic\";",
      "",
      "export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {",
      "  try {",
      "    const user = await getEffectiveUserOrNull(req);",
      "    assertCan(user, canDoThing, \"do the thing\");",
      "    const { id } = await params;              // Next 15: params is a Promise",
      "    const data = thingSchema.parse(await req.json());",
      "    const result = await doThing(id, data);",
      "    if (!result) return apiError(\"Not found\", 404);",
      "    return apiOk({ result });",
      "  } catch (error) {",
      "    return fromError(error);                   // maps ZodError / known errors to status codes",
      "  }",
      "}",
      "```",
      "",
      "## The four rules",
      "1. **Responses** always go through `apiOk` / `apiError` / `fromError` — never a raw `NextResponse.json` with an ad-hoc shape.",
      "2. **Validate every body** with a Zod schema from `src/server/validators.ts`. Never trust the client shape.",
      "3. **`await params`** — in Next.js 15 route params arrive as a `Promise`.",
      "4. **Gate before you act.** Resolve the user and `assertCan(user, canX, \"…\")`. `fromError` turns thrown auth errors into the right 401/403.",
      "",
      "## Auth model",
      "- All `/api/` routes except `/api/health` are gated by the `API_KEY` middleware; browser traffic carries an HttpOnly session cookie.",
      "- Per-user capability checks use the `can*` helpers in `src/server/auth/effective-user.ts`.",
      "- **Gate sensitive fields server-side** — blank them in the payload or reject; never rely on the UI hiding them.",
      "",
      "## Keep the logic out of the route",
      "Routes are thin: parse, gate, delegate to a `src/server/{domain}.ts` function, shape the response. Business logic lives in the server module so it's testable and reusable (the same function backs the web UI, the iOS app and the MCP tools).",
    ),
  },
  {
    slug: "data-and-prisma-conventions",
    title: "Data & Prisma conventions",
    category: "Backend",
    summary: "How we model data, scope every query, serialize to DTOs, and avoid the classic performance traps.",
    tags: ["prisma", "database", "backend"],
    content: md(
      "Prisma is our ORM over PostgreSQL. These conventions keep data access safe (multi-tenant), clean (typed DTOs) and fast.",
      "",
      "## Access",
      "- Import the **singleton** from `src/lib/prisma.ts` — never `new PrismaClient()`.",
      "- **Scope every query to the workspace**, and for restricted users to their assigned clients. A missing `where: { workspaceId }` is a cross-tenant data leak — treat it as a security bug, not a style nit.",
      "",
      "## Serialize to DTOs — never leak rows",
      "Don't return raw Prisma rows to the client. Map to a DTO in the server module and convert `Date` → ISO string. Keep the DTO type next to its serializer so client and server share one source of truth.",
      "```ts",
      "function serialize(a: Row): ArticleDTO {",
      "  return { id: a.id, title: a.title, updatedAt: a.updatedAt.toISOString() };",
      "}",
      "```",
      "This also keeps internal/sensitive columns from accidentally reaching a payload.",
      "",
      "## Schema changes",
      "- Prefer **additive** changes — new nullable columns, new tables, new enum values. They apply cleanly on deploy.",
      "- Read [the Prisma db-push footgun](/app/handbook) before *any* drop or rename — it's not optional reading.",
      "- **Index the columns you filter and sort on.** Add `@@index` for common query shapes.",
      "",
      "## Performance traps",
      "| Trap | Fix |",
      "|---|---|",
      "| N+1 (a query per row) | `findMany` + `include`, or batch the ids |",
      "| Counting in a loop | one `groupBy` with `_count` |",
      "| Over-fetching whole rows | `select` only the fields you use |",
      "| Aggregates in app code | push them into the query |",
      "",
      "> A route that's fast with 10 rows and dies at 10,000 isn't done — it's a latent incident. Think about the query shape at the scale the client will actually reach.",
    ),
  },
  {
    slug: "working-with-ai-providers",
    title: "Working with AI providers",
    category: "Backend",
    summary: "How we call models in Foundry — provider resolution, reliability, and cost/safety discipline.",
    tags: ["ai", "anthropic", "backend"],
    content: md(
      "Foundry is multi-provider (Anthropic by default, OpenAI/Gemini optional), configurable per workspace. AI features are powerful and expensive and flaky — treat them accordingly.",
      "",
      "## Never hardcode a model",
      "Resolve the model and provider from workspace settings — **never** a string literal in code.",
      "```ts",
      "// Good — resolves provider + key + model from the workspace",
      "const aiConfig = await resolveAiConfig(workspace);",
      "const text = await completeText(aiConfig, prompt);",
      "```",
      "- Use `resolveAiConfig` + `completeText` + `parseJsonObject` from `src/server/ai-provider.ts` for new work — don't re-implement provider plumbing.",
      "- For Pulse, `getModelForTask()` is the canonical resolver.",
      "- Default new features to the **latest, most capable Claude models**.",
      "",
      "## Reliability — assume it fails",
      "Model calls time out, rate-limit and return malformed JSON. Design for it:",
      "- Always have a **fallback path** — a checks-only result, a cached value, or a clean error to the user. Never a blank screen.",
      "- Keep long-running AI work **off the request path** (background jobs / `after()`), and **persist partial results** so a mid-run failure still leaves something usable.",
      "- Validate model JSON output before trusting it (`parseJsonObject` + a schema).",
      "",
      "## Cost & safety",
      "- Don't stuff secrets or entire client datasets into a prompt without a reason — send the minimum.",
      "- **Cache** where the same input recurs (there's an AI response cache for exactly this).",
      "- Be mindful that AI spend is visible and adds up; a needless re-run of a large prompt is real money.",
      "",
      "> The AI is a component with a failure rate, not magic. The quality bar is the same as any other backend dependency: validated inputs, handled failures, bounded cost.",
    ),
  },

  // ── Security ─────────────────────────────────────────────────────────────────
  {
    slug: "security-baseline",
    title: "Security baseline",
    category: "Security",
    summary: "The non-negotiables on every change: auth, server-side gating, input validation, least privilege.",
    tags: ["security", "auth", "baseline"],
    featured: true,
    content: md(
      "Security isn't a phase or a specialist's job — it's a set of defaults we hold on every change. Most breaches are boring: a missing check, an unvalidated body, a secret in a log. Hold the baseline and the boring ones don't happen.",
      "",
      "## Auth & access",
      "- Every `/api/` route except `/api/health` is gated by the `API_KEY` middleware; browser traffic carries an HttpOnly session cookie.",
      "- Gate capabilities **server-side** with `assertCan(user, canX, \"…\")`. UI hiding via `usePermissions()` is cosmetic UX only.",
      "- **Scope every query** to the workspace, and to assigned clients for restricted users.",
      "",
      "## The cardinal rule",
      "> The client is never trusted and the UI is never the enforcement point. If a developer opens dev tools and hits your endpoint directly, the server must still say no. Hiding a button is not a permission.",
      "",
      "## Input",
      "- Validate every mutation body with a **Zod schema**. Reject unexpected shapes — don't coerce them.",
      "- Sanitize any user-supplied URL or HTML. We render markdown to **React elements**, never `dangerouslySetInnerHTML` with untrusted input (see the Handbook's own `article-markdown` renderer).",
      "- Treat anything from a client, a webhook, or a model output as untrusted until validated.",
      "",
      "## Least privilege",
      "- New capabilities default **OFF**. Grant them explicitly, per person, via the role matrix.",
      "- High-risk actions (public sharing, fix-agent PRs that open client GitHub PRs, bulk delete) require their **own** permission and are flagged as high-risk.",
      "- Some tools are Super-Admin-only by role, not a grantable perm (Starters, this Handbook for now).",
      "",
      "## When you find a hole",
      "Fix it or flag it **immediately** — don't sit on it. If it's live and exploitable, treat it as an incident ([Incident response](/app/handbook)). A quietly-known hole is worse than a loudly-fixed one.",
    ),
  },
  {
    slug: "handling-secrets-and-credentials",
    title: "Handling secrets & credentials",
    category: "Security",
    summary: "Where secrets live, how they're stored, and the things that must never touch git or Slack.",
    tags: ["security", "secrets", "credentials"],
    content: md(
      "A leaked secret is one of the fastest ways to lose a client's trust and cause real damage. Handle credentials with deliberate care.",
      "",
      "## Where secrets live",
      "| Environment | Store | Committed? |",
      "|---|---|---|",
      "| Production | The VPS `.env`, loaded by Docker Compose | **Never** |",
      "| Local dev | `.env.local` | **Never** (git-ignored) |",
      "| Client integration tokens | Per-connection, server-side (e.g. on the connection record) | Never in `localStorage` |",
      "",
      "## Hard rules",
      "- **Never** paste a live secret into Slack, a PR, a commit message, a ticket, or a screenshot. If one is exposed anywhere, treat it as compromised and **rotate it**.",
      "- **Never** commit `.env`, `.env.local`, key files, or a token — even \"temporarily\". Git remembers forever.",
      "- Log carefully: don't `console.log` a request that carries a token or PII.",
      "",
      "## The `ENCRYPTION_KEY` — handle with extra care",
      "Client data encrypted at rest (e.g. onboarding bank details, AES-256-GCM) depends on `ENCRYPTION_KEY` staying **stable and identical** to prod. Regenerate it casually and every piece of previously-encrypted data becomes permanently unreadable. It is not a rotate-whenever secret.",
      "",
      "## Access hygiene",
      "- Request the **minimum** access you need for the task.",
      "- Prefer **per-user OAuth** over shared credentials — it's auditable and revocable per person.",
      "- When someone rolls off a project, revoke their access promptly.",
      "",
      "> If you're ever unsure whether something is a secret, assume it is. The cost of over-caution is zero; the cost of a leak is a client relationship.",
    ),
  },

  // ── Process ────────────────────────────────────────────────────────────────────
  {
    slug: "standups-and-communication",
    title: "Daily standups & communication",
    category: "Process",
    summary: "How we run standups, keep clients informed, and communicate async as a distributed team.",
    tags: ["communication", "standups", "process"],
    content: md(
      "We're a distributed team on tight timelines. Communication is the connective tissue — done well it feels effortless; done badly it's where projects quietly go wrong.",
      "",
      "## Daily standups (on the task board)",
      "- **AM \"Doing\"** — what you're picking up today. On Mondays, add a short \"this week\" note (it pre-fills from tasks due this ISO week).",
      "- **PM \"Done\"** — what actually shipped today.",
      "- These roll up automatically to the relevant client channels, so clients see steady momentum **without a status meeting**. That auto-roll-up only works if you push — so push.",
      "",
      "## Async first",
      "- **Write it where the team can find it later** — a channel beats a DM, a doc beats a channel for anything durable.",
      "- Make requests **actionable**: what you need, from whom, by when. \"Can someone look at this?\" ages badly; \"@name, can you review PR #123 before EOD?\" gets done.",
      "- **Over-communicate blockers.** \"I'm stuck on X and here's what I've tried\" today beats a silent missed deadline tomorrow.",
      "",
      "## Talking to clients",
      "- Calm, specific, and honest. **Under-promise, over-deliver.**",
      "- **Never surprise a client.** Flag slips, risks and scope changes early — always with a proposed plan attached, not just a problem.",
      "- Match their level: an exec wants the outcome and the risk; a technical contact wants the detail. Say the same truth, pitched right.",
      "",
      "> The goal of all of this is that a teammate or a client can act on what you said without chasing you for clarification. Clarity is a kindness — and it's faster for everyone.",
    ),
  },
  {
    slug: "scoping-and-estimation",
    title: "How we scope & estimate work",
    category: "Process",
    summary: "Turning a vague ask into a plan and an honest estimate you can actually commit to.",
    tags: ["estimation", "scoping", "planning"],
    content: md(
      "Estimates are promises to a client, and clients plan their business around them. We make them carefully and honestly — a padded-but-kept estimate builds trust; an optimistic-but-missed one erodes it.",
      "",
      "## Scope before you estimate",
      "- Get clear on the **outcome**, not the feature list. What does \"working\" look like for the client's user?",
      "- Break the work into pieces you can **ship independently** — small increments are easier to estimate and de-risk.",
      "- **Name the unknowns out loud.** The parts you'd need to spike before you'd trust a number are exactly the parts that blow estimates.",
      "",
      "## Estimate the whole thing",
      "The classic mistake is estimating only the happy-path coding. Estimate the real cost:",
      "```",
      "  build  +  review  +  QA  +  deploy  +  the fixes you know are coming",
      "```",
      "- Pad for the unknowns you named — proportionally to how unknown they are.",
      "- If you genuinely can't estimate a piece, **timebox a spike** instead of guessing. \"Two days to investigate, then I'll estimate\" is a real answer.",
      "- Prefer **ranges and stated assumptions** over false precision. \"3–5 days, assuming the API is as documented\" is more useful than \"4 days\".",
      "",
      "## Commit, then track honestly",
      "- Once scoped, put it on the board as **feature blocks** and tasks so it's visible on the Gantt and the client timeline.",
      "- If reality diverges from the estimate, **raise it the moment you know** — don't quietly absorb the slip and hope. Early is a plan; late is an apology.",
      "",
      "> An estimate is a forecast, not a fact. The professional move isn't being right every time — it's being transparent about confidence up front and about drift the instant it appears.",
    ),
  },

  // ── Playbooks ──────────────────────────────────────────────────────────────────
  {
    slug: "incident-response",
    title: "Incident response — when prod breaks",
    category: "Playbooks",
    summary: "The calm, fast path from \"production is down\" to \"fixed, verified and understood\".",
    tags: ["incident", "production", "playbook"],
    content: md(
      "Production will break sometimes — that's a certainty, not a failure. What separates a good team from a shaky one is how calmly and quickly it responds. Here's the playbook.",
      "",
      "## 1. Assess — how bad, how wide?",
      "- Who's affected and how badly? A broken internal admin page is **not** the same as a down client site — triage accordingly.",
      "- Post in the team channel immediately: *what's happening, who's on it.* **One owner** coordinates; others support without stepping on each other.",
      "",
      "## 2. Stabilise — stop the bleeding",
      "Restore service first; understand fully second.",
      "- **Recent deploy caused it?** Fastest fix is usually to roll forward with a small targeted change, or roll back (see [Deploying Foundry](/app/handbook)).",
      "- **A route crashing because a column never applied?** Classic symptom of [the Prisma db-push footgun](/app/handbook) — apply the schema to prod manually and it's often a ten-second fix.",
      "- **Don't** start a big refactor mid-incident. Smallest change that restores service.",
      "",
      "## 3. Fix & verify",
      "Ship the real fix through the normal gates — but fast — and **verify on production**, not just locally. The incident isn't over until you've watched it work live.",
      "",
      "## 4. Learn — make it un-repeatable",
      "Briefly write down: what happened, why, and the one change (a check, a test, a doc, a guardrail) that stops it recurring the same way. Add that change.",
      "",
      "## The culture",
      "> **Blameless.** We fix the system, not the person. The dev who shipped the bug is usually the one best placed to fix it and to prevent the next one — punishing them just teaches everyone to hide problems.",
    ),
  },
  {
    slug: "client-handover-checklist",
    title: "Client handover checklist",
    category: "Playbooks",
    summary: "What we hand over when a project ships, so the client is genuinely self-sufficient — not stranded.",
    tags: ["handover", "client", "playbook"],
    content: md(
      "A clean handover is the difference between a client who trusts us with their next project and one who feels abandoned the moment the invoice clears. Handover isn't an afterthought — it's a deliverable, and it starts at the beginning of the project.",
      "",
      "## Access & ownership",
      "- [ ] The client **owns** their repos, hosting, domains and third-party accounts — in their name, not held by us on their behalf.",
      "- [ ] Credentials transferred securely (see [Handling secrets & credentials](/app/handbook)); our temporary access revoked where appropriate.",
      "- [ ] Billing for any services is on the client's own accounts.",
      "",
      "## Documentation",
      "- [ ] A clear **README / runbook**: how to run, build, deploy and configure the thing.",
      "- [ ] An **architecture overview** and the key decisions behind it (and the roads not taken).",
      "- [ ] **Known limitations and deliberate trade-offs**, written down — surprises later read as defects.",
      "- [ ] Environment variables documented (names and purpose, not the secret values).",
      "",
      "## Operations",
      "- [ ] **Monitoring and backups** in place and explained — the client should know when something's wrong and how to recover.",
      "- [ ] A named **support/aftercare** arrangement, or a clean cut-off the client understands.",
      "",
      "## The walkthrough",
      "- [ ] A live, **recorded** handover session covering all of the above, so the knowledge outlives the meeting.",
      "",
      "## Build it to be handed over",
      "> The best handover is one you barely have to do — because the code is readable, the docs were written as you went, and nothing critical lives only in your head. Design for the day you walk away from day one.",
    ),
  },
];

/**
 * Seed / refresh the built-in Handbook articles. Version-gated: runs only when the workspace's
 * stored `handbookSeedVersion` is below `HANDBOOK_SEED_VERSION`. On a version bump it upserts every
 * built-in article by slug (create if missing, refresh core fields if present) and advances the
 * version — so improved built-in content ships on deploy, but members' edits are preserved between
 * bumps and their own (differently-slugged) articles are never touched. Idempotent; safe every boot.
 */
export async function seedHandbookArticles(workspaceId: string): Promise<number> {
  const workspace = await prisma.workspace.findUnique({
    where: { id: workspaceId },
    select: { handbookSeedVersion: true },
  });
  if (workspace && workspace.handbookSeedVersion >= HANDBOOK_SEED_VERSION) return 0;

  const now = new Date();
  let written = 0;
  for (const [i, a] of HANDBOOK_SEED.entries()) {
    const words = a.content.trim().split(/\s+/).filter(Boolean).length;
    const readMinutes = Math.max(1, Math.round(words / 200));
    await prisma.handbookArticle.upsert({
      where: { slug: a.slug },
      update: {
        // Refresh authored content on a version bump. Leave status/orderKey/viewCount alone so an
        // admin who archived or reordered an article keeps that; only promote featured, never unset
        // it, so manual pins survive.
        title: a.title,
        summary: a.summary,
        category: a.category,
        content: a.content,
        tags: a.tags,
        readMinutes,
        ...(a.featured ? { featured: true } : {}),
      },
      create: {
        workspaceId,
        title: a.title,
        slug: a.slug,
        summary: a.summary,
        category: a.category,
        content: a.content,
        tags: a.tags,
        status: "PUBLISHED",
        featured: a.featured ?? false,
        readMinutes,
        orderKey: i,
        publishedAt: now,
      },
    });
    written += 1;
  }

  await prisma.workspace.update({
    where: { id: workspaceId },
    data: { handbookSeedVersion: HANDBOOK_SEED_VERSION },
  });
  return written;
}
