import type { PulseScanCheckInput } from "@/types/pulse";
import type { ExtendedCheckContext } from "./_types";
import { skip } from "./_types";

const CATEGORY = "AI Readiness";

const ALL_CHECKS: Array<[string, string]> = [
  ["ai_feedback_ui", "User feedback loop on AI outputs"],
  ["ai_error_fallback_ui", "AI error / fallback state in UI"],
  ["ai_streaming_ui", "Streaming AI response pattern"],
  ["ai_cost_monitoring_script", "AI cost / usage monitoring tool"],
  ["ai_content_safety_signal", "Content moderation / safety layer"],
  ["ai_human_review_signal", "Human-in-the-loop review signal"],
  ["ai_rate_limit_ui", "Rate limit / quota UI signal"],
  ["ai_ai_act_disclosure", "EU AI Act transparency disclosure"],
  ["ai_provider_detected", "AI provider detected on page"],
];

export async function runAiReadinessChecks(
  ctx: ExtendedCheckContext,
): Promise<PulseScanCheckInput[]> {
  const { htmlLower } = ctx;

  const hasAiSignals =
    htmlLower.includes("openai") ||
    htmlLower.includes("anthropic") ||
    htmlLower.includes("claude") ||
    htmlLower.includes("chatgpt") ||
    htmlLower.includes("gpt-4") ||
    htmlLower.includes("gpt-3") ||
    htmlLower.includes("gemini") ||
    htmlLower.includes("langchain") ||
    htmlLower.includes("/api/chat") ||
    htmlLower.includes("/api/ai") ||
    htmlLower.includes("ai-powered") ||
    htmlLower.includes("powered by ai") ||
    htmlLower.includes("generated by ai") ||
    htmlLower.includes("ai-generated") ||
    htmlLower.includes("ai sdk") ||
    htmlLower.includes("vercel ai");

  if (!hasAiSignals) {
    return skip(CATEGORY, ALL_CHECKS, "No AI provider signals detected on this page.");
  }

  const checks: PulseScanCheckInput[] = [];

  // 1. User feedback loop
  const hasFeedbackUi =
    htmlLower.includes("was this helpful") ||
    htmlLower.includes("thumbs up") ||
    htmlLower.includes("thumbs down") ||
    htmlLower.includes("upvote") ||
    htmlLower.includes("downvote") ||
    htmlLower.includes("regenerate") ||
    (htmlLower.includes("feedback") && htmlLower.includes("rating")) ||
    (htmlLower.includes("feedback") && htmlLower.includes("rate this"));

  checks.push({
    category: CATEGORY,
    checkKey: "ai_feedback_ui",
    label: "User feedback loop on AI outputs",
    status: hasFeedbackUi ? "PASS" : "WARN",
    detail: hasFeedbackUi
      ? "User feedback mechanism detected (thumbs, ratings, or regenerate)."
      : "No user feedback UI detected. Without thumbs/ratings, you cannot identify when the AI performs poorly in production.",
  });

  // 2. AI error / fallback state
  const hasErrorFallback =
    htmlLower.includes("try again") ||
    htmlLower.includes("ai unavailable") ||
    htmlLower.includes("generating...") ||
    htmlLower.includes("thinking...") ||
    htmlLower.includes("skeleton") ||
    htmlLower.includes("spinner") ||
    htmlLower.includes("fallback mode") ||
    (htmlLower.includes("loading") && htmlLower.includes("ai"));

  checks.push({
    category: CATEGORY,
    checkKey: "ai_error_fallback_ui",
    label: "AI error / fallback state in UI",
    status: hasErrorFallback ? "PASS" : "WARN",
    detail: hasErrorFallback
      ? "Error or loading state detected — the app handles AI delays or provider failures gracefully."
      : "No AI error or loading state detected. When the AI provider fails or is slow, users will see blank or broken output.",
  });

  // 3. Streaming AI response pattern
  const hasStreamingUi =
    htmlLower.includes("eventsource") ||
    htmlLower.includes("readablestream") ||
    htmlLower.includes("text/event-stream") ||
    htmlLower.includes("typewriter") ||
    htmlLower.includes("typing-indicator") ||
    htmlLower.includes("typing indicator") ||
    (htmlLower.includes("stream") && htmlLower.includes("response"));

  checks.push({
    category: CATEGORY,
    checkKey: "ai_streaming_ui",
    label: "Streaming AI response pattern",
    status: hasStreamingUi ? "PASS" : "WARN",
    detail: hasStreamingUi
      ? "Streaming or progressive response pattern detected — better perceived performance for long AI outputs."
      : "No streaming response pattern detected. Long AI requests will feel unresponsive without progressive rendering.",
  });

  // 4. AI cost / observability monitoring
  const hasCostMonitoring =
    htmlLower.includes("helicone") ||
    htmlLower.includes("langsmith") ||
    htmlLower.includes("langfuse") ||
    htmlLower.includes("portkey") ||
    htmlLower.includes("arize") ||
    htmlLower.includes("traceloop") ||
    htmlLower.includes("braintrust") ||
    htmlLower.includes("wandb") ||
    htmlLower.includes("weights & biases");

  checks.push({
    category: CATEGORY,
    checkKey: "ai_cost_monitoring_script",
    label: "AI cost / usage monitoring tool",
    status: hasCostMonitoring ? "PASS" : "WARN",
    detail: hasCostMonitoring
      ? "AI observability or cost monitoring tool detected — LLM spend and usage are tracked."
      : "No AI observability tool detected. Without LLM cost monitoring, API spend can grow unnoticed and unpredictably in production.",
  });

  // 5. Content safety / moderation
  const hasContentSafety =
    htmlLower.includes("content moderation") ||
    htmlLower.includes("content policy") ||
    htmlLower.includes("content filter") ||
    htmlLower.includes("content-filter") ||
    htmlLower.includes("guardrail") ||
    htmlLower.includes("safe content") ||
    htmlLower.includes("openai moderation") ||
    htmlLower.includes("perspective api") ||
    htmlLower.includes("profanity filter");

  checks.push({
    category: CATEGORY,
    checkKey: "ai_content_safety_signal",
    label: "Content moderation / safety layer",
    status: hasContentSafety ? "PASS" : "WARN",
    detail: hasContentSafety
      ? "Content safety or moderation layer detected."
      : "No content moderation layer detected. Unfiltered AI outputs shown directly to users risk brand damage, legal liability, and abuse.",
  });

  // 6. Human-in-the-loop review
  const hasHumanReview =
    htmlLower.includes("pending review") ||
    htmlLower.includes("review before sending") ||
    htmlLower.includes("human review") ||
    htmlLower.includes("agent assist") ||
    htmlLower.includes("escalate to human") ||
    htmlLower.includes("approve before") ||
    htmlLower.includes("supervised") ||
    (htmlLower.includes("draft") && htmlLower.includes("send"));

  checks.push({
    category: CATEGORY,
    checkKey: "ai_human_review_signal",
    label: "Human-in-the-loop review signal",
    status: hasHumanReview ? "PASS" : "WARN",
    detail: hasHumanReview
      ? "Human review or approval step detected — consequential AI decisions are supervised."
      : "No human review signal found. For AI actions with real-world impact (emails, orders, payments), a human approval step is essential.",
  });

  // 7. Rate limit / quota UI
  const hasRateLimitUi =
    htmlLower.includes("rate limit") ||
    htmlLower.includes("usage limit") ||
    htmlLower.includes("requests remaining") ||
    htmlLower.includes("quota exceeded") ||
    htmlLower.includes("api limit") ||
    (htmlLower.includes("credits") && htmlLower.includes("remaining")) ||
    (htmlLower.includes("token") && htmlLower.includes("limit"));

  checks.push({
    category: CATEGORY,
    checkKey: "ai_rate_limit_ui",
    label: "Rate limit / quota UI signal",
    status: hasRateLimitUi ? "PASS" : "WARN",
    detail: hasRateLimitUi
      ? "Rate limit or usage quota UI detected — users see their limits before hitting them."
      : "No usage quota or rate limit UI detected. Users will hit API limits with no warning or recovery path.",
  });

  // 8. EU AI Act / transparency disclosure
  const hasAiActDisclosure =
    htmlLower.includes("ai-generated") ||
    htmlLower.includes("ai generated") ||
    htmlLower.includes("generated by ai") ||
    htmlLower.includes("powered by ai") ||
    htmlLower.includes("ai act disclosure") ||
    htmlLower.includes("this content was generated") ||
    htmlLower.includes("synthetic content notice") ||
    (htmlLower.includes("artificial intelligence") && htmlLower.includes("disclosure"));

  checks.push({
    category: CATEGORY,
    checkKey: "ai_ai_act_disclosure",
    label: "EU AI Act transparency disclosure",
    status: hasAiActDisclosure ? "PASS" : "WARN",
    detail: hasAiActDisclosure
      ? "AI-generated content disclosure detected — meets EU AI Act transparency requirements."
      : "No AI content disclosure detected. The EU AI Act (2024) requires that users be informed when interacting with AI-generated content.",
  });

  // 9. AI provider identification (informational)
  const providers: string[] = [];
  if (htmlLower.includes("openai") || htmlLower.includes("chatgpt") || htmlLower.includes("gpt-4") || htmlLower.includes("gpt-3")) providers.push("OpenAI");
  if (htmlLower.includes("anthropic") || htmlLower.includes("claude")) providers.push("Anthropic");
  if (htmlLower.includes("gemini") || htmlLower.includes("google ai") || htmlLower.includes("vertex ai")) providers.push("Google AI");
  if (htmlLower.includes("mistral")) providers.push("Mistral");
  if (htmlLower.includes("llama") || htmlLower.includes("meta ai")) providers.push("Meta AI");
  if (htmlLower.includes("cohere")) providers.push("Cohere");
  if (htmlLower.includes("huggingface") || htmlLower.includes("hugging face")) providers.push("Hugging Face");
  if (htmlLower.includes("perplexity")) providers.push("Perplexity");
  if (htmlLower.includes("together.ai") || htmlLower.includes("togetherai")) providers.push("Together AI");

  checks.push({
    category: CATEGORY,
    checkKey: "ai_provider_detected",
    label: "AI provider detected on page",
    status: providers.length > 0 ? "PASS" : "WARN",
    detail:
      providers.length > 0
        ? `AI providers detected: ${providers.join(", ")}.`
        : "AI signals detected but no specific provider identified — checks above are based on general AI patterns.",
  });

  return checks;
}
