import type { PulseScanCheckInput } from "@/types/pulse";
import type { ExtendedCheckContext } from "./_types";
import { headRequest } from "./_types";

const CATEGORY = "Vibe Code Hygiene";

export async function runVibeCodeHygieneChecks(
  ctx: ExtendedCheckContext,
): Promise<PulseScanCheckInput[]> {
  const { htmlLower, httpsUrl } = ctx;
  const checks: PulseScanCheckInput[] = [];

  // 1. Placeholder / filler content
  const hasLoremIpsum = htmlLower.includes("lorem ipsum");
  const hasExampleEmail =
    htmlLower.includes("example@example.com") ||
    htmlLower.includes("admin@example.com") ||
    htmlLower.includes("test@test.com") ||
    htmlLower.includes("user@user.com") ||
    htmlLower.includes("demo@demo.com");
  const hasTodoMarker =
    /\b(fixme:|hack:)\b/.test(htmlLower) ||
    (htmlLower.includes("todo:") && !htmlLower.includes("todo app") && !htmlLower.includes("to-do list") && !htmlLower.includes("todos"));
  const hasPlaceholderContent = hasLoremIpsum || hasExampleEmail || hasTodoMarker;

  checks.push({
    category: CATEGORY,
    checkKey: "vibe_placeholder_content",
    label: "No placeholder / filler content in production",
    status: hasPlaceholderContent ? "FAIL" : "PASS",
    detail: hasPlaceholderContent
      ? `Placeholder content detected: ${[
          hasLoremIpsum && "lorem ipsum text",
          hasExampleEmail && "example email address",
          hasTodoMarker && "TODO/FIXME marker",
        ]
          .filter(Boolean)
          .join(", ")}. Strong signal of incomplete work shipped to production.`
      : "No placeholder text, lorem ipsum, or TODO/FIXME markers detected.",
  });

  // 2. Placeholder image services
  const hasPlaceholderImages =
    htmlLower.includes("picsum.photos") ||
    htmlLower.includes("placehold.co") ||
    htmlLower.includes("via.placeholder.com") ||
    htmlLower.includes("placeholder.com/") ||
    htmlLower.includes("placeimg.com") ||
    htmlLower.includes("dummyimage.com") ||
    htmlLower.includes("lorempixel.com") ||
    htmlLower.includes("placekitten.com");

  checks.push({
    category: CATEGORY,
    checkKey: "vibe_placeholder_images",
    label: "No placeholder / stock filler images",
    status: hasPlaceholderImages ? "FAIL" : "PASS",
    detail: hasPlaceholderImages
      ? "Placeholder image service detected (Lorem Picsum, via.placeholder.com, etc.). These must be replaced with real product visuals before launch."
      : "No placeholder image services detected.",
  });

  // 3. Debug / development mode signals
  const hasDebugSignals =
    htmlLower.includes("debug: true") ||
    htmlLower.includes("debug=true") ||
    htmlLower.includes("development mode") ||
    htmlLower.includes("__debug__") ||
    htmlLower.includes("node_env=development") ||
    htmlLower.includes("webpack hmr") ||
    htmlLower.includes("hot module replacement") ||
    htmlLower.includes("vite dev server") ||
    htmlLower.includes("[vite]");

  checks.push({
    category: CATEGORY,
    checkKey: "vibe_debug_mode",
    label: "No debug or development mode signals",
    status: hasDebugSignals ? "FAIL" : "PASS",
    detail: hasDebugSignals
      ? "Debug or development mode signals detected in page HTML. These expose internal state and indicate the production build is not properly configured."
      : "No debug or development mode markers detected.",
  });

  // 4. Framework default page title
  const titleMatch = htmlLower.match(/<title[^>]*>([^<]*)<\/title>/);
  const pageTitle = titleMatch?.[1]?.trim() ?? "";
  const isDefaultTitle =
    pageTitle === "vite + react" ||
    pageTitle === "vite + react + ts" ||
    pageTitle === "create next app" ||
    pageTitle === "react app" ||
    pageTitle === "next.js app" ||
    pageTitle === "my app" ||
    pageTitle === "untitled" ||
    pageTitle === "" ||
    pageTitle === "app" ||
    pageTitle.startsWith("localhost");

  checks.push({
    category: CATEGORY,
    checkKey: "vibe_default_title",
    label: "Meaningful page title (not a framework default)",
    status: isDefaultTitle ? "WARN" : "PASS",
    detail: isDefaultTitle
      ? `Page title is "${pageTitle || "(empty)"}" — a framework scaffold default. Every page needs a meaningful, branded title for SEO and user trust.`
      : `Page title is set: "${pageTitle.slice(0, 60)}${pageTitle.length > 60 ? "…" : ""}".`,
  });

  // 5. AI-generated comment markers in source
  const hasAiComments =
    htmlLower.includes("// generated by claude") ||
    htmlLower.includes("// generated by chatgpt") ||
    htmlLower.includes("// generated by ai") ||
    htmlLower.includes("// ai-generated") ||
    htmlLower.includes("<!-- todo") ||
    htmlLower.includes("<!-- fixme") ||
    htmlLower.includes("// todo: implement") ||
    htmlLower.includes("// todo: add error") ||
    htmlLower.includes("// hack:");

  checks.push({
    category: CATEGORY,
    checkKey: "vibe_ai_comment_markers",
    label: "No AI-generated comment markers in page source",
    status: hasAiComments ? "WARN" : "PASS",
    detail: hasAiComments
      ? "AI-generated comment markers or TODO/FIXME comments found in page source — unfinished work shipped to production."
      : "No AI-generated or unresolved TODO comment markers detected in page source.",
  });

  // 6. Hardcoded test credentials visible in HTML
  const hasTestCreds =
    htmlLower.includes("admin@example.com") ||
    htmlLower.includes("password123") ||
    htmlLower.includes("test@test.com") ||
    htmlLower.includes("admin@admin.com") ||
    htmlLower.includes("demo@demo.com") ||
    (htmlLower.includes("password") && htmlLower.includes("123456"));

  checks.push({
    category: CATEGORY,
    checkKey: "vibe_hardcoded_creds_html",
    label: "No hardcoded test credentials in page HTML",
    status: hasTestCreds ? "FAIL" : "PASS",
    detail: hasTestCreds
      ? "Hardcoded test credentials detected in page HTML — remove before launch."
      : "No hardcoded test credentials detected in page HTML.",
  });

  // 7. Custom 404 page (HEAD a non-existent path)
  let custom404Status: PulseScanCheckInput["status"] = "PASS";
  let custom404Detail = "Custom 404 handling confirmed.";
  try {
    const notFoundStatus = await headRequest(`${httpsUrl}/pulse-check-nonexistent-path-404`);
    if (notFoundStatus === 200) {
      custom404Status = "WARN";
      custom404Detail =
        "Missing path returns 200 OK — no custom 404 page. Users reaching broken links see the homepage instead of a clear error.";
    } else if (notFoundStatus === 0) {
      custom404Status = "WARN";
      custom404Detail = "Could not verify 404 handling — request timed out.";
    } else {
      custom404Detail = `Returns ${notFoundStatus} for unknown paths — 404 handling is in place.`;
    }
  } catch {
    custom404Status = "WARN";
    custom404Detail = "Could not verify 404 handling.";
  }

  checks.push({
    category: CATEGORY,
    checkKey: "vibe_no_custom_404",
    label: "Custom 404 page for missing routes",
    status: custom404Status,
    detail: custom404Detail,
  });

  // 8. Images without alt text (basic accessibility signal)
  const imgTagMatches = htmlLower.match(/<img[^>]*>/g) ?? [];
  const emptyAltCount = imgTagMatches.filter(
    (tag) => tag.includes('alt=""') || tag.includes("alt=''") || !tag.includes("alt="),
  ).length;
  const totalImgs = imgTagMatches.length;
  const hasEmptyAlts = totalImgs > 2 && emptyAltCount / totalImgs > 0.6;

  checks.push({
    category: CATEGORY,
    checkKey: "vibe_empty_alt_images",
    label: "Images have descriptive alt text",
    status: hasEmptyAlts ? "WARN" : "PASS",
    detail: hasEmptyAlts
      ? `${emptyAltCount} of ${totalImgs} images are missing alt text — a common AI code generator oversight that fails WCAG 2.1 AA and harms SEO.`
      : totalImgs === 0
        ? "No images detected on the page."
        : `${totalImgs - emptyAltCount} of ${totalImgs} images have alt text.`,
  });

  return checks;
}
