import { notFound } from "next/navigation";
import { getOnboardingByTokenPublic, recordOnboardingFirstView } from "@/server/onboarding";
import { OnboardingFlow } from "./onboarding-flow";

export const dynamic = "force-dynamic";

// Generic OG/Twitter preview (the og-image is generated by opengraph-image.tsx
// in this folder). Deliberately no client data — link unfurls are public to
// anyone the token is forwarded to.
const PREVIEW_TITLE = "Project onboarding — Gitwork";
const PREVIEW_DESCRIPTION =
  "A quick, secure onboarding for your project with Gitwork.";

export const metadata = {
  title: PREVIEW_TITLE,
  description: PREVIEW_DESCRIPTION,
  openGraph: {
    title: PREVIEW_TITLE,
    description: PREVIEW_DESCRIPTION,
    siteName: "Gitwork",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: PREVIEW_TITLE,
    description: PREVIEW_DESCRIPTION,
  },
};

export default async function OnboardingPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const session = await getOnboardingByTokenPublic(token);
  if (!session) notFound();

  // Record the first open (best-effort; never blocks render) so Portal can show
  // whether the client has opened the link.
  await recordOnboardingFirstView(token);

  return <OnboardingFlow token={token} initialSession={session} />;
}
