#!/usr/bin/env bash
#
# Foundry STAGING — generate /opt/apps/foundry-staging/.env with fresh secrets.
#
# Run this ON THE VPS. Every random secret is generated locally and written
# straight to the file, so no secret value ever travels through Slack, a chat
# window, or a terminal you screenshot. That is the whole point of this script:
# the production .env leaked in July 2026 precisely because its values were
# pasted into a message.
#
#   cd /opt/apps/foundry-staging
#   bash generate-env.sh
#
# It REFUSES to overwrite an existing .env — pass --force if you truly mean to
# (which regenerates ENCRYPTION_KEY and makes any already-encrypted staging data
# unreadable; harmless on a fresh box, not harmless later).
#
# Afterwards, four values must be pasted in by hand — the script prints exactly
# which and where they come from. Everything else is done.

set -euo pipefail

TARGET="${TARGET:-.env}"
STAGING_URL="https://staging.foundry.gitwork.tech"

if [[ -f "$TARGET" && "${1:-}" != "--force" ]]; then
  echo "ERROR: $TARGET already exists. Refusing to overwrite." >&2
  echo "       Regenerating ENCRYPTION_KEY makes existing encrypted rows unreadable." >&2
  echo "       If you're sure: bash generate-env.sh --force" >&2
  exit 1
fi

command -v openssl >/dev/null || { echo "ERROR: openssl not found." >&2; exit 1; }

# ── Generate ─────────────────────────────────────────────────────────────────
# Passwords go through `tr -d` to strip characters that would need quoting or
# escaping inside a URL-form connection string. A Postgres password containing
# @ : / or # silently truncates DATABASE_URL at parse time, which presents as an
# authentication failure against a host you didn't type.
gen_pw()   { openssl rand -base64 36 | tr -d '\n=+/@:#?&' | cut -c1-32; }
gen_b64()  { openssl rand -base64 32 | tr -d '\n'; }          # 32 bytes, for AES-256
gen_auth() { openssl rand -base64 33 | tr -d '\n'; }          # NextAuth convention
gen_hex()  { openssl rand -hex 32 | tr -d '\n'; }

POSTGRES_PASSWORD="$(gen_pw)"
AUTH_SECRET="$(gen_auth)"
API_KEY="$(gen_b64)"
ENCRYPTION_KEY="$(gen_b64)"
CRON_SECRET="$(gen_hex)"
PROVENANCE_SIGNING_SECRET="$(gen_b64)"

# Sanity-check the one value whose FORMAT the app validates at runtime:
# src/lib/encryption.ts requires ENCRYPTION_KEY to base64-decode to exactly 32
# bytes and throws on anything else. Catching that here beats catching it as a
# 500 on the onboarding flow.
decoded_len=$(printf '%s' "$ENCRYPTION_KEY" | base64 -d 2>/dev/null | wc -c | tr -d ' ')
if [[ "$decoded_len" != "32" ]]; then
  echo "ERROR: generated ENCRYPTION_KEY decodes to ${decoded_len} bytes, expected 32." >&2
  exit 1
fi

umask 077   # so the file is 600 from the moment it exists, not after chmod

cat > "$TARGET" <<EOF
# ─────────────────────────────────────────────────────────────────────────────
# Foundry STAGING — generated by deploy/staging/generate-env.sh
# Host: ${STAGING_URL}
#
# Secrets here are STAGING-ONLY and share nothing with production. Do not paste
# this file into Slack, a ticket, or a chat window.
# Full reference: docs/staging-environment.md
# ─────────────────────────────────────────────────────────────────────────────

NODE_ENV=production

# ── Database ─────────────────────────────────────────────────────────────────
# Host 'db' is the compose-internal service in THIS project (foundry-staging),
# not production's. sslmode=disable is correct on a compose-internal network.
DATABASE_URL="postgresql://foundry:${POSTGRES_PASSWORD}@db:5432/foundry?sslmode=disable"
DIRECT_URL="postgresql://foundry:${POSTGRES_PASSWORD}@db:5432/foundry?sslmode=disable"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"

# ── Auth ─────────────────────────────────────────────────────────────────────
# NEXTAUTH_URL builds the redirect_uri sent to Google. Wrong value ⇒ the flow
# completes and lands the user on PRODUCTION, with no error anywhere.
NEXTAUTH_URL="${STAGING_URL}"
AUTH_SECRET="${AUTH_SECRET}"
AUTH_TRUST_HOST=true

# ⚠️ PASTE THESE TWO — the "Foundry Login" OAuth client (Google Cloud Console →
# APIs & Services → Credentials). Its redirect URIs must already include
# ${STAGING_URL}/api/auth/callback/google
AUTH_GOOGLE_ID=""
AUTH_GOOGLE_SECRET=""

# "Foundry Care" client — Gmail/Calendar/Drive connector. A DIFFERENT client from
# the login one. Blank ⇒ Care connectors unavailable, which is the right staging
# default until you need them.
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""
GOOGLE_IOS_SERVER_CLIENT_ID=""

# ── App / API auth + encryption ──────────────────────────────────────────────
API_KEY="${API_KEY}"
NEXT_PUBLIC_API_KEY="${API_KEY}"
# Staging's OWN key. Deliberately NOT production's: that one decrypts real client
# bank details, and a staging box holding it means staging shell access reads
# client banking data. Consequence of it differing: any bank rows in a restored
# production dump are unreadable here. That is intended.
ENCRYPTION_KEY="${ENCRYPTION_KEY}"

# ── Outbound link URLs ───────────────────────────────────────────────────────
# Unset, BOTH default to the production URL (src/server/notifications.ts,
# src/server/slack/blocks.ts, src/app/layout.tsx) — staging notifications would
# then deep-link into production. Read server-side only, so runtime env is
# sufficient; no Docker build arg needed.
NEXT_PUBLIC_APP_URL="${STAGING_URL}"
NEXT_PUBLIC_SITE_URL="${STAGING_URL}"

# ── Crons ────────────────────────────────────────────────────────────────────
CRON_SECRET="${CRON_SECRET}"

# ── Initial admin — intentionally blank ──────────────────────────────────────
# These CANNOT produce a login. Google is the only NextAuth provider
# (src/auth.ts) — there is no Credentials provider and no password login route
# for /app, so the passwordHash these would write is never compared.
# Your User + WorkspaceMember row is created automatically on first Google
# sign-in instead.
INITIAL_ADMIN_EMAIL=""
INITIAL_ADMIN_PASSWORD=""

# ── AI — PASTE IF YOU WANT AI FEATURES ───────────────────────────────────────
# Use a staging-specific key with its own spend cap so staging scans don't draw
# on the production budget. Per-workspace keys also live in the DB (Settings → AI
# provider) and take precedence; these are the fallback.
ANTHROPIC_API_KEY=""
ANTHROPIC_ADMIN_KEY=""
OPENAI_API_KEY=""
GEMINI_API_KEY=""

# ── Provenance ───────────────────────────────────────────────────────────────
# Staging's own seal. A Countermark sealed here must NOT verify as one issued by
# production — that is the entire point of a seal (CLAUDE.md §38).
PROVENANCE_SIGNING_SECRET="${PROVENANCE_SIGNING_SECRET}"

# ── Optional — blank is fine ─────────────────────────────────────────────────
GITHUB_TOKEN=""                    # Pulse repo scans. Prefer a READ-ONLY PAT here
GOOGLE_PSI_API_KEY=""              # better Pulse PageSpeed quota
DEEPGRAM_API_KEY=""                # DevSignal transcription
DEVSIGNAL_ACCESS_PASSWORD=""       # defaults to "gitwork-devsignal" if unset
NEXT_PUBLIC_TURNSTILE_SITE_KEY=""  # public Pulse embed bot-gate
TURNSTILE_SECRET_KEY=""
COLD_STORE_DIR=""                  # retention cold store; unset ⇒ feature off

# ── iOS push — blank unless testing push ─────────────────────────────────────
# If you DO fill these in, APNS_PRODUCTION must be "false": sandbox tokens from a
# dev/TestFlight build are rejected outright by the production APNs endpoint,
# which presents as "push is broken".
APNS_AUTH_KEY=""
APNS_KEY_ID=""
APNS_TEAM_ID=""
APNS_BUNDLE_ID="uk.co.gitwork.axisapp"
APNS_PRODUCTION="false"

# ── Web push (VAPID) — blank unless testing ──────────────────────────────────
# Generate a STAGING pair (npx web-push generate-vapid-keys). Sharing
# production's pair lets staging push to browsers subscribed via production.
VAPID_PUBLIC_KEY=""
VAPID_PRIVATE_KEY=""
VAPID_SUBJECT="mailto:dan@gitwork.co.uk"

# ── Client system credentials — LEAVE BLANK ──────────────────────────────────
# Real logins to a real client's systems. Staging has no business holding them.
WEDGE_APP_API_USER=""
WEDGE_APP_API_PASSWORD=""
WEDGE_COURSE_API_USER=""
WEDGE_COURSE_API_PASSWORD=""
EOF

chmod 600 "$TARGET"

cat <<'DONE'

✅ Wrote .env (mode 600) with freshly generated staging secrets.

   Generated for you, no action needed:
     POSTGRES_PASSWORD · AUTH_SECRET · API_KEY · NEXT_PUBLIC_API_KEY
     ENCRYPTION_KEY (verified to decode to 32 bytes) · CRON_SECRET
     PROVENANCE_SIGNING_SECRET

   None of these match production. That is deliberate.

⚠️  Two values you MUST paste in before login will work:

     AUTH_GOOGLE_ID       Google Cloud Console → APIs & Services → Credentials
     AUTH_GOOGLE_SECRET   → the "Foundry Login" web client
                            (Client ID begins 863801453214-1dv17p3eqf94ncl…)

     That client's Authorised redirect URIs must ALSO already contain:
       https://staging.foundry.gitwork.tech/api/auth/callback/google

     (Authorised JavaScript origins are NOT needed — this app uses NextAuth's
      server-side code flow, not a browser-side Google SDK.)

     Edit with:  nano .env       (or: vi .env)

🔵  Optional, only if you want the feature:
     ANTHROPIC_API_KEY (AI), GITHUB_TOKEN (Pulse repo scans — read-only PAT)

Then:  docker compose up -d db && docker compose up -d app
Full runbook: docs/staging-environment.md
DONE
