#!/usr/bin/env node
/**
 * Regenerates `src/server/pulse-checks/catalogue-baseline.json` — the record of
 * every Pulse check key that exists, which `catalogue-compat.test.ts` holds the
 * registry to.
 *
 * Run it when you ADD a check (the test will tell you to). When you need to
 * REMOVE one, do not run it first: add a RETIRED_CHECKS entry in
 * `catalogue-compat.ts` explaining what replaced the key, then run it — the
 * baseline keeps the key listed as retired so old scans stay readable.
 *
 *   npm run pulse:catalogue
 *   npm run pulse:catalogue -- --check    # report drift, write nothing (exit 1)
 */

import { readFileSync, writeFileSync } from "node:fs";
import { CHECKS_REGISTRY } from "../src/server/checks-registry";
import { CATALOGUE_VERSION, RETIRED_CHECKS } from "../src/server/pulse-checks/catalogue-compat";

const BASELINE_PATH = "src/server/pulse-checks/catalogue-baseline.json";
const checkOnly = process.argv.includes("--check");

const registered = CHECKS_REGISTRY.map((definition) => definition.key);
const retired = Object.keys(RETIRED_CHECKS);
const keys = [...new Set([...registered, ...retired])].sort();

const next = {
  $comment:
    "Generated by `npm run pulse:catalogue`. Every key here is a public identifier " +
    "referenced by stored scans and per-workspace check configuration — see " +
    "src/server/pulse-checks/catalogue-compat.ts before removing one.",
  catalogueVersion: CATALOGUE_VERSION,
  totals: {
    keys: keys.length,
    registered: registered.length,
    retired: retired.length,
  },
  keys,
};

const serialised = `${JSON.stringify(next, null, 2)}\n`;

let previousRaw = "";
try {
  previousRaw = readFileSync(BASELINE_PATH, "utf8");
} catch {
  // First run — there is no baseline to compare against.
}

if (previousRaw === serialised) {
  console.log(`✓ ${BASELINE_PATH} is current (${keys.length} keys).`);
  process.exit(0);
}

if (checkOnly) {
  const previous: { keys?: string[] } = previousRaw ? JSON.parse(previousRaw) : {};
  const before = new Set(previous.keys ?? []);
  const after = new Set(keys);
  const added = keys.filter((key) => !before.has(key));
  const removed = [...before].filter((key) => !after.has(key));
  console.error(`✗ ${BASELINE_PATH} is out of date.`);
  if (added.length) console.error(`  ${added.length} added:   ${added.slice(0, 10).join(", ")}${added.length > 10 ? " …" : ""}`);
  if (removed.length) console.error(`  ${removed.length} removed: ${removed.slice(0, 10).join(", ")}${removed.length > 10 ? " …" : ""}`);
  console.error("  Run `npm run pulse:catalogue` to refresh it.");
  process.exit(1);
}

writeFileSync(BASELINE_PATH, serialised);
console.log(`✓ Wrote ${BASELINE_PATH} — ${keys.length} keys (${registered.length} registered, ${retired.length} retired).`);
